Repository pluralsh/plural, pull requests merged in 2022-05, with the labels that each got.

#218 Design fixes 2
  www/package-lock.json
  www/package.json
  www/src/components/Explore.js
  www/src/components/ModalHeader.js
  www/src/components/accounts/CreateServiceAccount.js
  www/src/components/accounts/Domains.js
  www/src/components/accounts/Group.js
  www/src/components/accounts/Role.js
  www/src/components/accounts/ServiceAccounts.js
  www/src/components/accounts/User.js
  www/src/components/incidents/CreateIncident.js
  www/src/components/incidents/File.js
  www/src/components/incidents/Incident.js
  www/src/components/incidents/Incidents.js
  www/src/components/incidents/Markdown.js
  www/src/components/incidents/MessageControls.js
  www/src/components/incidents/MessageReactions.js
  www/src/components/incidents/Responses.js
  www/src/components/incidents/Sidebar.js
  www/src/components/incidents/ViewSwitcher.js
  www/src/components/integrations/CreateWebhook.js
  www/src/components/integrations/OAuthIntegrations.js
  www/src/components/integrations/WebhookLog.js
  www/src/components/metrics/Graph.js
  www/src/components/payments/CreatePlan.js
  www/src/components/payments/Invoices.js
  www/src/components/payments/Plan.js
  www/src/components/payments/Subscription.js
  www/src/components/repos/Artifacts.js
  www/src/components/repos/Chart.js
  www/src/components/repos/DeferredUpdates.js
  www/src/components/repos/Docker.js
  www/src/components/repos/DockerImages.js
  www/src/components/repos/Integrations.js
  www/src/components/repos/PackageScan.js
  www/src/components/users/Billing.js
  www/src/components/users/BillingDetails.js
  www/src/components/users/EditUser.js
  www/src/components/users/EmailConfirmation.js
  www/src/components/users/Tokens.js
  www/src/components/utils/Confirm.js
  www/src/components/utils/Copyable.js
  www/src/components/utils/ModalHeader.js
  www/src/components/utils/Steps.js
  www/src/components/utils/Tabs.js
  www/src/theme.js
Labels: enhancement, design

#224 Add Labels to PR Template and improve checklist
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#225 Add release notes template for automatic release generation.
  .github/release.yml
Labels: documentation

#227 Auto-Infer git user via oauth information
  apps/core/lib/core/schema/cloud_shell.ex
  apps/core/lib/core/services/shell.ex
  apps/core/lib/core/services/shell/demo.ex
  apps/core/lib/core/services/shell/scm.ex
  apps/core/lib/core/services/shell/scm/github.ex
  apps/core/priv/repo/migrations/20220511165641_shell_git_info.exs
  apps/core/test/services/shell_test.exs
  apps/core/test/test_helper.exs
  apps/graphql/test/mutations/shell_mutations_test.exs
Labels: enhancement

#228 Add side-by-side selection for demo and bring-your-own-cloud
  apps/core/lib/core/schema/group_member.ex
  apps/core/mix.exs
  mix.lock
  www/src/components/shell/CloudShell.js
  www/src/components/shell/cloud/provider.js
Labels: enhancement

#229 Allow Users to create a fixed number of demo projects
  apps/core/lib/core/policies/account.ex
  apps/core/lib/core/schema/user.ex
  apps/core/lib/core/services/shell/demo.ex
  apps/core/priv/repo/migrations/20220513214234_demo-project-counts.exs
  apps/core/test/services/shell/demo_test.exs
Labels: enhancement, dependencies

#219 Repositories
  www/package-lock.json
  www/package.json
  www/src/components/ModalHeader.js
  www/src/components/Plural.js
  www/src/components/ResponsiveInput.js
  www/src/components/Socials.js
  www/src/components/Toolbar.js
  www/src/components/explore/Explore.js
  www/src/components/explore/ExploreRepositories.js
  www/src/components/explore/ExploreSidebar.js
  www/src/components/explore/queries.js
  www/src/components/incidents/Markdown.js
  www/src/components/payments/Invoices.js
  www/src/components/repos/SearchRepositories.js
  www/src/components/repos/queries.js
  www/src/components/repository/Repository.js
  www/src/components/repository/RepositoryArtifacts.js
  www/src/components/repository/RepositoryDeployments.js
  www/src/components/repository/RepositoryDescription.js
  www/src/components/repository/RepositoryEdit.js
  www/src/components/repository/RepositoryHeader.js
  www/src/components/repository/RepositoryPackages.js
  www/src/components/repository/RepositoryPackagesDocker.js
  www/src/components/repository/RepositoryPackagesHelm.js
  www/src/components/repository/RepositoryPackagesTerraform.js
  www/src/components/repository/RepositoryTests.js
  www/src/components/repository/queries.js
  www/src/components/shell/cloud/demo.js
  www/src/components/shell/cloud/provider.js
  www/src/components/shell/cloud/types.js
  www/src/components/users/MagicLogin.js
  www/src/components/utils/Code.js
  www/src/components/utils/InfiniteScroller.js
  www/src/contexts/RepositoryContext.js
  www/src/helpers/client.js
  www/src/hooks/useBreadcrumbs.js
  www/src/hooks/usePaginatedQuery.js
  www/src/index.css
  www/src/index.js
  www/src/utils/file.js
  www/src/utils/string.js
Labels: enhancement, design

#231 Overhaul API error messages
  apps/core/lib/core/policies/dns.ex
  apps/core/lib/core/policies/repository.ex
  apps/core/lib/core/policies/test.ex
  apps/core/mix.exs
  mix.lock
Labels: bug-fix

#230 New Repositories scene follow up: Delete installation and more.
  www/package-lock.json
  www/package.json
  www/src/components/Plural.js
  www/src/components/Sidebar.js
  www/src/components/explore/Explore.js
  www/src/components/explore/ExploreRepositories.js
  www/src/components/explore/ExploreSidebar.js
  www/src/components/explore/queries.js
  www/src/components/repository/Repository.js
  www/src/components/repository/RepositoryEdit.js
  www/src/components/repository/RepositoryHeader.js
  www/src/components/repository/queries.js
  www/src/components/shell/CloudShell.js
  www/src/components/shell/cloud/provider.js
  www/src/components/shell/query.js
  www/src/components/shell/validation.js
  www/src/components/users/EditUser.js
  www/src/hooks/usePaginatedQuery.js
  www/src/models/shell.js
  www/src/theme.js
Labels: enhancement, design

#233 Gitlab OAuth Support
  apps/core/lib/core/oauth.ex
  apps/core/lib/core/oauth/base.ex
  apps/core/lib/core/oauth/github.ex
  apps/core/lib/core/oauth/gitlab.ex
  apps/core/lib/core/oauth/google.ex
  apps/core/lib/core/services/shell/scm.ex
  apps/graphql/lib/graphql/schema/oauth.ex
  plural/helm/plural/Chart.yaml
  plural/helm/plural/templates/secret.yaml
  plural/helm/plural/values.yaml
  www/public/gitlab.svg
  www/src/components/users/OauthEnabler.js
Labels: enhancement

#234 Add Shell SCM Support for Gitlab
  apps/core/lib/core/oauth/gitlab.ex
  apps/core/lib/core/services/shell/scm.ex
  apps/core/lib/core/services/shell/scm/gitlab.ex
  apps/core/test/services/shell_test.exs
  apps/graphql/lib/graphql/schema/shell.ex
  apps/graphql/test/queries/shell_queries_test.exs
  www/package.json
  www/src/components/shell/scm/gitlab.js
  www/yarn.lock
Labels: enhancement

#236 Support Provisioning Gitlab Repos in Cloud Shell
  www/package.json
  www/src/components/Plural.js
  www/src/components/shell/CloudShell.js
  www/src/components/shell/scm/ScmInput.js
  www/src/components/shell/scm/gitlab.js
  www/src/components/shell/scm/types.js
  www/yarn.lock
Labels: enhancement

#238 Refresh Cache on Role Updates
  apps/core/lib/core/pubsub/events.ex
  apps/core/lib/core/pubsub/protocols/cacheable.ex
  apps/core/lib/core/pubsub/protocols/fanout.ex
  apps/core/lib/core/schema/user.ex
  apps/core/test/pubsub/cache/users_test.exs
  apps/core/test/pubsub/fanout/accounts_test.exs
Labels: bug

#237 Application renewal: Remove some useless files
  www/src/components/repos/Installations.js
  www/src/components/repos/Recipe.js
  www/src/components/repos/Recipes.js
  www/src/components/repos/RepoDirectory.js
  www/src/components/repos/Repository.js
  www/src/components/repos/RepositoryTests.js
  www/src/components/upgrades/Rollouts.js
  www/src/components/upgrades/types.js
  www/src/utils/event.js
Labels: enhancement
