Repository pluralsh/plural, pull requests merged in 2022-06, with the labels that each got.

#246 Add multiselect for publisher, category and tag
  apps/core/lib/core/schema/repository.ex
  apps/graphql/lib/graphql/resolvers/repository.ex
  apps/graphql/lib/graphql/schema/repository.ex
Labels: enhancement

#248 Klink/add fonts
  www/public/ABCMonumentGroteskSemi-Mono-Heavy.woff
  www/public/ABCMonumentGroteskSemi-Mono-Medium.woff
  www/public/ABCMonumentGroteskSemi-Mono-Regular.woff
  www/public/index.html
Labels: enhancement, design

#250 Don't include avatar when bootstrapping from oauth
  apps/core/lib/core/oauth.ex
Labels: bug-fix

#244 Complete Marketplace Design
  www/package-lock.json
  www/package.json
  www/src/components/Explore.js
  www/src/components/ModalHeader.js
  www/src/components/ResponsiveInput.js
  www/src/components/Socials.js
  www/src/components/accounts/Audits.js
  www/src/components/accounts/Domains.js
  www/src/components/accounts/Group.js
  www/src/components/incidents/Markdown.js
  www/src/components/integrations/Webhook.js
  www/src/components/integrations/Webhooks.js
  www/src/components/layout/ApplicationLayout.js
  www/src/components/layout/Sidebar.js
  www/src/components/layout/WithNotifications.js
  www/src/components/marketplace/Marketplace.js
  www/src/components/marketplace/MarketplaceRepositories.js
  www/src/components/marketplace/MarketplaceSidebar.js
  www/src/components/marketplace/queries.js
  www/src/components/oidc/OIDCProvider.js
  www/src/components/repos/Docker.js
  www/src/components/repos/DockerImages.js
  www/src/components/repos/Installation.js
  www/src/components/repos/SearchRepositories.js
  www/src/components/repos/Tags.js
  www/src/components/repository/InstallDropdownButton.js
  www/src/components/repository/Repository.js
  www/src/components/repository/RepositoryArtifacts.js
  www/src/components/repository/RepositoryDeployments.js
  www/src/components/repository/RepositoryDescription.js
  www/src/components/repository/RepositoryDescriptionMarkdown.js
  www/src/components/repository/RepositoryEdit.js
  www/src/components/repository/RepositoryHeader.js
  www/src/components/repository/RepositoryPackages.js
  www/src/components/repository/RepositoryPackagesDocker.js
  www/src/components/repository/RepositoryPackagesHelm.js
  www/src/components/repository/RepositoryPackagesTerraform.js
  www/src/components/repository/RepositoryTests.js
  www/src/components/repository/constants.js
  www/src/components/repository/queries.js
  www/src/components/upgrades/UpgradeQueue.js
  www/src/components/upgrades/UpgradeQueues.js
  www/src/components/users/Me.js
  www/src/components/users/Notifications.js
  www/src/components/utils/Code.js
  www/src/components/utils/Flyout.js
  www/src/components/versions/VersionTags.js
  www/src/hooks/usePaginatedQuery.js
Labels: enhancement, design

#252 Implement Onboarding, part 1
  www/package-lock.json
  www/package.json
  www/src/components/Plural.js
  www/src/components/incidents/AttachmentProvider.js
  www/src/components/login/CurrentUser.js
  www/src/components/shell/CloudShell.js
  www/src/components/shell/SplashToLogoTransition.js
  www/src/components/shell/cloud/CloudCredentials.js
  www/src/components/shell/cloud/CloudDecision.js
  www/src/components/shell/cloud/InstallCli.js
  www/src/components/shell/cloud/aws.js
  www/src/components/shell/cloud/gcp.js
  www/src/components/shell/cloud/provider.js
  www/src/components/shell/constants.js
  www/src/components/shell/icons.js
  www/src/components/shell/scm/ScmInput.js
  www/src/components/shell/scm/github.js
  www/src/components/shell/scm/gitlab.js
  www/src/components/shell/validation.js
Labels: enhancement, design

#253 Allow oauth users to bypass icon validation
  apps/core/lib/core/oauth.ex
  apps/core/lib/core/schema/user.ex
  apps/core/lib/core/services/storage.ex
  apps/core/test/oauth_test.exs
  apps/core/test/test_helper.exs
Labels: bug-fix

#255 Add longform recipe docstrings
  apps/core/lib/core/schema/recipe_item.ex
  apps/graphql/lib/graphql/schema/recipe.ex
Labels: enhancement

#256 Recipe Docgen Script
  apps/graphql/lib/graphql/resolvers/repository.ex
  bin/docgen.py
  bin/requirements.txt
Labels: documentation

#254 Implement Login/Sign-up flow
  www/public/plural-white-cropped.png
  www/public/plural-white-word-cropped.png
  www/src/components/users/MagicLogin.js
Labels: enhancement, design

#257 Send demo information to cloud shell
  apps/core/lib/core/services/shell/client.ex
  apps/core/lib/core/services/shell/pods.ex
  apps/core/test/services/shell/client_test.exs
Labels: enhancement

#258 Fix formatting for docgen script.
  bin/docgen.py
Labels: documentation

#260 Support Listing Roles per user
  apps/core/lib/core/schema/group.ex
  apps/core/lib/core/schema/role.ex
  apps/graphql/lib/graphql/resolvers/account.ex
  apps/graphql/lib/graphql/schema/account.ex
  apps/graphql/test/queries/account_queries_test.exs
Labels: enhancement

#261 New Design Profile Screens
  apps/core/lib/core/services/users.ex
  package-lock.json
  www/package-lock.json
  www/package.json
  www/src/App.js
  www/src/components/Plural.js
  www/src/components/layout/Sidebar.js
  www/src/components/profile/AccessTokens.js
  www/src/components/profile/EabCredentials.js
  www/src/components/profile/Header.js
  www/src/components/profile/Icon.js
  www/src/components/profile/ListItem.js
  www/src/components/profile/Me.js
  www/src/components/profile/MyProfile.js
  www/src/components/profile/PublicKeys.js
  www/src/components/profile/Security.js
  www/src/components/profile/types.js
  www/src/components/utils/SidebarTabs.js
  www/src/components/utils/Table.js
  www/src/theme.js
Labels: enhancement

#263 Lint app
  www/package-lock.json
  www/package.json
  www/src/components/layout/Sidebar.js
  www/src/components/layout/WithApplicationUpdate.js
  www/src/components/profile/AccessTokens.js
  www/src/components/profile/Me.js
  www/src/components/repository/Repository.js
  www/src/components/shell/CloudShell.js
  www/src/components/shell/debug-tokens.js
  www/src/components/users/MagicLogin.js
  www/src/theme.js
Labels: enhancement, dependencies

#266 Finish onboarding flow
  www/package-lock.json
  www/package.json
  www/src/App.js
  www/src/components/shell/OAuthCallback.js
  www/src/components/shell/constants.js
  www/src/components/shell/debug-tokens.js
  www/src/components/shell/onboarding/OnboardingFlow.js
  www/src/components/shell/onboarding/OnboardingNavSection.js
  www/src/components/shell/onboarding/OnboardingWrapper.js
  www/src/components/shell/onboarding/cli/CliCompletion.js
  www/src/components/shell/onboarding/cli/CliInstallation.js
  www/src/components/shell/onboarding/cloud/CloudBuild.js
  www/src/components/shell/onboarding/cloud/CloudCredentials.js
  www/src/components/shell/onboarding/cloud/CloudLaunch.js
  www/src/components/shell/onboarding/cloud/CloudSelect.js
  www/src/components/shell/onboarding/cloud/provider.js
  www/src/components/shell/onboarding/synopsis/Synopsis.js
Labels: enhancement, dependencies, design

#273 hydra: add offline_access scope for refresh tokens
  apps/core/lib/core/services/oauth.ex
  apps/core/lib/core/services/repositories.ex
Labels: enhancement, bug-fix

#277 hydra: add offline scopes
  apps/core/lib/core/services/oauth.ex
  apps/core/lib/core/services/repositories.ex
Labels: bug-fix

#281 Backfill oidc scopes
  apps/core/lib/core/backfill/hydra.ex
  apps/core/priv/repo/seeds/08_migrate_hydra_clients.exs
  apps/core/test/backfill/hydra_test.exs
  www/src/components/shell/debug-tokens.js
Labels: bug

#283 Use new Discord link
  www/src/components/Socials.js
  www/src/components/shell/onboarding/cloud/CloudLaunch.js
Labels: enhancement
