Repository pluralsh/plural, pull requests merged in 2022-12, with the labels that each got.

#805 fix: expose template type in the API
  apps/graphql/lib/graphql/schema/version.ex
Labels: bug-fix

#719 fix(deps): upgrade to Elixir 1.12.3 and Erlang 24.3.4.6
  .github/workflows/publish.yaml
  .github/workflows/test.yaml
  .github/workflows/www.yaml
  .tool-versions
  Dockerfile
  apps/api/lib/api.ex
  apps/core/lib/core/services/accounts.ex
  apps/core/lib/core/services/shell/scm.ex
  apps/core/lib/core/services/users.ex
  apps/core/mix.exs
  mix.lock
Labels: dependencies

#802 Add call to setupShell before entering cloud shell
  www/src/components/shell/Terminal.tsx
  www/src/components/shell/onboarding/cloud/CloudLaunch.tsx
  www/src/components/shell/queries.ts
Labels: enhancement, frontend

#812 fix(backend): module ssh_file missing during demo project
  apps/core/mix.exs
Labels: bug-fix, backend

#736 Paginate docker images in ImageVersionPicker on Docker page
  www/src/components/repos/Docker.tsx
  www/src/components/repos/queries.ts
Labels: enhancement, frontend

#815 Add installation source
  apps/core/lib/core.ex
  apps/core/lib/core/schema/cloud_shell.ex
  apps/core/lib/core/schema/demo_project.ex
  apps/core/lib/core/schema/installation.ex
  apps/core/lib/core/services/repositories.ex
  apps/core/lib/core/services/shell.ex
  apps/core/lib/core/services/shell/demo.ex
  apps/core/priv/repo/migrations/20221204020315_add_installation_source.exs
  apps/core/test/services/repositories_test.exs
Labels: enhancement, backend

#816 Feat: Fix console button not showing on OnboardingCompletionModal
  www/src/components/shell/OnboardingCompletionModal.tsx
  www/src/components/shell/TerminalSidebar.tsx
Labels: bug-fix, frontend

#819 Add support for filtering repos by provider
  apps/core/lib/core/schema/repository.ex
  apps/graphql/lib/graphql/resolvers/repository.ex
  apps/graphql/lib/graphql/schema/repository.ex
  apps/graphql/test/queries/repository_queries_test.exs
Labels: enhancement, backend

#818 Migrate to new shell pod configuration apis
  apps/core/lib/core/services/shell.ex
  apps/core/lib/core/services/shell/models.ex
  apps/core/test/services/shell_test.exs
  apps/graphql/lib/graphql/schema/shell.ex
  apps/graphql/test/mutations/shell_mutations_test.exs
  apps/graphql/test/queries/shell_queries_test.exs
Labels: enhancement, backend

#823 Add stack install apis
  apps/core/lib/core/schema/stack.ex
  apps/core/lib/core/services/recipes.ex
  apps/core/lib/core/services/shell.ex
  apps/core/test/services/recipes_test.exs
  apps/core/test/services/shell_test.exs
  apps/graphql/lib/graphql/resolvers/recipe.ex
  apps/graphql/lib/graphql/resolvers/shell.ex
  apps/graphql/lib/graphql/schema/recipe.ex
  apps/graphql/lib/graphql/schema/shell.ex
  apps/graphql/test/mutations/recipe_mutation_test.exs
  apps/graphql/test/mutations/shell_mutations_test.exs
  apps/graphql/test/queries/recipe_queries_test.exs
Labels: enhancement, backend

#820 Lazy load routes
  www/package.json
  www/src/App.tsx
  www/src/components/Plural.tsx
  www/yarn.lock
Labels: enhancement, frontend

#826 Add extraSecretEnv to plural chart
  plural/helm/plural/Chart.yaml
  plural/helm/plural/templates/secret.yaml
  plural/helm/plural/values.yaml
Labels: enhancement, backend

#814 chore(artifact): use updated busybox image for migration
  plural/helm/plural/Chart.yaml
  plural/helm/plural/templates/_helpers.tpl
Labels: dependencies

#828 Add generic provider
  apps/core/lib/core/schema/dependencies.ex
  apps/core/lib/core/schema/provider_scaffold.ex
  apps/core/lib/core/schema/recipe.ex
  apps/core/priv/scaffolds/terraform/providers/0.1.0/generic.eex
  apps/core/priv/scaffolds/terraform/providers/generic.eex
  rel/config/config.exs
  www/src/components/repos/constants.ts
  www/src/components/repository/RepositoryPackagesTerraform.tsx
  www/src/components/utils/InstallDropdownButton.tsx
  www/src/generated/graphql.ts
Labels: enhancement

#825 Better error handling for Ecto.NoResultsError
  apps/graphql/lib/graphql/schema/base/helpers.ex
Labels: enhancement, backend

#830 Send emails to all service account bindings
  apps/core/lib/core/services/accounts.ex
  apps/email/lib/email/builder/base.ex
  apps/email/lib/email/builder/locked_installation.ex
  apps/email/test/email/builder/locked_installation_test.exs
Labels: enhancement, backend
