Repository pluralsh/plural, pull requests merged in 2022-09, with the labels that each got.

#497 ENG-308 - Account Refinement
  www/src/components/account/Account.tsx
  www/src/components/account/AccountAttributes.tsx
  www/src/components/account/CreateGroup.js
  www/src/components/account/CreateRole.js
  www/src/components/account/CreateServiceAccount.js
  www/src/components/account/DnsRecords.js
  www/src/components/account/Domains.js
  www/src/components/account/EditGroup.js
  www/src/components/account/EditRole.js
  www/src/components/account/Group.js
  www/src/components/account/Groups.js
  www/src/components/account/GroupsList.js
  www/src/components/account/InviteUser.js
  www/src/components/account/Invites.js
  www/src/components/account/List.tsx
  www/src/components/account/MoreMenu.js
  www/src/components/account/MoreMenu.tsx
  www/src/components/account/Role.js
  www/src/components/account/RoleForm.js
  www/src/components/account/Roles.js
  www/src/components/account/ServiceAccounts.js
  www/src/components/account/Typeaheads.js
  www/src/components/account/User.js
  www/src/components/account/Users.js
  www/src/components/account/UsersList.js
  www/src/components/layout/ApplicationLayout.js
  www/src/components/profile/AccessTokens.js
  www/src/components/profile/EabCredentials.js
  www/src/components/profile/Icon.tsx
  www/src/components/profile/PublicKeys.js
  www/src/components/utils/CopyableButton.tsx
  www/src/components/utils/GoBack.js
  www/src/components/utils/IconButtons.tsx
  www/src/components/utils/List.tsx
  www/src/components/utils/ListInput.tsx
Labels: enhancement, design, frontend

#503 Prune invites
  apps/core/lib/core/schema/invite.ex
  apps/cron/lib/cron/prune/invite.ex
  apps/cron/test/cron/prune/invites_test.exs
  apps/graphql/lib/graphql/schema/account.ex
  apps/graphql/test/queries/account_queries_test.exs
  plural/helm/plural/Chart.yaml
  plural/helm/plural/values.yaml
Labels: enhancement, backend

#489 Update error handling for cloud shell
  apps/rtc/lib/rtc_web/channels/shell_channel.ex
  apps/rtc/test/rtc_web/channels/shell_channel_test.exs
  www/src/components/shell/TerminalThemeSelector.js
Labels: bug-fix, backend

#460 Add email helper module
  CONTRIBUTING.md
  apps/email/lib/email/helper.ex
  apps/email/lib/email_web/templates/email/confirm_email.html.eex
  apps/email/lib/email_web/templates/email/reset_password.html.eex
  apps/email/lib/email_web/templates/layout/email.html.eex
Labels: enhancement, backend

#505 Disable Passwordless Login
  apps/core/lib/core/firewall.ex
  apps/core/lib/core/pubsub/protocols/cacheable.ex
  apps/core/lib/core/schema/user.ex
  apps/core/lib/core/services/accounts.ex
  apps/core/mix.exs
  apps/core/test/firewall_test.exs
  apps/core/test/pubsub/cache/users_test.exs
  apps/core/test/services/users_test.exs
  apps/graphql/lib/graphql/schema/upload.ex
  apps/graphql/test/mutations/user_mutation_test.exs
  mix.lock
  plural/terraform/aws/deps.yaml
  plural/terraform/aws/main.tf
  plural/terraform/gcp/deps.yaml
  www/src/components/profile/Security.js
Labels: bug-fix, backend

#506 Remove react-highlight.js
  www/package.json
  www/src/components/incidents/Markdown.js
  www/src/components/layout/DEBUG_NOTIFCATIONS.tsx
  www/src/components/layout/WithNotifications.js
  www/src/components/layout/WithNotifications.tsx
  www/src/components/repos/Artifacts.js
  www/src/components/repos/Chart.js
  www/src/components/repos/Installation.js
  www/src/components/utils/Highlight.js
  www/yarn.lock
Labels: dependencies, design, frontend

#508 ENG-588 - Optimize lodash imports
  www/src/components/account/Domains.js
  www/src/components/account/GroupsList.js
  www/src/components/account/Roles.js
  www/src/components/account/ServiceAccounts.js
  www/src/components/marketplace/MarketplaceRepositories.js
  www/src/components/marketplace/MarketplaceSidebar.js
  www/src/components/profile/PublicKeys.js
  www/src/components/repos/common/ImageVulnerabilities.js
  www/src/components/repos/common/PackageSecurity.js
  www/src/components/repository/InstallDropdownButton.js
  www/src/components/repository/InstallationConfiguration.js
  www/src/components/repository/RepositoryEdit.tsx
  www/src/components/repository/RepositoryHeader.js
  www/src/components/repository/RepositorySideNav.tsx
  www/src/components/shell/Terminal.js
  www/src/components/utils/Table.js
  www/src/hooks/useUpdateState.ts
  www/src/utils/string.js
Labels: enhancement, frontend

#507 Add missing gap to terraform provider icons and use components from design system
  www/package.json
  www/public/terraform.js
  www/src/components/incidents/Markdown.js
  www/src/components/repository/RepositoryPackagesTerraform.js
  www/src/components/utils/Copyable.js
  www/src/components/utils/DarkSelect.js
  www/src/components/utils/Highlight.js
  www/yarn.lock
Labels: design, bug-fix, frontend

#490 Implement Publisher screen
  www/src/components/Plural.js
  www/src/components/layout/Sidebar.js
  www/src/components/layout/TopBar.tsx
  www/src/components/marketplace/Marketplace.js
  www/src/components/marketplace/MarketplaceRepositories.js
  www/src/components/publisher/CreatePublisher.js
  www/src/components/publisher/CreatePublisherModal.tsx
  www/src/components/publisher/Publisher.old.js
  www/src/components/publisher/Publisher.tsx
  www/src/components/publisher/PublisherSideCar.tsx
  www/src/components/publisher/PublisherSideNav.tsx
  www/src/components/publisher/queries.js
  www/src/components/repos/Chart.js
  www/src/components/repos/Docker.js
  www/src/components/repos/Terraform.js
  www/src/components/repository/Repository.js
  www/src/components/repository/RepositoryEdit.tsx
  www/src/components/repository/RepositorySideNav.tsx
  www/src/components/utils/AnimatedLogo.js
  www/src/components/utils/GoBack.js
  www/src/components/utils/IconUploadPreview.tsx
Labels: enhancement, design, frontend

#509 Edit app refinements
  www/src/components/repository/RepositoryEdit.tsx
  www/src/hooks/useUpdateState.ts
  www/src/utils/string.js
Labels: enhancement, frontend

#511 Fix service worker issues with CRA build
  www/src/service-worker.js
Labels: bug-fix

#421 ENG-327: Plural release process
  .dockerignore
  .github/release.yml
  .github/workflows/publish.yaml
  .github/workflows/push-to-plural.yaml
  .github/workflows/test.yaml
  Dockerfile
  Makefile
  VERSION
  apps/api/mix.exs
  apps/core/mix.exs
  apps/cron/mix.exs
  apps/email/mix.exs
  apps/graphql/mix.exs
  apps/rtc/mix.exs
  apps/worker/mix.exs
  mix.exs
  rel/config.exs
Labels: enhancement

#517 Don't test elixir code for frontend changes
  .github/workflows/test.yaml
Labels: enhancement

#514 ENG-587 - Replace grommet-icons with design system icons
  www/package.json
  www/src/components/Explore.js
  www/src/components/Login.js
  www/src/components/Toolbar.js
  www/src/components/accounts/DnsRecords.js
  www/src/components/accounts/Domains.js
  www/src/components/accounts/EditAccount.js
  www/src/components/accounts/Group.js
  www/src/components/accounts/Invites.js
  www/src/components/accounts/Role.js
  www/src/components/accounts/ServiceAccounts.js
  www/src/components/clusters/UpgradeQueue.js
  www/src/components/clusters/UpgradeQueues.js
  www/src/components/incidents/CreateIncident.js
  www/src/components/incidents/File.js
  www/src/components/incidents/Incident.js
  www/src/components/incidents/IncidentControls.js
  www/src/components/incidents/IncidentHistory.js
  www/src/components/incidents/Incidents.js
  www/src/components/incidents/Responses.js
  www/src/components/incidents/Subscription.js
  www/src/components/login/AutoRefresh.js
  www/src/components/oidc/OAuthConsent.js
  www/src/components/payments/CreatePlan.js
  www/src/components/payments/CreateSubscription.js
  www/src/components/payments/Invoices.js
  www/src/components/payments/Plan.js
  www/src/components/publisher/MyPublisher.js
  www/src/components/repos/Artifacts.js
  www/src/components/repos/CreateRepository.js
  www/src/components/repos/EditInstallation.js
  www/src/components/repos/Integrations.js
  www/src/components/repository/RepositoryArtifacts.js
  www/src/components/shell/ShellStatus.js
  www/src/components/shell/TerminalInformation.js
  www/src/components/shell/onboarding/scm/OrgInput.js
  www/src/components/users/BillingDetails.js
  www/src/components/users/DeleteUser.js
  www/src/components/users/DeviceLoginNotif.js
  www/src/components/users/EmailConfirmation.js
  www/src/components/users/MagicLogin.js
  www/src/components/users/Me.js
  www/src/components/users/Notifications.js
  www/src/components/users/utils.js
  www/src/components/utils/Alert.js
  www/src/components/utils/Copyable.js
  www/src/components/utils/Flyout.js
  www/src/components/utils/ModalHeader.js
  www/src/components/utils/ReturnToBeginning.js
  www/src/utils/ignore-event.js
  www/yarn.lock
Labels: enhancement, design, frontend

#512 Fix user search query
  apps/core/lib/core/schema/user.ex
Labels: enhancement, backend

#519 ENG-599 Fix glitch during onboarding flow (screen-in-screen)
  www/src/components/shell/Terminal.js
  www/src/components/shell/onboarding/JoinCommunityCard.js
  www/src/components/shell/onboarding/ShellStatus.js
  www/src/components/shell/onboarding/cloud/CloudLaunch.js
  www/src/components/utils/Alert.js
Labels: design, bug-fix, frontend

#518 Remove test code for notifications
  www/src/components/layout/DEBUG_NOTIFCATIONS.tsx
  www/src/components/layout/WithNotifications.tsx
Labels: bug-fix, frontend

#520 Fix lint warning
  www/src/components/layout/WithApplicationUpdate.js
Labels: bug-fix, frontend

#522 Update README logo
  README.md
Labels: documentation

#523 Add all supportable aws regions to cloud shell
  www/src/components/shell/onboarding/cloud/aws.js
Labels: enhancement, frontend

#524 Implement demo project transfer
  Makefile
  apps/core/lib/core/services/shell/demo.ex
  apps/core/test/services/shell/demo_test.exs
  apps/graphql/lib/graphql/resolvers/shell.ex
  apps/graphql/lib/graphql/schema/shell.ex
  apps/graphql/test/mutations/shell_mutations_test.exs
  apps/worker/mix.exs
Labels: enhancement, backend

#526 fix azure provider versions
  apps/core/priv/scaffolds/terraform/providers/0.1.1/azure.eex
  apps/core/priv/scaffolds/terraform/providers/0.1.2/azure.eex
Labels: enhancement

#527 bump plural version and increase www replica count
  plural/helm/plural/Chart.yaml
  plural/helm/plural/templates/deployment.yaml
  plural/helm/plural/values.yaml
Labels: enhancement

#525 Use new modals
  www/package.json
  www/src/components/account/Actions.js
  www/src/components/account/Confirm.tsx
  www/src/components/account/CreateGroup.js
  www/src/components/account/CreateRole.js
  www/src/components/account/CreateServiceAccount.js
  www/src/components/account/Domains.js
  www/src/components/account/EditGroup.js
  www/src/components/account/EditRole.js
  www/src/components/account/Groups.js
  www/src/components/account/InviteUser.js
  www/src/components/profile/AccessTokens.js
  www/src/components/publisher/CreatePublisherModal.tsx
  www/src/components/repository/InstallationConfiguration.js
  www/src/components/shell/TerminalInformation.js
  www/src/components/shell/TerminalSidebar.js
  www/yarn.lock
Labels: enhancement, design, frontend

#529 Fix cluster upgrades stuck in pending state
  www/src/components/clusters/ClustersContent.tsx
  www/src/components/clusters/ClustersSidenav.tsx
Labels: bug-fix, frontend

#531 New onboarding layout
  www/package.json
  www/src/components/shell/constants.js
  www/src/components/shell/onboarding/OnboardingFooter.js
  www/src/components/shell/onboarding/OnboardingHeader.js
  www/src/components/shell/onboarding/OnboardingSidecar.tsx
  www/src/components/shell/onboarding/OnboardingSidenav.tsx
  www/src/components/shell/onboarding/OnboardingTitle.tsx
  www/src/components/shell/onboarding/OnboardingTitleOnboarding.svg
  www/src/components/shell/onboarding/OnboardingWrapper.js
  www/src/components/shell/onboarding/SplashToLogoTransition.js
  www/yarn.lock
Labels: dependencies, design, frontend

#534 Add trending flag and update erlang version to 23.3
  .tool-versions
  CONTRIBUTING.md
  apps/core/lib/core/schema/repository.ex
  apps/core/priv/repo/migrations/20220915140425_add_trending_flag.exs
  apps/graphql/lib/graphql/schema/repository.ex
Labels: enhancement, backend

#533 Add stacks to the marketplace
  www/package.json
  www/src/components/marketplace/MarketplaceRepositories.js
  www/src/components/marketplace/MarketplaceStacks.tsx
  www/src/components/marketplace/queries.js
  www/src/components/marketplace/utils.tsx
  www/src/models/repo.js
  www/yarn.lock
Labels: enhancement, frontend

#532 Add community attributes to other resources
  apps/core/lib/core/schema/publisher.ex
  apps/core/lib/core/schema/repository.ex
  apps/core/lib/core/schema/stack.ex
  apps/core/priv/repo/migrations/20220914161140_add_community_to_publishers.exs
  apps/graphql/lib/graphql/schema/recipe.ex
  apps/graphql/lib/graphql/schema/repository.ex
  apps/graphql/lib/graphql/schema/user.ex
Labels: enhancement, backend

#536 Fix some icon sizes
  www/src/components/repos/CreateRepository.js
  www/src/components/repos/EditInstallation.js
  www/src/components/repos/Integrations.js
  www/src/components/repos/common/ImageVulnerabilities.js
  www/src/components/shell/onboarding/cloud/gcp.js
  www/src/components/utils/List.tsx
  www/src/components/utils/ReturnToBeginning.js
Labels: bug-fix, frontend

#539 Add trending info to repositories
  www/package.json
  www/src/components/marketplace/MarketplaceRepositories.js
  www/src/models/repo.js
  www/yarn.lock
Labels: enhancement, frontend

#541 Remove one element only if there are duplicates
  www/src/components/account/Typeaheads.js
  www/src/components/repository/OIDCProvider.js
Labels: bug-fix, frontend

#543 [ENG-601] Fix top bar width on cloud shell view
  www/src/components/shell/Terminal.js
Labels: bug-fix, frontend

#537 Add validation for repository names
  apps/api/test/api_web/controllers/auth_controller_test.exs
  apps/core/lib/core/schema/repository.ex
  apps/core/test/services/repositories_test.exs
  apps/graphql/test/mutations/repository_mutation_test.exs
  apps/graphql/test/queries/repository_queries_test.exs
Labels: enhancement, backend

#535 Updated Readme file
  README.md
Labels: documentation, enhancement

#540 Add stack details view
  www/package.json
  www/src/components/Plural.js
  www/src/components/incidents/Responses.js
  www/src/components/marketplace/MarketplaceRepositories.js
  www/src/components/marketplace/MarketplaceStacks.tsx
  www/src/components/marketplace/RepoCardList.tsx
  www/src/components/profile/Profile.js
  www/src/components/repos/EditInstallation.js
  www/src/components/stack/Stack.tsx
  www/src/components/stack/StackApps.tsx
  www/src/components/stack/queries.ts
  www/src/components/stack/types.ts
  www/src/components/utils/SaveButton.tsx
  www/src/models/repo.js
  www/yarn.lock
Labels: enhancement, frontend

#546 Add install panel for stacks
  www/src/components/repository/RepositoryHeader.js
  www/src/components/repository/constants.js
  www/src/components/repository/misc.tsx
  www/src/components/stack/Stack.tsx
  www/src/components/stack/StackApps.tsx
  www/src/components/stack/misc.tsx
  www/src/components/utils/InstallDropdownButton.tsx
  www/src/models/repo.js
Labels: enhancement, frontend

#552 Shrink cluster expiration
  apps/core/lib/core/schema/upgrade_queue.ex
Labels: enhancement

#544 [ENG-595] Position sidecar items properly
  www/src/components/repos/Chart.js
  www/src/components/repos/Docker.js
  www/src/components/repos/Terraform.js
  www/src/components/repository/InstallDropdownButton.js
  www/src/components/repository/misc.tsx
Labels: bug-fix, frontend

#549 Update cheatsheet commands
  www/src/components/shell/TerminalSidebar.js
Labels: enhancement, frontend

#555 Fix merge issues
  www/src/components/repository/misc.tsx
  www/src/components/stack/Stack.tsx
  www/src/components/utils/InstallDropdownButton.tsx
Labels: bug-fix

#545 Onboarding applications selection
  www/package.json
  www/src/components/shell/CloudShell.tsx
  www/src/components/shell/CreateRepositoryCard.js
  www/src/components/shell/OAuthCallback.js
  www/src/components/shell/Shell.js
  www/src/components/shell/Terminal.js
  www/src/components/shell/constants.js
  www/src/components/shell/onboarding/OnboardingCard.js
  www/src/components/shell/onboarding/OnboardingFlow.js
  www/src/components/shell/onboarding/OnboardingSidecar.tsx
  www/src/components/shell/onboarding/OnboardingSidenav.tsx
  www/src/components/shell/onboarding/OnboardingTitle.tsx
  www/src/components/shell/onboarding/OnboardingWrapper.js
  www/src/components/shell/onboarding/applications/ApplicationsSelection.tsx
  www/src/components/shell/onboarding/cloud/CloudBuild.js
  www/src/components/shell/onboarding/cloud/CloudLaunch.js
  www/src/components/shell/onboarding/cloud/demo.js
  www/src/components/shell/queries.js
  www/yarn.lock
Labels: enhancement, design, frontend

#554 Add quckStack api
  .github/workflows/test.yaml
  apps/core/lib/core.ex
  apps/core/lib/core/schema/stack.ex
  apps/core/lib/core/services/recipes.ex
  apps/core/mix.exs
  apps/core/priv/repo/migrations/20220921182340_add_stack_expiry.exs
  apps/core/test/services/recipes_test.exs
  apps/cron/lib/cron/prune/stacks.ex
  apps/cron/test/cron/prune/stacks_test.exs
  apps/graphql/lib/graphql/resolvers/recipe.ex
  apps/graphql/lib/graphql/schema/recipe.ex
  apps/graphql/test/mutations/recipe_mutation_test.exs
  mix.lock
  plural/helm/plural/Chart.yaml
  plural/helm/plural/values.yaml
Labels: enhancement, backend

#557 Add display name for stacks
  apps/core/lib/core/schema/stack.ex
  apps/core/priv/repo/migrations/20220922155143_add_stack_display_name.exs
  apps/graphql/lib/graphql/schema/recipe.ex
Labels: enhancement, backend

#556 Stack design updates
  www/src/components/marketplace/MarketplaceRepositories.js
  www/src/components/marketplace/MarketplaceStacks.tsx
  www/src/components/marketplace/RepoCardList.tsx
  www/src/components/repository/Repository.js
  www/src/components/stack/Stack.tsx
  www/src/components/stack/StackApps.tsx
  www/src/components/stack/misc.tsx
Labels: enhancement, design, frontend

#553 Add Stacks page to Onboarding
  www/src/components/shell/CloudShell.tsx
  www/src/components/shell/CreateRepositoryCard.js
  www/src/components/shell/Shell.js
  www/src/components/shell/Terminal.js
  www/src/components/shell/onboarding/OnboardingSidecar.tsx
  www/src/components/shell/onboarding/OnboardingSidecarApplications.tsx
  www/src/components/shell/onboarding/OnboardingWrapper.js
  www/src/components/shell/onboarding/OnboardingWrapper.tsx
  www/src/components/shell/onboarding/applications/ApplicationsSelection.tsx
  www/src/components/shell/queries.ts
  www/src/contexts/SelectedApplicationsContext.ts
Labels: design, frontend

#560 Add new step to the shell demo
  www/src/components/shell/TerminalSidebar.js
Labels: enhancement, frontend

#561 Stacks enhacements
  www/package.json
  www/src/components/marketplace/MarketplaceStacks.tsx
  www/src/components/profile/Security.js
  www/src/components/stack/Stack.tsx
  www/src/components/stack/StackApps.tsx
  www/src/components/stack/misc.tsx
  www/src/components/stack/queries.ts
  www/src/components/utils/Graph.js
  www/src/components/utils/colors.js
  www/src/models/repo.js
  www/yarn.lock
Labels: enhancement, frontend

#568 Update redirect logic for stack installation
  www/src/components/shell/onboarding/applications/ApplicationsSelection.tsx
  www/src/components/utils/InstallDropdownButton.tsx
Labels: enhancement, frontend

#558 Stack: Change step two of the cloud shell demo
  www/package.json
  www/src/components/layout/Sidebar.js
  www/src/components/shell/CreateRepositoryCard.js
  www/src/components/shell/Shell.js
  www/src/components/shell/TerminalSidebar.js
  www/src/components/shell/constants.js
  www/src/components/shell/onboarding/OnboardingCard.js
  www/src/components/shell/onboarding/OnboardingFlow.js
  www/src/components/shell/onboarding/OnboardingSidecar.tsx
  www/src/components/shell/onboarding/OnboardingSidenav.tsx
  www/src/components/shell/onboarding/OnboardingWrapper.tsx
  www/src/components/shell/onboarding/applications/ApplicationsSelection.tsx
  www/src/components/shell/onboarding/cloud/CloudCredentials.js
  www/src/components/shell/onboarding/cloud/CloudSelect.js
  www/src/components/shell/onboarding/useOnboarded.js
  www/src/components/shell/persistance.ts
  www/src/components/shell/queries.ts
  www/src/components/shell/usePluralCommand.ts
  www/src/components/utils/InstallDropdownButton.tsx
  www/yarn.lock
Labels: design, frontend

#572 Fix console command on other providers
  www/src/components/shell/TerminalSidebar.js
Labels: bug-fix

#559 Swap docker toggle label on change
  www/src/components/repos/Docker.js
Labels: enhancement, frontend

#528 Implement Plural Stacks
  README.md
  www/package.json
  www/src/components/Plural.js
  www/src/components/incidents/Responses.js
  www/src/components/layout/Sidebar.js
  www/src/components/marketplace/MarketplaceRepositories.js
  www/src/components/marketplace/MarketplaceStacks.tsx
  www/src/components/marketplace/RepoCardList.tsx
  www/src/components/marketplace/queries.js
  www/src/components/marketplace/utils.tsx
  www/src/components/profile/Profile.js
  www/src/components/profile/Security.js
  www/src/components/repos/EditInstallation.js
  www/src/components/repository/Repository.js
  www/src/components/repository/RepositoryHeader.js
  www/src/components/repository/constants.js
  www/src/components/repository/misc.tsx
  www/src/components/shell/CloudShell.js
  www/src/components/shell/CloudShell.tsx
  www/src/components/shell/CreateRepositoryCard.js
  www/src/components/shell/OAuthCallback.js
  www/src/components/shell/Shell.js
  www/src/components/shell/Terminal.js
  www/src/components/shell/TerminalSidebar.js
  www/src/components/shell/constants.js
  www/src/components/shell/onboarding/OnboardingCard.js
  www/src/components/shell/onboarding/OnboardingFlow.js
  www/src/components/shell/onboarding/OnboardingFooter.js
  www/src/components/shell/onboarding/OnboardingHeader.js
  www/src/components/shell/onboarding/OnboardingSidecar.tsx
  www/src/components/shell/onboarding/OnboardingSidecarApplications.tsx
  www/src/components/shell/onboarding/OnboardingSidenav.tsx
  www/src/components/shell/onboarding/OnboardingTitle.tsx
  www/src/components/shell/onboarding/OnboardingTitleOnboarding.svg
  www/src/components/shell/onboarding/OnboardingWrapper.js
  www/src/components/shell/onboarding/OnboardingWrapper.tsx
  www/src/components/shell/onboarding/SplashToLogoTransition.js
  www/src/components/shell/onboarding/applications/ApplicationsSelection.tsx
  www/src/components/shell/onboarding/cloud/CloudBuild.js
  www/src/components/shell/onboarding/cloud/CloudCredentials.js
  www/src/components/shell/onboarding/cloud/CloudLaunch.js
  www/src/components/shell/onboarding/cloud/CloudSelect.js
  www/src/components/shell/onboarding/cloud/demo.js
  www/src/components/shell/onboarding/useOnboarded.js
  www/src/components/shell/persistance.ts
  www/src/components/shell/queries.ts
  www/src/components/shell/usePluralCommand.ts
  www/src/components/stack/Stack.tsx
  www/src/components/stack/StackApps.tsx
  www/src/components/stack/misc.tsx
  www/src/components/stack/queries.ts
  www/src/components/stack/types.ts
  www/src/components/utils/Graph.js
  www/src/components/utils/InstallDropdownButton.tsx
  www/src/components/utils/SaveButton.tsx
  www/src/components/utils/colors.js
  www/src/contexts/SelectedApplicationsContext.ts
  www/src/models/repo.js
  www/yarn.lock
Labels: enhancement, design, frontend

#576 Fix onboarding terminal sidebar
  www/package.json
  www/src/components/shell/TerminalSidebar.js
  www/src/components/shell/constants.js
  www/src/components/shell/onboarding/OnboardingFlow.js
  www/src/components/shell/onboarding/useOnboarded.js
  www/src/components/shell/persistance.ts
  www/yarn.lock
Labels: bug-fix, frontend

#579 Onboarding VAQ 2
  www/package.json
  www/src/components/shell/CloudShell.tsx
  www/src/components/shell/TerminalSidebar.js
  www/src/components/shell/onboarding/OnboardingTitle.tsx
  www/src/components/shell/onboarding/OnboardingWrapper.tsx
  www/src/components/shell/onboarding/applications/ApplicationsSelection.tsx
  www/src/components/shell/queries.ts
  www/yarn.lock
Labels: enhancement, design, frontend

#580 ENG-723 - Remove "confirm email" toast during net-new users onboarding.
  www/src/components/layout/Sidebar.js
  www/src/components/shell/onboarding/useOnboarded.js
  www/src/components/users/EmailConfirmation.js
Labels: enhancement, frontend

#582 ENG-732 - Resolve "install plural console" issues with onboarding flow.
  www/src/components/shell/CloudShell.tsx
  www/src/components/shell/onboarding/applications/ApplicationsSelection.tsx
  www/src/components/shell/persistance.ts
Labels: enhancement, bug-fix, frontend

#581 Make copy changes for onboarding sidebar
  www/src/components/shell/Shell.js
  www/src/components/shell/TerminalSidebar.js
  www/src/components/shell/debug-tokens.js
  www/src/components/shell/onboarding/OnboardingSidenav.tsx
  www/src/components/shell/usePluralCommand.ts
Labels: enhancement, frontend

#577 [ENG-714] [ENG-695] [ENG-718] Add padding to the onboarding sidenav and hide publishers filter
  www/src/components/marketplace/MarketplaceSidebar.js
  www/src/components/shell/OAuthCallback.js
  www/src/components/shell/Shell.js
  www/src/components/shell/TerminalSidebar.js
  www/src/components/shell/onboarding/OnboardingWrapper.tsx
  www/src/components/shell/onboarding/cloud/CloudBuild.js
  www/src/components/shell/onboarding/synopsis/Synopsis.js
  www/src/components/shell/usePluralCommand.ts
Labels: bug-fix, frontend

#585 Fix code copy bug
  www/src/components/shell/TerminalSidebar.js
  www/src/components/utils/CodeLine.tsx
Labels: bug-fix, frontend

#583 Fix visual issues with onboarding at narrow VWs
  www/package.json
  www/src/components/shell/onboarding/OnboardingSidenav.tsx
  www/src/components/shell/onboarding/OnboardingWrapper.tsx
  www/yarn.lock
Labels: enhancement, design, frontend
