Repository pluralsh/plural, pull requests merged in 2022-07, with the labels that each got.

#288 Implement Installation Updates
  www/src/components/account/Actions.js
  www/src/components/account/Role.js
  www/src/components/repository/InstallationConfiguration.js
  www/src/components/repository/RepositoryHeader.js
  www/src/components/repository/queries.js
  www/src/components/utils/SidebarTabs.js
Labels: enhancement

#291 Add onboarding state to user records
  apps/core/lib/core/schema/user.ex
  apps/core/priv/repo/migrations/20220701180738_user_onboarding_status.exs
  apps/graphql/lib/graphql/schema/user.ex
Labels: enhancement

#292 Consistently implement container max widths
  www/src/components/account/AccountAttributes.js
  www/src/components/account/Domains.js
  www/src/components/account/Groups.js
  www/src/components/account/Roles.js
  www/src/components/account/ServiceAccounts.js
  www/src/components/account/Users.js
  www/src/components/accounts/Domains.js
  www/src/components/audits/AuditDirectory.js
  www/src/components/audits/LoginAudits.js
  www/src/components/profile/AccessTokens.js
  www/src/components/profile/EabCredentials.js
  www/src/components/profile/Me.js
  www/src/components/profile/PublicKeys.js
  www/src/components/profile/Security.js
  www/src/components/utils/Container.js
Labels: enhancement

#290 Add cloud shell Cheatsheet, complete cloud shell layout
  www/package-lock.json
  www/package.json
  www/src/components/shell/Terminal.js
  www/src/components/shell/TerminalSidebar.js
  www/src/components/shell/TerminalThemeSelector.js
  www/src/components/shell/onboarding/cloud/CloudWorkspace.js
  www/src/components/shell/shell.css
  www/src/hooks/usePrevious.js
Labels: enhancement, dependencies, design

#297 Fix validation on recipes query
  apps/graphql/lib/graphql/middleware/accessible.ex
  apps/graphql/lib/graphql/resolvers/repository.ex
  apps/graphql/test/queries/recipe_queries_test.exs
  apps/graphql/test/queries/repository_queries_test.exs
Labels: bug-fix

#300 fixing up the airbyte command
  www/src/components/shell/TerminalSidebar.js
Labels: good first issue

#304 ENG-248 Fix border margins
  www/src/components/repository/Repository.js
  www/src/components/repository/RepositoryHeader.js
Labels: design

#310 ENG-250 Fix sidebar icons
  www/src/components/layout/Sidebar.js
Labels: design

#313 Fix Update Icon
  www/src/components/layout/WithApplicationUpdate.js
  www/src/components/layout/WithNotifications.js
  www/src/index.js
Labels: bug-fix

#316 ENG-246 ENG-251 ENG-252 ENG-271 Styling fixes and marketplace improvements
  www/package-lock.json
  www/package.json
  www/src/components/layout/Sidebar.js
  www/src/components/layout/WithNotifications.js
  www/src/components/marketplace/MarketplaceRepositories.js
Labels: enhancement, design

#320 Marketplace view fixes
  www/src/components/marketplace/MarketplaceRepositories.js
  www/src/components/marketplace/MarketplaceSidebar.js
Labels: design

#312 Accounts Tab Fixes
  www/package-lock.json
  www/package.json
  www/src/components/account/AccountAttributes.js
  www/src/components/account/Domains.js
  www/src/components/account/Group.js
  www/src/components/account/Groups.js
  www/src/components/account/InviteUser.js
  www/src/components/account/Role.js
  www/src/components/account/Typeaheads.js
  www/src/components/account/User.js
  www/src/components/account/Users.js
  www/src/components/profile/Header.js
  www/src/components/utils/Copyable.js
  www/src/components/utils/Toasts.js
Labels: design

#325 fixed broken links
  www/src/components/shell/onboarding/OnboardingTips.js
Labels: good first issue

#326 Fix audit logs link
  www/src/components/audits/Audits.js
Labels: design

#328 Fix login highlights
  www/src/components/users/MagicLogin.js
Labels: design

#321 Fix dropdown end icon and Lint
  www/src/components/account/InviteUser.js
  www/src/components/layout/Sidebar.js
  www/src/components/profile/AccessTokens.js
  www/src/components/profile/EabCredentials.js
  www/src/components/profile/PublicKeys.js
  www/src/components/repos/Docker.js
  www/src/components/repos/Terraform.js
  www/src/components/repository/InstallDropdownButton.js
  www/src/components/shell/onboarding/OnboardingFlow.js
  www/src/components/shell/onboarding/OnboardingWrapper.js
Labels: design

#331 ENG-270 Adjust repo cards sizes
  www/src/components/marketplace/MarketplaceRepositories.js
Labels: design

#338 Allow confirming uninstall with enter key
  www/src/components/repository/InstallationConfiguration.js
Labels: enhancement

#335 Bump design system version and update package.json
  .github/workflows/www.yaml
  www/.browserslistrc
  www/.dockerignore
  www/.eslintrc.yml
  www/.gitignore
  www/.yarn/releases/yarn-3.2.1.cjs
  www/.yarnrc.yml
  www/Dockerfile
  www/README.md
  www/package-lock.json
  www/package.json
  www/src/components/marketplace/MarketplaceRepositories.js
  www/yarn.lock
Labels: design

#327 Remove a margin in favor of padding
  www/src/components/shell/onboarding/OnboardingWrapper.js
Labels: design

#348 Add new version of oidc request queries
  apps/core/lib/core/services/oauth.ex
  apps/graphql/lib/graphql/resolvers/oauth.ex
  apps/graphql/lib/graphql/schema/oauth.ex
  apps/graphql/test/queries/oauth_queries_test.exs
Labels: enhancement

#350 Adjust repository description styling
  www/src/components/repository/RepositoryDescription.js
  www/src/components/repository/RepositoryDescriptionMarkdown.js
Labels: design

#340 ENG-284 ENG-296 - Onboarding improvements and cheatsheet styling
  www/src/components/layout/Sidebar.js
  www/src/components/shell/Terminal.js
  www/src/components/shell/TerminalSidebar.js
Labels: enhancement

#351 Add licenses to repos
  www/src/components/repository/RepositoryHeader.js
  www/src/components/repository/queries.js
Labels: enhancement

#355 Setup linting for stylesheets
  .github/workflows/www.yaml
  www/.stylelintrc.yaml
  www/package.json
  www/src/components/repository/RepositoryDescription.js
  www/src/components/shell/TerminalSidebar.js
  www/src/components/toolbar.css
  www/yarn.lock
Labels: frontend

#353 Redesign packages tabs
  www/.eslintrc.yml
  www/src/components/repository/RepositoryDescription.js
  www/src/components/repository/RepositoryDescriptionMarkdown.js
  www/src/components/repository/RepositoryPackages.js
  www/src/components/repository/RepositoryPackagesDocker.js
  www/src/components/repository/RepositoryPackagesHelm.js
  www/src/components/repository/RepositoryPackagesTerraform.js
  www/src/models/chart.js
  www/src/models/terraform.js
Labels: design, frontend

#357 Update dependencies
  package-lock.json
  www/package.json
  www/yarn.lock
Labels: dependencies

#360 Fix modal margin of role creation and update
  www/package.json
  www/src/components/account/Role.js
  www/yarn.lock
Labels: dependencies, design

#362 Adjust fonts across the app
  www/README.md
  www/src/components/audits/AuditChloropleth.js
  www/src/components/audits/AuditUser.js
  www/src/components/audits/Audits.js
  www/src/components/profile/Header.js
  www/src/components/utils/ButtonGroup.js
  www/src/components/utils/Table.js
  www/src/theme.js
  www/yarn.lock
Labels: design, frontend

#363 Fix the select in clusters
  www/package.json
  www/src/components/clusters/Clusters.js
  www/yarn.lock
Labels: dependencies, design, bug-fix

#364 Add verified field to repositories
  apps/core/lib/core/schema/repository.ex
  apps/core/priv/repo/migrations/20220716193407_add_verified_flag.exs
  apps/graphql/lib/graphql/schema/repository.ex
Labels: enhancement

#367 Filter null categories
  www/src/components/marketplace/MarketplaceSidebar.js
Labels: bug-fix, frontend

#369 Setup image build checks
  .github/workflows/test.yaml
  .github/workflows/www.yaml
Labels: frontend, backend

#380 Remove node modules cache from CI
  .github/workflows/www.yaml
Labels: frontend

#382 Packages improvements
  www/src/components/repos/Chart.js
  www/src/components/repos/Installation.js
  www/src/components/repos/Terraform.js
  www/src/components/repos/common/PackageSecurity.js
  www/src/components/repos/common/misc.js
Labels: design, frontend

#383 Packages improvements
  www/src/components/repos/common/PackageDependencies.js
  www/src/components/repos/common/PackageSecurity.js
  www/src/components/utils/TreeGraph.js
Labels: design, frontend

#378 Grid layout
  .gitignore
  .vscode/settings.json
  www/package.json
  www/src/components/clusters/ConsoleButton.js
  www/src/components/layout/ApplicationLayout.js
  www/src/components/layout/ResponsiveLayout.tsx
  www/src/components/marketplace/Marketplace.js
  www/src/components/marketplace/MarketplaceRepositories.js
  www/src/components/repository/InstallDropdownButton.js
  www/src/components/repository/Repository.js
  www/src/components/repository/RepositoryDeployments.js
  www/src/components/repository/RepositoryDescription.js
  www/src/components/repository/RepositoryHeader.tsx
  www/src/components/repository/RepositoryPackages.js
  www/src/components/repository/RepositorySideCar.tsx
  www/src/components/repository/RepositorySideNav.tsx
  www/src/components/repository/RepositoryTests.js
  www/src/components/utils/Table.js
  www/src/contexts/RepositoryContext.js
  www/src/contexts/RepositoryContext.ts
  www/yarn.lock
Labels: dependencies, design, frontend

#385 Package improvements
  www/package.json
  www/src/components/repos/Chart.js
  www/src/components/repos/Terraform.js
  www/src/components/repos/common/PackageConfiguration.js
  www/src/components/repos/common/PackageDependencies.js
  www/src/components/repos/common/PackageReadme.js
  www/src/components/repos/common/PackageSecurity.js
  www/src/components/repos/common/PackageUpdateQueue.js
  www/src/components/repos/common/PackageVersionPicker.js
  www/src/components/repos/common/misc.js
  www/src/components/repository/RepositoryEdit.tsx
  www/src/components/repository/RepositoryHeader.js
  www/src/components/repository/RepositoryHeader.tsx
  www/src/components/repository/RepositoryPackagesHelm.js
  www/src/components/repository/RepositorySideCar.tsx
  www/src/components/repository/RepositorySideNav.tsx
  www/src/contexts/RepositoryContext.ts
  www/yarn.lock
Labels: design, frontend

#389 Update deps
  www/package.json
  www/yarn.lock
Labels: dependencies

#392 Packages improvements
  www/src/components/audits/Audits.js
  www/src/components/audits/LoginAudits.js
  www/src/components/repos/Chart.js
  www/src/components/repos/Terraform.js
  www/src/components/repos/common/PackageSecurity.js
  www/src/components/repos/common/PackageUpdateQueue.js
  www/src/components/repos/common/misc.js
  www/src/components/utils/Date.js
Labels: design, frontend

#388 Fix markeplace layout
  www/src/components/layout/ResponsiveLayout.tsx
  www/src/components/marketplace/Marketplace.js
  www/src/components/marketplace/MarketplaceRepositories.js
  www/src/components/repository/Repository.js
  www/src/components/repository/RepositoryDescription.js
  www/src/components/repository/RepositoryHeader.tsx
  www/src/components/repository/RepositoryTests.js
Labels: design

#397 Add service account banner
  www/src/components/layout/ApplicationLayout.js
  www/src/components/layout/Sidebar.js
  www/src/components/login/CurrentUser.js
Labels: enhancement
