Repository pluralsh/plural, pull requests merged in 2022-11, with the labels that each got.

#648 Fix daily action to update GraphQL schema
  .github/workflows/daily.yml
Labels: bug-fix

#647 Begin implementing OpenAI
  apps/core/lib/core/clients/openai.ex
  apps/core/lib/core/services/ai.ex
  apps/graphql/lib/graphql.ex
  apps/graphql/lib/graphql/resolvers/ai.ex
  apps/graphql/lib/graphql/schema/ai.ex
  apps/graphql/test/queries/ai_queries_test.exs
  plural/helm/plural/Chart.yaml
  plural/helm/plural/templates/secret.yaml
  rel/config/config.exs
Labels: enhancement

#650 add dedicated node groups for Plural
  plural/terraform/aws/deps.yaml
  plural/terraform/aws/node-groups.tf
  plural/terraform/aws/terraform.tfvars
  plural/terraform/aws/variables.tf
Labels: enhancement

#654 Clear modal error on close
  www/src/components/account/InviteUser.tsx
Labels: bug-fix

#653 Fix typos
  www/src/components/shell/TerminalSidebar.tsx
  www/src/components/shell/onboarding/OnboardingTips.tsx
Labels: bug-fix

#651 Move plural to dedicated nodes
  plural/helm/plural/Chart.yaml
  plural/helm/plural/templates/chartmuseum.yaml
  plural/helm/plural/templates/deployment.yaml
  plural/helm/plural/templates/hydra-postgres.yaml
  plural/helm/plural/templates/postgres.yaml
  plural/helm/plural/templates/registry.yaml
  plural/helm/plural/values.yaml
Labels: enhancement

#652 Add docs upload and queries
  apps/core/lib/core/schema/repository.ex
  apps/core/lib/core/services/repositories.ex
  apps/core/lib/core/services/users.ex
  apps/core/priv/docs.tgz
  apps/core/priv/docs/other.md
  apps/core/priv/docs/test.md
  apps/core/priv/repo/migrations/20221104200647_add_repo_docs.exs
  apps/core/test/services/repositories_test.exs
  apps/graphql/lib/graphql/resolvers/repository.ex
  apps/graphql/lib/graphql/schema/misc.ex
  apps/graphql/lib/graphql/schema/repository.ex
  apps/graphql/test/queries/repository_queries_test.exs
Labels: enhancement

#646 Backpressured docker image scanning
  apps/core/lib/core/schema/docker_image.ex
  apps/core/lib/core/services/repositories.ex
  apps/worker/lib/worker/application.ex
  apps/worker/lib/worker/docker/pipeline.ex
  apps/worker/lib/worker/docker/producer.ex
  apps/worker/test/docker/pipeline_test.exs
  apps/worker/test/test_helper.exs
  config/config.exs
  config/prod.exs
  plural/helm/plural/Chart.yaml
  plural/helm/plural/values.yaml
Labels: enhancement, backend

#649 migrate fragments from models/*.ts to *.graphql
  www/src/generated/graphql.ts
  www/src/graph/account.graphql
  www/src/graph/artifacts.graphql
  www/src/graph/charts.graphql
  www/src/graph/dns.graphql
  www/src/graph/docker.graphql
  www/src/graph/domains.graphql
  www/src/graph/incidents.graphql
  www/src/graph/installations.graphql
  www/src/graph/integrations.graphql
  www/src/graph/metrics.graphql
  www/src/graph/misc.graphql
  www/src/graph/models.graphql
  www/src/graph/oauth.graphql
  www/src/graph/payments.graphql
  www/src/graph/recipes.graphql
  www/src/graph/repos.graphql
  www/src/graph/scaffolds.graphql
  www/src/graph/shells.graphql
  www/src/graph/terraforms.graphql
  www/src/graph/tests.graphql
  www/src/graph/upgrades.graphql
  www/src/graph/users.graphql
  www/src/graph/versions.graphql
Labels: enhancement

#678 Add scan_completed_at for better docker scan bookkeeping
  apps/core/lib/core/schema/docker_image.ex
  apps/core/lib/core/services/repositories.ex
  apps/core/priv/repo/migrations/20221108013800_add_scan_completed_at.exs
  apps/core/test/services/repositories_test.exs
  apps/cron/test/cron/task/docker_test.exs
  apps/graphql/lib/graphql/schema/docker.ex
  apps/worker/lib/worker/conduit/broker.ex
  apps/worker/test/conduit/subscribers/docker_test.exs
  apps/worker/test/docker/pipeline_test.exs
Labels: bug-fix

#681 remove unused assets generated by phoenix
  apps/rtc/assets/.babelrc
  apps/rtc/assets/css/app.scss
  apps/rtc/assets/css/phoenix.css
  apps/rtc/assets/js/app.js
  apps/rtc/assets/js/socket.js
  apps/rtc/assets/package.json
  apps/rtc/assets/static/favicon.ico
  apps/rtc/assets/static/images/phoenix.png
  apps/rtc/assets/static/robots.txt
  apps/rtc/assets/webpack.config.js
Labels: dependencies

#682 [ENG-939] - Fix repository and shell step UI
  www/src/components/shell/CreateRepositoryCard.tsx
  www/src/components/shell/onboarding/cloud/CloudSelect.tsx
  www/src/components/shell/onboarding/cloud/provider.tsx
Labels: bug-fix, frontend

#680 Hide cloud shell for kind
  www/src/components/utils/InstallDropdownButton.tsx
Labels: bug-fix

#683 [ENG-940] - Refresh user on onboarding status update
  www/src/components/Explore.tsx
  www/src/components/Plural.tsx
  www/src/components/account/AccountAttributes.tsx
  www/src/components/account/AccountSidenav.tsx
  www/src/components/account/Groups.tsx
  www/src/components/account/Roles.tsx
  www/src/components/account/User.tsx
  www/src/components/incidents/Incident.tsx
  www/src/components/incidents/IncidentStatus.tsx
  www/src/components/incidents/MessageControls.tsx
  www/src/components/incidents/MessageInput.tsx
  www/src/components/incidents/MessageReactions.tsx
  www/src/components/incidents/Severity.tsx
  www/src/components/layout/ApplicationLayout.tsx
  www/src/components/layout/Sidebar.tsx
  www/src/components/login/CurrentUser.tsx
  www/src/components/payments/Plan.tsx
  www/src/components/profile/MyProfile.tsx
  www/src/components/profile/Profile.tsx
  www/src/components/profile/Security.tsx
  www/src/components/shell/ConfigureMyCloudButton.tsx
  www/src/components/shell/onboarding/OnboardingSidenav.tsx
  www/src/components/shell/onboarding/cloud/CloudSelect.tsx
  www/src/components/shell/onboarding/useOnboarded.ts
  www/src/components/users/BillingDetails.tsx
  www/src/components/users/EmailConfirmation.tsx
Labels: bug-fix, frontend

#676 Edit OnboardingCompletionModal (Onboarding feedback)
  www/src/components/shell/OnboardingCompletionModal.tsx
Labels: enhancement, frontend

#684 Cluster refinement
  www/src/components/clusters/ClustersContent.tsx
  www/src/components/clusters/ClustersSidenav.tsx
Labels: enhancement

#679 Add CodeQL action
  .github/workflows/codeql.yml
  www/src/components/publisher/CreatePublisherModal.tsx
Labels: enhancement

#706 move plural workers to their own node group
  plural/helm/plural/Chart.yaml
  plural/helm/plural/templates/deployment.yaml
  plural/helm/plural/values.yaml
  plural/terraform/aws/deps.yaml
  plural/terraform/aws/variables.tf
Labels: enhancement

#707 Move docker scan into GenStage
  apps/core/lib/core/pubsub/protocols/fanout.ex
  apps/core/test/pubsub/fanout/docker_test.exs
  apps/worker/lib/worker/docker/pipeline.ex
  apps/worker/lib/worker/docker/producer.ex
  apps/worker/test/docker/pipeline_test.exs
  apps/worker/test/test_helper.exs
Labels: enhancement, backend

#708 bump plural to new release
  plural/helm/plural/Chart.yaml
  plural/helm/plural/templates/deployment.yaml
  plural/helm/plural/values.yaml
Labels: dependencies

#709 Refactor our polled workers to use a common macro
  apps/core/lib/core/schema/docker_image.ex
  apps/core/lib/core/services/scan.ex
  apps/core/test/services/scan_test.exs
  apps/core/test/test_helper.exs
  apps/graphql/lib/graphql/resolvers/docker.ex
  apps/graphql/lib/graphql/schema/docker.ex
  apps/graphql/test/queries/docker_queries_test.exs
  apps/worker/lib/worker/conduit/subscribers/docker.ex
  apps/worker/lib/worker/conduit/subscribers/scan.ex
  apps/worker/lib/worker/demo_projects/producer.ex
  apps/worker/lib/worker/docker/pipeline.ex
  apps/worker/lib/worker/docker/producer.ex
  apps/worker/lib/worker/poll_producer.ex
  apps/worker/lib/worker/rollouts/producer.ex
  apps/worker/lib/worker/upgrades/pipeline.ex
  apps/worker/lib/worker/upgrades/producer.ex
  apps/worker/test/conduit/subscribers/docker_test.exs
  apps/worker/test/demo_projects/pipeline_test.exs
  apps/worker/test/docker/pipeline_test.exs
  apps/worker/test/rollouts/pipeline_test.exs
  apps/worker/test/test_helper.exs
  apps/worker/test/upgrades/pipeline_test.exs
  config/config.exs
  config/prod.exs
  config/test.exs
  plural/helm/plural/Chart.yaml
  plural/helm/plural/templates/deployment.yaml
  plural/helm/plural/values.yaml
Labels: enhancement, backend

#724 Bump rabbit common/amqp
  .github/workflows/publish.yaml
  .github/workflows/test.yaml
  apps/core/mix.exs
  apps/worker/mix.exs
  config/config.exs
  mix.lock
Labels: enhancement, backend

#726 Add digest to key backups
  apps/core/lib/core/clients/vault.ex
  apps/core/lib/core/schema/key_backup.ex
  apps/core/lib/core/services/charts.ex
  apps/core/lib/core/services/encryption.ex
  apps/core/lib/core/services/shell/demo.ex
  apps/core/priv/repo/migrations/20221112162839_add_backup_digest.exs
  apps/core/test/services/encryption_test.exs
  apps/core/test/support/factory.ex
  apps/graphql/lib/graphql/schema/user.ex
  config/config.exs
  mix.lock
  plural/helm/plural/Chart.yaml
  plural/helm/plural/values.yaml
  rel/config/config.exs
Labels: enhancement, backend

#727 Add scan retries
  apps/core/lib/core/schema/docker_image.ex
  apps/core/lib/core/services/repositories.ex
  apps/core/lib/core/services/scan.ex
  apps/core/priv/repo/migrations/20221114025225_add_scan_retries.exs
  apps/core/test/services/repositories_test.exs
  apps/core/test/services/scan_test.exs
Labels: enhancement, backend

#729 feat: Design System maintenance 2
  www/package.json
  www/src/components/publisher/CreatePublisherModal.tsx
  www/src/components/repository/InstallationConfiguration.tsx
  www/src/components/repository/RepositoryPackages.tsx
  www/yarn.lock
Labels: dependencies, frontend

#730 Add ViteJS as the frontend dev server and build system
  www/.babelrc
  www/.browserslistrc
  www/.env
  www/.eslintrc.cjs
  www/index.html
  www/package.json
  www/src/components/constants.ts
  www/src/components/integrations/constants.ts
  www/src/components/layout/ApplicationLayout.tsx
  www/src/components/repos/constants.ts
  www/src/components/repository/RepositoryPackagesDocker.tsx
  www/src/components/repository/RepositoryPackagesHelm.tsx
  www/src/components/repository/RepositoryPackagesTerraform.tsx
  www/src/components/shell/CreateRepositoryCard.tsx
  www/src/components/shell/OAuthCallback.tsx
  www/src/components/shell/Shell.tsx
  www/src/components/shell/onboarding/OnboardingTitle.tsx
  www/src/components/utils/AnimatedLogo.tsx
  www/src/components/utils/InstallDropdownButton.tsx
  www/src/main.tsx
  www/src/serviceWorkerRegistration.ts
  www/src/setupTests.ts
  www/src/setupTests.tsx
  www/src/vite-env.d.ts
  www/tsconfig.json
  www/tsconfig.node.json
  www/vite.config.ts
  www/waitOnConfig.json
  www/yarn.lock
Labels: enhancement, frontend

#737 feat(frontend): get node version from package.json in CI
  .github/workflows/daily.yml
  .github/workflows/www.yaml
  www/package.json
Labels: enhancement

#420 feat(frontend): run nginx as non-root user + fix prod build
  www/Dockerfile
  www/nginx.conf
  www/src/serviceWorkerRegistration.ts
  www/vite.config.ts
Labels: enhancement

#754 Update major version of dependencies
  www/e2e/package.json
  www/e2e/yarn.lock
  www/package.json
  www/src/App.tsx
  www/src/components/incidents/File.tsx
  www/src/components/incidents/MessageInput.tsx
  www/src/components/repos/Artifacts.tsx
  www/src/components/repos/common/PackageSecurity.tsx
  www/src/components/repository/RepositoryArtifacts.tsx
  www/src/components/shell/OnboardingCompletionModal.tsx
  www/yarn.lock
Labels: dependencies, frontend

#757 Fix service worker registration
  www/package.json
  www/public/service-worker.js
  www/src/components/layout/WithApplicationUpdate.tsx
  www/src/service-worker.ts
  www/src/serviceWorkerRegistration.ts
  www/tsconfig.json
  www/vite.config.ts
  www/yarn.lock
Labels: bug-fix, frontend

#758 fix(backend): update arc_ecto to 0.11.3
  apps/core/mix.exs
  mix.exs
  mix.lock
Labels: dependencies

#764 chore(backend): bump ex_aws_sts and ex_machina
  apps/core/mix.exs
  mix.lock
Labels: dependencies

#765 chore(backend): bump stripity_stripe to 2.17.1
  apps/core/mix.exs
  mix.lock
Labels: dependencies

#716 fix(backend): migrate to new config module
  apps/email/lib/email_web/router.ex
  config/config.exs
  config/dev.exs
  config/prod.exs
  config/test.exs
Labels: bug-fix

#767 Add upstream for reverse proxy
  apps/api/lib/api_web/controllers/chart_museum_controller.ex
Labels: bug-fix

#759 [ENG-975] - Preselect the application when using install button
  www/src/components/shell/onboarding/OnboardingWrapper.tsx
  www/src/components/utils/InstallDropdownButton.tsx
Labels: enhancement, frontend

#771 fix(frontend): Fix create publisher modal
  www/src/components/publisher/CreatePublisherModal.tsx
Labels: bug-fix, frontend

#768 Add secret command to input GitHub/GitLab token on onboarding
  www/package.json
  www/src/App.tsx
  www/src/components/shell/CreateRepositoryCard.tsx
  www/src/components/shell/OAuthCallback.tsx
  www/src/components/shell/debug-tokens.ts
  www/src/components/shell/onboarding/OnboardingFlow.tsx
  www/src/components/shell/onboarding/OnboardingWrapper.tsx
  www/src/components/shell/useDevToken.ts
  www/src/router/component.tsx
  www/yarn.lock
Labels: enhancement, frontend

#782 fix(frontend): Fix confirm email view
  www/src/router/context.ts
Labels: bug-fix, frontend

#783 fix(frontend): Fix same domains display multiple times
  www/src/components/account/Domains.tsx
  www/src/components/shell/onboarding/OnboardingWrapper.tsx
  www/src/utils/graphql.ts
Labels: bug-fix, frontend

#784 fix(deps): Fix regex for autoupdate of plural cli by renovate
  renovate.json
Labels: bug-fix

#789 fix: Update honorable deps
  www/package.json
  www/yarn.lock
Labels: dependencies

#788 Fix xterm-addon-fit
  www/package.json
  www/src/components/shell/Shell.tsx
  www/yarn.lock
Labels: bug-fix, frontend

#791 feat(backend): Add search support to dns domain list API
  apps/core/lib/core/schema/dns_domain.ex
  apps/graphql/lib/graphql/resolvers/dns.ex
  apps/graphql/lib/graphql/schema/dns.ex
  apps/graphql/test/queries/dns_queries_test.exs
Labels: enhancement, backend

#792 feat(frontend): Use repository name in the URL instead of id
  www/src/components/Plural.tsx
  www/src/components/audits/Audits.tsx
  www/src/components/marketplace/MarketplaceRepositories.tsx
  www/src/components/marketplace/RepoCardList.tsx
  www/src/components/publisher/PublisherSideNav.tsx
  www/src/components/repos/Chart.tsx
  www/src/components/repos/Docker.tsx
  www/src/components/repos/Terraform.tsx
  www/src/components/repos/queries.ts
  www/src/components/repository/OIDCProvider.tsx
  www/src/components/repository/Repository.tsx
  www/src/components/repository/RepositoryPackages.tsx
  www/src/components/repository/RepositorySideNav.tsx
  www/src/components/repository/misc.tsx
  www/src/components/repository/queries.ts
Labels: enhancement, frontend

#790 Auto-backup encryption keys in cloud shell
  apps/core/lib/core/clients/openai.ex
  apps/core/lib/core/clients/vault.ex
  apps/core/lib/core/schema/key_backup.ex
  apps/core/lib/core/services/encryption.ex
  apps/core/lib/core/services/shell.ex
  apps/core/test/services/encryption_test.exs
  apps/core/test/services/shell_test.exs
  apps/core/test/test_helper.exs
  apps/graphql/lib/graphql/resolvers/user.ex
  apps/graphql/lib/graphql/schema/user.ex
  apps/graphql/test/mutations/shell_mutations_test.exs
  apps/graphql/test/mutations/user_mutation_test.exs
  apps/graphql/test/queries/ai_queries_test.exs
Labels: enhancement, backend

#778 Add additional promote tags to test objects
  apps/core/lib/core/schema/test.ex
  apps/core/lib/core/services/tests.ex
  apps/core/priv/repo/migrations/20221118204819_add_test_promote_tags.exs
  apps/core/test/services/tests_test.exs
  apps/graphql/lib/graphql/schema/test.ex
  mix.lock
Labels: enhancement, backend

#793 Implement platform plan apis
  apps/core/lib/core/policies/payments.ex
  apps/core/lib/core/schema/account.ex
  apps/core/lib/core/schema/platform_plan.ex
  apps/core/lib/core/schema/platform_subscription.ex
  apps/core/lib/core/services/payments.ex
  apps/core/priv/repo/migrations/20221121181836_add_platform_plans.exs
  apps/core/test/services/payments_test.exs
  apps/core/test/support/factory.ex
  apps/graphql/lib/graphql/resolvers/payments.ex
  apps/graphql/lib/graphql/schema/account.ex
  apps/graphql/lib/graphql/schema/payments.ex
  apps/graphql/test/mutations/payments_mutation_test.exs
  apps/graphql/test/queries/payments_queries_test.exs
Labels: enhancement, backend

#795 Allow recipes to be queried anonymously
  apps/graphql/lib/graphql/middleware/accessible.ex
  apps/graphql/lib/graphql/schema/recipe.ex
  apps/graphql/test/queries/recipe_queries_test.exs
Labels: enhancement, backend

#786 fix(deps): Update regex
  renovate.json
Labels: bug-fix

#794 Add shell setup api
  apps/core/lib/core/schema/cloud_shell.ex
  apps/core/lib/core/schema/shell.ex
  apps/core/lib/core/services/shell.ex
  apps/core/lib/core/services/shell/client.ex
  apps/core/lib/core/services/shell/demo.ex
  apps/core/test/services/shell/demo_test.exs
  apps/core/test/services/shell_test.exs
  apps/graphql/lib/graphql/resolvers/shell.ex
  apps/graphql/lib/graphql/schema/shell.ex
  apps/graphql/test/mutations/shell_mutations_test.exs
  apps/graphql/test/test_helper.exs
Labels: enhancement, backend
