Repository pluralsh/plural, pull requests merged in 2022-10, with the labels that each got.

#588 Allow onboarding local development
  www/src/components/shell/OAuthCallback.js
Labels: bug-fix, frontend

#590 ENG-742 Fix ‘Complete demo’ button at end of CLI onboarding
  www/src/components/shell/onboarding/cli/CliCompletion.js
Labels: bug-fix, frontend

#587 [ENG-725] Detect detached message and trigger shell restart
  www/src/components/shell/Shell.js
Labels: enhancement, frontend

#594 [ENG-721] Add history router to better handle state of redirect
  www/package.json
  www/src/App.js
  www/src/components/Plural.js
  www/src/components/shell/OAuthCallback.js
  www/src/components/users/MagicLogin.js
  www/src/router/browser.ts
  www/src/router/component.tsx
  www/src/router/context.ts
  www/src/router/hook.ts
  www/src/router/index.ts
  www/yarn.lock
Labels: enhancement, frontend

#593 ENG-750 - CLI copy code block is appending incorrect code
  www/src/components/shell/onboarding/cli/CliInstallation.js
Labels: bug-fix, frontend

#591 ENG-741 - Fix inline link style on cloud shell side-panel
  www/src/components/shell/TerminalSidebar.js
Labels: design, bug-fix

#586 Set growthbook attributes
  www/src/components/login/CurrentUser.js
  www/src/helpers/growthbook.js
Labels: enhancement, frontend

#592 ENG-728 - Fix login screen for mobile viewport
  www/src/components/users/MagicLogin.js
Labels: design, bug-fix

#596 bump to release v0.4.6
  plural/helm/plural/Chart.yaml
Labels: dependencies

#597 [ENG-761] - Clear some local storage keys when logging out
  www/src/components/layout/Sidebar.js
  www/src/components/users/PasswordReset.js
  www/src/helpers/client.js
  www/src/helpers/localStorage.ts
  www/src/router/context.ts
Labels: enhancement, frontend

#595 Onboarding flow fixes
  www/src/components/shell/constants.js
  www/src/components/shell/onboarding/OnboardingCard.js
  www/src/components/shell/onboarding/OnboardingSidenav.tsx
  www/src/components/shell/onboarding/applications/ApplicationsSelection.tsx
  www/src/components/shell/onboarding/cli/CliCompletion.js
  www/src/components/shell/persistance.ts
Labels: bug-fix, frontend

#603 Add option to get demo project for the current user
  apps/core/lib/core/services/shell/demo.ex
  apps/graphql/lib/graphql/resolvers/shell.ex
  apps/graphql/lib/graphql/schema/shell.ex
  apps/graphql/test/queries/shell_queries_test.exs
Labels: enhancement, backend

#601 Add gql fields for querying and setting shell configuration
  apps/core/lib/core/services/recipes.ex
  apps/core/lib/core/services/repositories.ex
  apps/core/lib/core/services/shell.ex
  apps/core/lib/core/services/shell/client.ex
  apps/core/lib/core/services/shell/models.ex
  apps/core/lib/core/services/shell/pods.ex
  apps/core/test/services/shell_test.exs
  apps/core/test/test_helper.exs
  apps/graphql/lib/graphql/resolvers/recipe.ex
  apps/graphql/lib/graphql/resolvers/shell.ex
  apps/graphql/lib/graphql/schema/shell.ex
  apps/graphql/test/mutations/shell_mutations_test.exs
  apps/graphql/test/queries/shell_queries_test.exs
Labels: enhancement, backend

#600 ENG-746 - Update cloud shell side panel content
  www/package.json
  www/src/components/shell/TerminalSidebar.js
  www/src/components/utils/CodeLine.tsx
  www/yarn.lock
Labels: enhancement, frontend

#607 Implement azure cloud shell
  apps/core/lib/core/schema/cloud_shell.ex
  apps/core/lib/core/services/shell/demo.ex
  apps/graphql/lib/graphql/schema/shell.ex
Labels: enhancement, backend

#598 Hide sidebar during onboarding
  www/src/components/shell/onboarding/useOnboarded.js
Labels: bug-fix

#616 ENG-800 - Fix GCP credentials upload
  www/src/components/incidents/AttachmentProvider.js
  www/src/components/shell/onboarding/cloud/gcp.tsx
Labels: bug-fix, frontend

#620 Place onboarding buttons inside of cards
  www/src/components/shell/CreateRepositoryCard.js
  www/src/components/shell/onboarding/OnboardingNavSection.js
  www/src/components/shell/onboarding/cli/CliCompletion.js
  www/src/components/shell/onboarding/cli/CliInstallation.js
  www/src/components/shell/onboarding/cloud/CloudBuild.js
  www/src/components/shell/onboarding/cloud/CloudCredentials.js
  www/src/components/shell/onboarding/cloud/CloudSelect.js
  www/src/components/shell/onboarding/cloud/CloudWorkspace.js
  www/src/components/shell/onboarding/scm/ScmInput.js
  www/src/components/shell/onboarding/synopsis/Synopsis.js
Labels: enhancement, design, bug-fix, frontend

#619 [ENG-643] - Add the onboarding checklist data to the user object
  apps/core/lib/core/schema/user.ex
  apps/core/priv/repo/migrations/20221018122933_add_user_onboarding_checklist.exs
  apps/core/test/services/users_test.exs
  apps/graphql/lib/graphql/schema/user.ex
Labels: enhancement, backend

#622 Automate onboarding status updates
  apps/core/lib/core/pubsub/events.ex
  apps/core/lib/core/pubsub/protocols/fanout.ex
  apps/core/lib/core/services/users.ex
  apps/core/test/pubsub/fanout/repositories_test.exs
  apps/core/test/pubsub/fanout/users_test.exs
Labels: enhancement, backend

#623 Update uninstall app modal
  www/src/components/repository/InstallationConfiguration.js
Labels: enhancement, frontend

#618 Update card sizing
  www/src/components/marketplace/utils.tsx
Labels: enhancement, design, frontend

#621 Add feedback to onboarding completion
  www/package.json
  www/src/components/shell/OnboardingCompletionModal.tsx
  www/src/components/shell/TerminalSidebar.js
  www/yarn.lock
Labels: enhancement, design, frontend

#624 Backfill onboarding status and ensure set on user create
  apps/core/lib/core/backfill/users.ex
  apps/core/lib/core/schema/user.ex
  apps/core/lib/core/services/users.ex
  apps/core/priv/repo/seeds/010_onboarding_backfill.exs
  apps/core/test/backfill/users_test.exs
  apps/core/test/services/users_test.exs
Labels: enhancement, backend

#617 Add configure my cloud functionality
  www/package.json
  www/src/components/shell/ConfigureMyCloudButton.js
  www/src/components/shell/Shell.js
  www/src/components/shell/queries.ts
  www/yarn.lock
Labels: enhancement, frontend

#628 Update app title and favicons
  www/public/favicon-16x16.png
  www/public/favicon-32x32.png
  www/public/favicon-96x96.png
  www/public/favicon.ico
  www/public/index.html
Labels: enhancement, frontend

#630 Don't modify onboarding checklist when demo projects are present
  apps/core/lib/core/pubsub/protocols/fanout.ex
  apps/core/test/pubsub/fanout/repositories_test.exs
Labels: enhancement, backend

#627 Show demo option only to the new users
  www/src/components/shell/onboarding/OnboardingSidenav.tsx
  www/src/components/shell/onboarding/cloud/CloudSelect.js
  www/src/components/shell/onboarding/cloud/provider.tsx
Labels: enhancement, frontend

#629 Add console to selected apps when using stacks
  www/src/components/shell/onboarding/OnboardingSidecarApplications.tsx
  www/src/components/shell/onboarding/applications/ApplicationsSelection.tsx
Labels: bug-fix, frontend

#542 [ENG-303] Improve error message for provider query
  apps/core/lib/core/schema/provider_scaffold.ex
  apps/core/test/services/scaffolds_test.exs
  apps/graphql/lib/graphql/resolvers/scaffolds.ex
  apps/graphql/test/queries/scaffolds_queries_test.exs
Labels: enhancement, backend

#625 [ENG-644] [ENG-645] - Add onboarding checklist
  www/package.json
  www/src/App.js
  www/src/components/Plural.js
  www/src/components/audits/Audits.js
  www/src/components/layout/WithNotifications.tsx
  www/src/components/shell/constants.tsx
  www/src/components/shell/onboarding/checklist/Checklist.tsx
  www/src/components/shell/onboarding/checklist/Complete.tsx
  www/src/components/shell/onboarding/checklist/Footer.tsx
  www/src/components/shell/persistance.ts
  www/src/components/users/queries.js
  www/src/contexts/OnboardingChecklistContext.ts
  www/src/generated/graphql.tsx
  www/src/helpers/localStorage.ts
  www/src/models/user.js
  www/yarn.lock
Labels: enhancement, frontend

#632 Update e2e test
  www/e2e/cypress.config.ts
  www/e2e/cypress/pages/login.ts
  www/e2e/cypress/pages/marketplace.ts
Labels: bug-fix

#633 release latest version of Plural
  plural/helm/plural/Chart.yaml
Labels: dependencies

#631 [ENG-729] - Fix redirect url add/delete option
  www/src/components/repository/OIDCProvider.js
Labels: bug-fix, frontend

#637 Default CLI installation tab to mac
  www/src/components/shell/onboarding/cli/CliInstallation.js
Labels: enhancement, frontend

#634 [ENG-798] - Add daily action to update GraphQL TS schema
  .github/workflows/daily.yml
Labels: enhancement

#641 Fix null pointer errors
  www/src/components/shell/onboarding/OnboardingSidecarApplications.tsx
Labels: bug-fix, frontend

#639 Update configure my cloud interface
  www/src/components/shell/ConfigureMyCloudButton.js
  www/src/components/shell/onboarding/checklist/Checklist.tsx
Labels: enhancement, design, frontend

#642 [ENG-938] - Fix issues with domain list/detail view and add option to filter domains
  www/src/components/account/DnsRecords.js
  www/src/components/account/Domains.js
  www/src/components/utils/IconButtons.tsx
  www/src/components/utils/List.tsx
Labels: bug-fix, frontend

#644 [ENG-951] - Fix repository test view
  www/src/components/repository/RepositoryTests.js
Labels: bug-fix, frontend

#638 ENG-895 - Fix colors, padding and logo for email notifications
  apps/email/lib/email_web/templates/layout/email.html.eex
  www/public/plural-email-header@2x.png
Labels: design, bug-fix
