Repository pluralsh/plural, pull requests merged in 2022-08, with the labels that each got.

#393 My profile refinement
  www/src/components/Plural.js
  www/src/components/account/AccountAttributes.js
  www/src/components/clusters/Clusters.js
  www/src/components/layout/ResponsiveLayout.tsx
  www/src/components/profile/AccessTokens.js
  www/src/components/profile/EabCredentials.js
  www/src/components/profile/ListItem.js
  www/src/components/profile/Me.js
  www/src/components/profile/MyProfile.js
  www/src/components/profile/Profile.js
  www/src/components/profile/PublicKeys.js
  www/src/components/profile/Security.js
  www/src/components/repository/OIDCProvider.js
  www/src/components/utils/Header.js
  www/src/components/utils/Toasts.js
Labels: design, frontend

#401 Design improvements
  www/package.json
  www/public/ABCMonumentGroteskMono-Heavy.woff
  www/public/ABCMonumentGroteskMono-Medium.woff
  www/public/ABCMonumentGroteskMono-Regular.woff
  www/public/DINAMO EULA.pdf
  www/public/index.html
  www/src/components/profile/AccessTokens.js
  www/src/components/profile/EabCredentials.js
  www/src/components/profile/Profile.js
  www/src/components/profile/PublicKeys.js
  www/src/components/repos/Chart.js
  www/src/components/repos/Terraform.js
  www/src/components/repos/common/misc.js
  www/src/components/repository/RepositoryDescriptionMarkdown.js
  www/src/components/utils/Code.js
  www/src/components/utils/Highlight.js
  www/yarn.lock
Labels: design, frontend

#400 Create community info schema for repositories
  Makefile
  apps/core/lib/core/schema/repository.ex
  apps/core/priv/repo/migrations/20220801132654_add_repository_community.exs
  apps/core/test/services/repositories_test.exs
  apps/graphql/lib/graphql/schema/repository.ex
Labels: backend

#403 Add empty states and other design improvements
  www/src/components/account/Domains.js
  www/src/components/account/Groups.js
  www/src/components/account/Roles.js
  www/src/components/account/ServiceAccounts.js
  www/src/components/audits/AuditChloropleth.js
  www/src/components/audits/AuditDirectory.js
  www/src/components/audits/Audits.js
  www/src/components/audits/LoginAudits.js
  www/src/components/clusters/Clusters.tsx
  www/src/components/marketplace/MarketplaceRepositories.js
  www/src/components/profile/AccessTokens.js
  www/src/components/profile/EabCredentials.js
  www/src/components/profile/MyProfile.js
  www/src/components/profile/PublicKeys.js
  www/src/components/repos/Docker.js
  www/src/components/repos/common/misc.js
  www/src/components/repository/RepositoryDeployments.js
  www/src/components/repository/RepositoryDescription.js
  www/src/components/repository/RepositoryPackages.js
  www/src/components/repository/RepositoryTests.js
  www/src/components/utils/EmptyState.js
  www/src/components/utils/SidebarTabs.js
Labels: design, frontend

#406 Plural Stack Schema and Business Logic
  apps/core/lib/core/policies/recipe.ex
  apps/core/lib/core/schema/stack.ex
  apps/core/lib/core/schema/stack_collection.ex
  apps/core/lib/core/schema/stack_recipe.ex
  apps/core/lib/core/services/recipes.ex
  apps/core/priv/repo/migrations/20220806031446_plural_stacks.exs
  apps/core/test/services/recipes_test.exs
  apps/core/test/support/factory.ex
Labels: enhancement

#410 Fix dns domain validation
  apps/core/lib/core/schema/dns_domain.ex
  apps/core/mix.exs
  apps/core/test/services/dns_test.exs
  apps/cron/lib/cron/task/repo_readme.ex
  mix.lock
Labels: bug-fix, backend

#407 Add plural stacks graphql logic
  apps/core/lib/core/schema/stack.ex
  apps/graphql/lib/graphql/resolvers/recipe.ex
  apps/graphql/lib/graphql/schema/recipe.ex
  apps/graphql/test/mutations/recipe_mutation_test.exs
  apps/graphql/test/queries/recipe_queries_test.exs
Labels: enhancement, backend

#411 Setup Firebase hosting for plural
  .firebaserc
  .github/workflows/firebase-hosting-pull-request.yml
  firebase.json
  www/src/helpers/hostname.js
  www/src/serviceWorker.js
Labels: enhancement, frontend

#416 Add Rate Limits to gql apis
  .github/workflows/test.yaml
  apps/graphql/lib/graphql/middleware/rate_limit.ex
  apps/graphql/lib/graphql/schema/user.ex
  apps/graphql/mix.exs
  config/config.exs
  mix.lock
Labels: bug-fix, backend

#419 Add accessible protocol for gql authz
  apps/core/lib/core/services/accounts.ex
  apps/graphql/lib/graphql/accessible.ex
  apps/graphql/lib/graphql/resolvers/account.ex
  apps/graphql/lib/graphql/resolvers/base.ex
  apps/graphql/test/queries/account_queries_test.exs
Labels: enhancement, backend

#423 prevent simply adding users to dns setup
  apps/core/lib/core/services/dns.ex
  apps/core/test/services/dns_test.exs
Labels: bug-fix, backend

#424 Use code and markdown components
  www/package.json
  www/src/components/repos/common/PackageConfiguration.js
  www/src/components/repos/common/PackageReadme.js
  www/src/components/repository/RepositoryArtifacts.js
  www/src/components/repository/RepositoryDescription.js
  www/src/components/repository/RepositoryDescriptionMarkdown.js
  www/src/components/utils/Code.js
  www/yarn.lock
Labels: dependencies, frontend

#428 Add validation that user/group bindings are w/in account
  apps/core/lib/core/policies/account.ex
  apps/core/lib/core/services/accounts.ex
  apps/core/lib/core/services/dns.ex
  apps/core/test/services/accounts_test.exs
  apps/core/test/services/dns_test.exs
  apps/graphql/test/mutations/account_mutations_test.exs
Labels: bug-fix, backend

#432 Add growthbook test element for demo
  www/package.json
  www/src/components/Plural.js
  www/src/helpers/growthbook.js
  www/yarn.lock
Labels: frontend

#435 Expire stale tests
  apps/core/lib/core/schema/test.ex
  apps/core/lib/core/services/tests.ex
  apps/core/test/services/tests_test.exs
  apps/cron/lib/cron/task/stale_tests.ex
  apps/cron/test/cron/task/stale_tests_test.exs
  plural/helm/plural/Chart.yaml
  plural/helm/plural/values.yaml
Labels: enhancement, backend

#439 Pull metrics improvements
  www/src/components/metrics/Graph.js
  www/src/components/repos/Docker.js
  www/src/components/utils/Graph.js
Labels: design, frontend

#441 Wrap chips in vulnerability details view
  www/src/components/repos/common/ImageVulnerabilities.js
Labels: design, frontend

#443 Merge packages-redesign again
  www/package.json
  www/src/components/account/Account.js
  www/src/components/audits/AuditChloropleth.js
  www/src/components/audits/AuditDirectory.js
  www/src/components/marketplace/MarketplaceRepositories.js
  www/src/components/profile/MyProfile.js
  www/src/components/repository/InstallationConfiguration.js
  www/src/components/repository/Repository.js
  www/src/components/repository/RepositoryPackages.js
  www/src/components/repository/RepositorySideNav.tsx
  www/src/components/utils/Link.js
  www/src/components/utils/Link.tsx
  www/src/components/utils/Tabs.js
  www/yarn.lock
Labels: enhancement, frontend

#438 Autodelete installations when demo projects are created
  apps/core/lib/core/services/shell/demo.ex
  apps/core/lib/core/services/upgrades.ex
  apps/core/test/services/charts_test.exs
  apps/core/test/services/shell/demo_test.exs
Labels: enhancement, backend

#444 Adapt RepositoryCard to screen size
  www/package.json
  www/src/components/marketplace/MarketplaceRepositories.js
  www/src/components/marketplace/MarketplaceSidebar.js
  www/yarn.lock
Labels: dependencies, design, frontend

#448 Bind graph colors
  www/package.json
  www/src/components/metrics/Graph.js
  www/src/components/repos/common/ImagePullMetrics.js
  www/src/components/utils/Graph.js
  www/src/components/utils/colors.js
  www/yarn.lock
Labels: design, frontend

#447 Update private control for Docker images
  www/src/components/repos/Docker.js
  www/src/components/repos/common/ImageVulnerabilities.js
Labels: design, frontend

#452 Fix Marketplace Sidebar focus
  www/package.json
  www/src/components/marketplace/MarketplaceSidebar.js
  www/yarn.lock
Labels: bug-fix, frontend

#455 Close InstallDropdown on outside click
  www/package.json
  www/src/components/repository/InstallDropdownButton.js
  www/yarn.lock
Labels: design, bug-fix

#450 Add destroyCluster api
  apps/core/lib/core/conduit/base.ex
  apps/core/lib/core/services/dns.ex
  apps/core/lib/core/services/users.ex
  apps/core/test/services/users_test.exs
  apps/graphql/lib/graphql/resolvers/user.ex
  apps/graphql/lib/graphql/schema/user.ex
  apps/graphql/test/mutations/user_mutation_test.exs
  apps/graphql/test/test_helper.exs
  apps/worker/lib/worker/conduit/broker.ex
  apps/worker/lib/worker/conduit/subscribers/base.ex
  apps/worker/lib/worker/conduit/subscribers/cluster.ex
  apps/worker/test/conduit/subscribers/cluster_test.exs
  apps/worker/test/test_helper.exs
Labels: enhancement, backend

#458 Update cloud shell
  www/src/components/shell/Terminal.js
  www/src/components/shell/TerminalSidebar.js
Labels: design, frontend

#449 Use select component as theme picker
  www/src/components/shell/TerminalThemeSelector.js
Labels: design, frontend

#456 Fix chip wrapping and update code color theme
  www/package.json
  www/public/index.html
  www/src/components/repos/common/ImageVulnerabilities.js
  www/yarn.lock
Labels: design, frontend

#459 Audits refinement
  www/src/components/utils/Chloropleth.js
Labels: design, frontend

#426 Ensure email confirmation sent on email updates
  apps/core/lib/core/pubsub/protocols/fanout.ex
  apps/core/lib/core/schema/user.ex
  apps/core/test/pubsub/fanout/users_test.exs
  apps/core/test/services/users_test.exs
Labels: enhancement, backend

#464 Display email verification status
  www/src/components/profile/Profile.js
Labels: design, frontend

#465 Fix OICDProvider design
  www/package.json
  www/src/components/oidc/OIDCProvider.js
  www/src/components/repository/OIDCProvider.js
  www/yarn.lock
Labels: design, frontend

#468 Edit Discord link
  README.md
  apps/email/lib/email_web/templates/layout/email.html.eex
  apps/email/lib/email_web/templates/layout/index.html.eex
  www/src/components/layout/Sidebar.js
Labels: enhancement, frontend

#467 Marketplace VQA
  www/package.json
  www/src/components/marketplace/MarketplaceRepositories.js
  www/src/components/marketplace/MarketplaceSidebar.js
  www/yarn.lock
Labels: design, frontend

#473 Add Empty state for marketplace
  www/package.json
  www/src/components/account/Groups.js
  www/src/components/account/Roles.js
  www/src/components/account/ServiceAccounts.js
  www/src/components/clusters/Clusters.tsx
  www/src/components/marketplace/MarketplaceRepositories.js
  www/src/components/profile/AccessTokens.js
  www/src/components/repos/common/ImageVulnerabilities.js
  www/src/components/utils/EmptyState.js
  www/yarn.lock
Labels: dependencies, design, frontend

#474 Display update date if available for Docker images
  www/src/components/repos/Docker.js
  www/src/models/docker.js
Labels: enhancement, frontend

#483 Fix OIDC redirect when logging in with external IDP
  www/src/components/users/MagicLogin.js
Labels: bug-fix

#461 ENG-549 Account Refinements - Account attributes
  www/src/components/Plural.js
  www/src/components/account/Account.js
  www/src/components/account/Account.tsx
  www/src/components/account/AccountAttributes.js
  www/src/components/account/AccountAttributes.tsx
  www/src/components/account/AccountSidenav.tsx
  www/src/components/account/Confirm.js
  www/src/components/account/Confirm.tsx
  www/src/components/account/CreateServiceAccount.js
  www/src/components/account/Domains.js
  www/src/components/account/Group.js
  www/src/components/account/Groups.js
  www/src/components/account/InviteUser.js
  www/src/components/account/List.tsx
  www/src/components/account/MoreMenu.js
  www/src/components/account/Role.js
  www/src/components/account/Roles.js
  www/src/components/account/ServiceAccounts.js
  www/src/components/account/User.js
  www/src/components/account/Users.js
  www/src/components/accounts/queries.js
  www/src/components/profile/AccessTokens.js
  www/src/components/profile/Icon.js
  www/src/components/profile/Icon.tsx
  www/src/components/profile/ListItem.js
  www/src/components/repository/RepositoryEdit.tsx
  www/src/components/utils/Container.js
  www/src/components/utils/SaveButton.tsx
  www/src/hooks/useUpdateState.ts
  www/src/types/styled.d.ts
  www/yarn.lock
Labels: enhancement

#472 Responsive sidecar and tabs layout
  www/src/components/repos/Chart.js
  www/src/components/repos/Docker.js
  www/src/components/repos/Terraform.js
  www/src/components/repos/common/ImagePullMetrics.js
  www/src/components/repos/common/ImageVulnerabilities.js
  www/src/components/repos/common/PackageConfiguration.js
  www/src/components/repos/common/PackageDependencies.js
  www/src/components/repos/common/PackageReadme.js
  www/src/components/repos/common/PackageSecurity.js
  www/src/components/repos/common/PackageUpdateQueue.js
  www/src/components/repos/common/misc.js
  www/src/components/repository/RepositoryDeployments.js
  www/src/components/repository/RepositoryDescription.js
  www/src/components/repository/RepositoryEdit.tsx
  www/src/components/repository/RepositoryPackages.js
  www/src/components/repository/RepositorySideCar.tsx
  www/src/components/repository/RepositoryTests.js
  www/src/components/repository/misc.tsx
  www/src/components/utils/TreeGraph.js
Labels: design, frontend

#487 Redesign invite view
  www/package.json
  www/src/components/Invite.js
  www/src/components/profile/MyProfile.js
  www/src/components/users/MagicLogin.js
  www/src/components/utils/WelcomeHeader.tsx
  www/yarn.lock
Labels: design, frontend

#341 Generate typescript types for our GraphQL API
  www/codegen.yml
  www/package.json
  www/src/generated/graphql.tsx
  www/src/graph/artifacts.graphql
  www/src/graph/charts.graphql
  www/src/graph/dns.graphql
  www/src/graph/domains.graphql
  www/src/graph/installations.graphql
  www/src/graph/models.graphql
  www/src/graph/recipes.graphql
  www/src/graph/repos.graphql
  www/src/graph/scaffolds.graphql
  www/src/graph/shells.graphql
  www/src/graph/terraforms.graphql
  www/src/graph/tests.graphql
  www/src/graph/users.graphql
  www/src/graph/versions.graphql
  www/yarn.lock
Labels: enhancement

#491 Update install in cloud shell command
  www/src/components/repository/InstallDropdownButton.js
Labels: enhancement, frontend

#495 add workflow that checks PR has required labels
  .github/workflows/pr-labels.yaml
Labels: enhancement

#484 Increase invite security
  apps/core/lib/core/pubsub/events.ex
  apps/core/lib/core/pubsub/protocols/auditable/accounts.ex
  apps/core/lib/core/schema/user.ex
  apps/core/lib/core/services/accounts.ex
  apps/core/test/pubsub/audit/accounts_test.exs
  apps/core/test/services/accounts_test.exs
  apps/email/lib/email/builder/invite.ex
  apps/email/lib/email/deliverable/users.ex
  apps/email/lib/email_web/templates/email/invite.html.eex
  apps/email/lib/email_web/templates/email/invite.text.eex
  apps/email/test/email/deliverable/users_test.exs
  apps/graphql/lib/graphql/schema/account.ex
Labels: bug-fix

#496 fix publisher uniq constraint
  apps/core/lib/core/schema/publisher.ex
Labels: bug-fix

#493 ENG-556 - Update marketplace token component
  www/src/components/marketplace/MarketplaceRepositories.js
Labels: bug-fix

#498 ENG-572 - Fix spacing on the repository view
  www/src/components/repos/Chart.js
  www/src/components/repository/Repository.js
  www/src/components/repository/RepositoryDescription.js
Labels: bug-fix, frontend

#499 add script to analyze build size
  www/package.json
  www/yarn.lock
Labels: enhancement

#500 Update modal sizes
  www/package.json
  www/src/components/account/CreateServiceAccount.js
  www/src/components/account/Domains.js
  www/src/components/account/Group.js
  www/src/components/account/Groups.js
  www/src/components/account/Role.js
  www/yarn.lock
Labels: enhancement, design, frontend

#502 Frontend for existing user invites
  apps/core/lib/core/services/accounts.ex
  apps/graphql/lib/graphql/resolvers/account.ex
  apps/graphql/lib/graphql/schema/account.ex
  www/src/components/account/InviteUser.js
  www/src/components/account/Invites.js
  www/src/components/accounts/queries.js
Labels: enhancement, backend
