Repository pluralsh/plural, pull requests merged in 2023-10, with the labels that each got.

#1259 Handle nil value for role repos
  .tool-versions
  CONTRIBUTING.md
  apps/core/lib/core/services/rbac.ex
  apps/rtc/lib/rtc_web/channels/shell_channel.ex
Labels: bug, bug-fix

#1263 Don't show docker installation as an option
  www/src/components/shell/onboarding/sections/cli/CLIInstallationStep.tsx
Labels: bug-fix

#1265 fix: Babel security vulnerability
  www/e2e/yarn.lock
  www/yarn.lock
Labels: bug-fix

#1266 feat: Update to latest design-system
  www/.eslintrc.cjs
  www/package.json
  www/src/components/Invite.tsx
  www/src/components/account/CreateGroup.tsx
  www/src/components/account/CreateServiceAccount.tsx
  www/src/components/account/EditGroup.tsx
  www/src/components/account/Group.tsx
  www/src/components/account/InviteUser.tsx
  www/src/components/account/Role.tsx
  www/src/components/account/RoleForm.tsx
  www/src/components/account/billing/BillingPreview.tsx
  www/src/components/account/invite/InviteUser.tsx
  www/src/components/account/invite/InviteUserButton.tsx
  www/src/components/app/upgrade/Upgrade.tsx
  www/src/components/layout/NotificationsPanelOverlay.tsx
  www/src/components/layout/Overlay.tsx
  www/src/components/layout/Sidebar.tsx
  www/src/components/profile/ListItem.tsx
  www/src/components/repository/RepositoryEdit.tsx
  www/src/components/shell/onboarding/Onboarding.tsx
  www/src/components/shell/onboarding/OnboardingHeader.tsx
  www/src/components/shell/onboarding/OnboardingSidenav.tsx
  www/src/components/shell/terminal/sidebar/installer/Configuration.tsx
  www/src/components/shell/terminal/sidebar/installer/ConfigurationItem.tsx
  www/src/components/users/settings/UserSettings.tsx
  www/src/components/utils/Chloropleth.tsx
  www/src/components/utils/Graph.tsx
  www/src/components/utils/colors.ts
  www/src/components/utils/group/CreateGroup.tsx
  www/src/types/styled.d.ts
  www/vite.config.ts
  www/yarn.lock
Labels: dependencies, frontend
