Repository pluralsh/plural, pull requests merged in 2023-06, with the labels that each got.

#1112 fix: Make Roadmap search inputs maintain full height
  www/src/components/roadmap/RoadmapFeedback.tsx
  www/src/components/roadmap/RoadmapSearchBox.tsx
Labels: bug-fix, frontend

#1115 fix: Repo page broken when no recipes are provided
  www/src/components/utils/InstallAppButton.tsx
  www/src/components/utils/recipeHelpers.tsx
Labels: bug-fix, frontend

#1116 feat: Upgrade front-end dependencies
  www/.yarn/releases/yarn-3.3.0.cjs
  www/.yarn/releases/yarn-3.6.0.cjs
  www/.yarnrc.yml
  www/codegen.yml
  www/package.json
  www/src/components/account/AccountAttributes.tsx
  www/src/components/account/Invites.tsx
  www/src/components/layout/Header.tsx
  www/src/components/layout/Sidebar.tsx
  www/src/components/layout/Subheader.tsx
  www/src/components/layout/WithNotifications.tsx
  www/src/components/marketplace/MarketplaceStacks.tsx
  www/src/components/profile/AccessTokens.tsx
  www/src/components/profile/ListItem.tsx
  www/src/components/repository/RepositoryDeployments.tsx
  www/src/components/shell/onboarding/Onboarding.tsx
  www/src/components/shell/onboarding/OnboardingHeader.tsx
  www/src/components/shell/onboarding/sections/shell/Summary.tsx
  www/src/components/users/Signup.tsx
  www/src/components/utils/Chloropleth.tsx
  www/src/components/utils/Link.tsx
  www/src/components/utils/List.tsx
  www/src/components/utils/ListInput.tsx
  www/src/components/utils/SaveButton.tsx
  www/src/generated/graphql.ts
  www/src/types/styled.d.ts
  www/src/utils/slate.ts
  www/yarn.lock
Labels: dependencies, frontend

#1119 Release v0.10.8
  plural/helm/plural/Chart.yaml
Labels: release

#1121 feat: Remove uninstall from app pages
  www/src/components/app/AppSidenav.tsx
Labels: enhancement, frontend

#1120 feat: Check Origin for signup/login mutations
  apps/api/lib/api_web/plugs/absinthe_context.ex
  apps/api/test/api_web/controllers/gql_controller_test.exs
  apps/api/test/api_web/plugs/absinthe_context_test.exs
  apps/graphql/lib/graphql/middleware/check_origin.ex
  apps/graphql/lib/graphql/schema/user.ex
  apps/graphql/test/mutations/user_mutation_test.exs
  config/config.exs
Labels: enhancement, backend

#1122 release v0.10.10
  plural/helm/plural/Chart.yaml
Labels: release

#1123 feat: server-enforce cluster dependency creation
  apps/core/lib/core/pubsub/protocols/fanout.ex
  apps/core/test/pubsub/fanout/docker_test.exs
  apps/graphql/lib/graphql/schema/cluster.ex
  apps/graphql/test/mutations/cluster_mutations_test.exs
Labels: enhancement, backend

#1127 make `repository` query public
  apps/core/lib/core/policies/repository.ex
  apps/graphql/lib/graphql/resolvers/repository.ex
  apps/graphql/lib/graphql/schema/repository.ex
  apps/graphql/test/queries/repository_queries_test.exs
Labels: enhancement

#1125 Add admin status to oidc id token
  apps/core/lib/core/clients/hydra.ex
  apps/core/test/services/oauth_test.exs
Labels: enhancement

#1129 Add delete user function
  apps/core/lib/core/services/accounts.ex
  apps/core/test/services/accounts_test.exs
Labels: enhancement

#1130 fix: Grammar issue
  www/src/components/shell/onboarding/sections/cloud/ProviderSelection.tsx
Labels: enhancement, frontend

#1128 Release v0.10.12
  plural/helm/plural/Chart.yaml
Labels: release

#1131 release v0.10.13
  plural/helm/plural/Chart.yaml
  plural/helm/plural/values.yaml
Labels: release

#1133 Bump version to v0.10.14
  plural/helm/plural/Chart.yaml
Labels: release

#1134 Add begin trial api
  apps/core/lib/core/schema/account.ex
  apps/core/lib/core/schema/cluster_dependency.ex
  apps/core/lib/core/schema/platform_subscription.ex
  apps/core/lib/core/schema/user.ex
  apps/core/lib/core/services/clusters.ex
  apps/core/lib/core/services/payments.ex
  apps/core/priv/repo/migrations/20230627145817_add_trialed.exs
  apps/core/test/services/payments_test.exs
  apps/core/test/support/factory.ex
  apps/cron/lib/cron/prune/trial.ex
  apps/cron/test/cron/prune/trials_test.exs
  apps/graphql/lib/graphql/resolvers/payments.ex
  apps/graphql/lib/graphql/schema/payments.ex
  apps/graphql/test/mutations/payments_mutation_test.exs
  config/config.exs
  schema/schema.graphql
  www/src/components/shell/terminal/NextSteps.tsx
  www/src/components/shell/terminal/sidebar/installed/helpers.tsx
  www/src/generated/graphql.ts
Labels: enhancement, backend

#1135 release v0.10.15
  plural/helm/plural/Chart.yaml
Labels: release

#1136 Disable destroy for critical apps
  apps/core/lib/core/services/repositories.ex
  apps/core/lib/core/services/tests.ex
  apps/core/lib/core/services/versions.ex
  apps/graphql/lib/graphql/resolvers/version.ex
  apps/graphql/lib/graphql/schema/version.ex
  apps/graphql/test/mutations/version_mutations_test.exs
  schema/schema.graphql
  www/src/components/shell/terminal/sidebar/installed/helpers.tsx
  www/src/generated/graphql.ts
Labels: enhancement, frontend

#1137 release v0.10.16
  plural/helm/plural/Chart.yaml
Labels: release

#1138 feat: Add release controls to app page in cluster view
  www/src/components/app/AppSidecar.tsx
  www/src/components/app/queries.ts
  www/src/components/cluster/queries.ts
  www/src/generated/graphql.ts
  www/src/graph/repos.graphql
Labels: enhancement
