Repository pluralsh/plural, pull requests merged in 2023-01, with the labels that each got.

#832 fix(generic provider): properly template kubernetes provider
  apps/core/priv/scaffolds/terraform/providers/0.1.0/generic.eex
  apps/core/priv/scaffolds/terraform/providers/generic.eex
Labels: bug-fix

#831 Add Feature Differentiation
  apps/core/lib/core/guardian.ex
  apps/core/lib/core/schema/platform_plan.ex
  apps/core/lib/core/services/payments.ex
  apps/core/lib/core/services/rbac.ex
  apps/graphql/lib/graphql/middleware/differentiate.ex
  apps/graphql/lib/graphql/schema/account.ex
  apps/graphql/lib/graphql/schema/base/base.ex
  apps/graphql/test/mutations/account_mutations_test.exs
  config/test.exs
  rel/config/config.exs
Labels: enhancement, backend

#834 fix(ci): require frontend build for release
  .github/workflows/publish.yaml
Labels: bug-fix

#835 fix(frontend): remove ts-expect-error comment
  www/src/components/repos/Artifacts.tsx
Labels: bug-fix

#821 feat: Roadmap
  www/package.json
  www/src/App.tsx
  www/src/components/Plural.tsx
  www/src/components/account/AccountAttributes.tsx
  www/src/components/account/EditGroup.tsx
  www/src/components/account/Group.tsx
  www/src/components/account/RoleForm.tsx
  www/src/components/account/Users.tsx
  www/src/components/audits/AuditChloropleth.tsx
  www/src/components/layout/Sidebar.tsx
  www/src/components/marketplace/MarketplaceSidebar.tsx
  www/src/components/repos/common/PackageConfiguration.tsx
  www/src/components/repository/InstallationConfiguration.tsx
  www/src/components/repository/RepositoryArtifacts.tsx
  www/src/components/repository/RepositorySideCar.tsx
  www/src/components/roadmap/Roadmap.tsx
  www/src/components/roadmap/RoadmapApplicationRequests.tsx
  www/src/components/roadmap/RoadmapChangelog.tsx
  www/src/components/roadmap/RoadmapDataProvider.tsx
  www/src/components/roadmap/RoadmapFeatureRequests.tsx
  www/src/components/roadmap/RoadmapFeedback.tsx
  www/src/components/roadmap/RoadmapIssue.tsx
  www/src/components/roadmap/RoadmapRoadmap.tsx
  www/src/components/roadmap/RoadmapSearchBox.tsx
  www/src/components/roadmap/RoadmapSideCar.tsx
  www/src/components/roadmap/constants.ts
  www/src/components/roadmap/types.ts
  www/src/components/roadmap/useRoadmapData.ts
  www/src/components/shell/onboarding/cli/CliInstallation.tsx
  www/src/components/users/BillingDetails.tsx
  www/src/components/utils/CopyableButton.tsx
  www/src/components/utils/IconButtons.tsx
  www/src/contexts/RoadmapContext.ts
  www/vite.config.ts
  www/yarn.lock
Labels: enhancement, frontend, roadmap

#836 chore(deps): update AWS node group amis to k8s 1.22
  plural/terraform/aws/deps.yaml
  plural/terraform/aws/node-groups.tf
  plural/terraform/aws/shell.tf
  plural/terraform/aws/terraform.tfvars
  plural/terraform/aws/variables.tf
Labels: dependencies

#774 chore(deps): upgrade hydra chart
  plural/helm/plural/Chart.lock
  plural/helm/plural/Chart.yaml
  plural/helm/plural/charts/hydra-0.16.0.tgz
  plural/helm/plural/charts/hydra-0.26.2.tgz
  plural/helm/plural/templates/migration.yaml
  plural/helm/plural/values.yaml
  plural/helm/plural/values.yaml.tpl
Labels: dependencies

#839 fix hydra admin url due to upstream bug
  config/config.exs
Labels: bug-fix

#827 Platform Payments Usage Accounting
  apps/core/lib/core/backfill/accounts.ex
  apps/core/lib/core/pubsub/consumers/usage.ex
  apps/core/lib/core/pubsub/protocols/usage.ex
  apps/core/lib/core/schema/account.ex
  apps/core/lib/core/schema/platform_plan.ex
  apps/core/lib/core/schema/upgrade_queue.ex
  apps/core/lib/core/services/payments.ex
  apps/core/lib/core/services/upgrades.ex
  apps/core/priv/repo/migrations/20221224200002_add_usage.exs
  apps/core/priv/repo/seeds/011_usage.exs
  apps/core/test/backfill/accounts_test.exs
  apps/core/test/pubsub/usage/upgrades_test.exs
  apps/core/test/pubsub/usage/users_test.exs
  apps/core/test/services/payments_test.exs
  apps/core/test/services/upgrades_test.exs
  apps/cron/lib/cron/prune/queues.ex
  apps/cron/lib/cron/task/usage.ex
  apps/cron/test/cron/prune/queues_test.exs
  apps/cron/test/cron/task/usage_test.exs
  config/prod.exs
  plural/helm/plural/templates/cron.yaml
  plural/helm/plural/values.yaml
Labels: enhancement, backend

#833 Stripe webhook implementation
  apps/api/lib/api_web/controllers/webhook_controller.ex
  apps/api/lib/api_web/router.ex
  apps/api/test/api_web/controllers/webhook_controller_test.exs
  apps/core/lib/core/schema/account.ex
  apps/core/lib/core/services/payments.ex
  apps/core/lib/core/stripe/handler.ex
  apps/core/priv/repo/migrations/20230103221258_add_account_delinquency.exs
  apps/core/test/stripe/handler_test.exs
  apps/graphql/lib/graphql/schema/account.ex
  config/config.exs
  plural/helm/plural/Chart.yaml
  plural/helm/plural/templates/secret.yaml
  plural/helm/plural/values.yaml
  rel/config/config.exs
Labels: enhancement, backend

#847 fix: Fix roadmap issue in prod
  www/src/components/account/MoreMenu.tsx
  www/src/components/roadmap/RoadmapIssue.tsx
Labels: bug-fix, frontend

#851 Prevent double-send of accept login
  www/src/components/users/MagicLogin.tsx
Labels: bug-fix, frontend

#848 Implement delinquency enforcement
  apps/core/lib/core/schema/account.ex
  apps/core/lib/core/services/payments.ex
  apps/core/lib/core/services/rollouts/rollable/versions.ex
  apps/core/priv/repo/migrations/20230105230510_add_grandfathered_until.exs
  apps/core/test/services/payments_test.exs
  apps/core/test/services/rollable/versions_test.exs
  apps/core/test/support/test_helpers.ex
  apps/graphql/lib/graphql/schema/account.ex
  apps/graphql/test/mutations/account_mutations_test.exs
Labels: enhancement, backend

#849 Implement subscription delete api
  apps/core/lib/core/services/payments.ex
  apps/core/test/services/payments_test.exs
  apps/graphql/lib/graphql/resolvers/payments.ex
  apps/graphql/lib/graphql/schema/payments.ex
  apps/graphql/test/mutations/payments_mutation_test.exs
Labels: enhancement, backend

#852 Add plan setup functions
  apps/core/lib/core/services/payments.ex
  apps/core/test/services/payments_test.exs
Labels: enhancement, backend

#838 feat: Allow both UUIDs and names for repository URLs
  www/package.json
  www/src/components/repository/Repository.tsx
  www/yarn.lock
Labels: enhancement, frontend

#855 Delete shell on restarts from failed setup
  www/src/components/shell/Terminal.tsx
  www/src/components/shell/queries.ts
Labels: bug-fix, frontend

#853 Add ability to autoprovision service account rbac
  apps/core/lib/core/schema/account.ex
  apps/core/lib/core/schema/platform_plan.ex
  apps/core/lib/core/services/accounts.ex
  apps/core/lib/core/services/payments.ex
  apps/core/priv/repo/migrations/20230109223232_add_role_provisioned_bool.exs
  apps/core/priv/repo/seeds/012_enterprise_plan.exs
  apps/core/test/services/accounts_test.exs
  apps/core/test/services/payments_test.exs
  apps/graphql/lib/graphql/schema/payments.ex
Labels: enhancement, backend

#858 Extend gcp provider scaffold
  apps/core/priv/scaffolds/terraform/providers/gcp.eex
Labels: bug-fix, backend

#860 Feature differentiate audit logs
  apps/core/lib/core/schema/platform_plan.ex
  apps/core/lib/core/services/payments.ex
  apps/core/test/services/payments_test.exs
  apps/core/test/support/factory.ex
  apps/graphql/lib/graphql/schema/audit.ex
  apps/graphql/lib/graphql/schema/user.ex
  apps/graphql/test/mutations/account_mutations_test.exs
  apps/graphql/test/queries/audit_queries_test.exs
  apps/graphql/test/queries/user_queries_test.exs
Labels: enhancement, backend

#861 Add oidc enabled to recipe schema
  apps/graphql/lib/graphql/schema/recipe.ex
Labels: enhancement, backend

#862 feat: Update terminal handling and themes
  www/.gitignore
  www/package.json
  www/src/components/repository/RepositoryTests.tsx
  www/src/components/shell/Shell.tsx
  www/src/components/shell/TerminalThemeProvider.tsx
  www/src/components/shell/themes.tsx
  www/yarn.lock
Labels: enhancement, frontend

#859 Cluster Schema Setup
  apps/core/lib/core/backfill/clusters.ex
  apps/core/lib/core/policies/cluster.ex
  apps/core/lib/core/schema/cluster.ex
  apps/core/lib/core/schema/upgrade_queue.ex
  apps/core/lib/core/schema/user.ex
  apps/core/lib/core/services/clusters.ex
  apps/core/lib/core/services/repositories.ex
  apps/core/lib/core/services/shell.ex
  apps/core/lib/core/services/upgrades.ex
  apps/core/priv/repo/migrations/20230115004239_add_clusters.exs
  apps/core/priv/repo/seeds/013_clusters.exs
  apps/core/test/backfill/clusters_test.exs
  apps/core/test/services/clusters_test.exs
  apps/core/test/services/shell_test.exs
  apps/core/test/services/upgrades_test.exs
  apps/core/test/support/factory.ex
  apps/graphql/lib/graphql.ex
  apps/graphql/lib/graphql/resolvers/cluster.ex
  apps/graphql/lib/graphql/schema/cluster.ex
  apps/graphql/test/mutations/cluster_mutations_test.exs
  apps/graphql/test/queries/cluster_queries_test.exs
Labels: enhancement, backend

#863 feat: Expose update shell mutation
  apps/graphql/lib/graphql/resolvers/shell.ex
  apps/graphql/lib/graphql/schema/shell.ex
  apps/graphql/test/mutations/shell_mutations_test.exs
Labels: enhancement, backend

#865 Expose Usage in gql, ignore service accounts
  apps/core/lib/core/pubsub/protocols/usage.ex
  apps/core/lib/core/schema/account.ex
  apps/core/lib/core/services/shell.ex
  apps/core/test/backfill/accounts_test.exs
  apps/core/test/pubsub/usage/users_test.exs
  apps/core/test/services/shell_test.exs
  apps/graphql/lib/graphql/schema/account.ex
Labels: bug-fix, backend

#868 Don't force destroy aws buckets
  plural/terraform/aws/deps.yaml
  plural/terraform/aws/main.tf
Labels: bug-fix

#869 feat: Expose selected region via shell configuration workspace
  apps/core/lib/core/services/shell/models.ex
  apps/graphql/lib/graphql/schema/shell.ex
  apps/graphql/test/queries/shell_queries_test.exs
Labels: enhancement

#873 fix: trivy use skipdirs instead of scanref
  .github/workflows/www.yaml
Labels: enhancement

#876 Implement dedicated upgrade delivery
  apps/core/lib/core/schema/dependencies.ex
  apps/core/lib/core/schema/upgrade.ex
  apps/core/lib/core/services/rollouts.ex
  apps/core/lib/core/services/rollouts/rollable/versions.ex
  apps/core/test/services/rollable/versions_test.exs
Labels: enhancement, backend

#877 enable s3 encryption + set image bucket to private
  plural/terraform/aws/deps.yaml
  plural/terraform/aws/main.tf
Labels: enhancement

#878 feat: Wire region field through the shell query and revert shell config change
  apps/graphql/lib/graphql/schema/shell.ex
  apps/graphql/test/queries/shell_queries_test.exs
Labels: enhancement, backend

#875 feat: Update App navigation to align with Console navigation
  www/public/app-logo-white.png
  www/src/components/account/Account.tsx
  www/src/components/account/AccountSidenav.tsx
  www/src/components/audits/AuditDirectory.tsx
  www/src/components/clusters/Clusters.tsx
  www/src/components/clusters/ClustersContent.tsx
  www/src/components/clusters/ClustersSidecar.tsx
  www/src/components/clusters/ClustersSidenav.tsx
  www/src/components/layout/ApplicationLayout.tsx
  www/src/components/layout/Header.tsx
  www/src/components/layout/ResponsiveLayout.tsx
  www/src/components/layout/Sidebar.tsx
  www/src/components/layout/Subheader.tsx
  www/src/components/layout/TopBar.tsx
  www/src/components/layout/WithNotifications.tsx
  www/src/components/layout/queries.ts
  www/src/components/marketplace/CardGrid.tsx
  www/src/components/marketplace/Marketplace.tsx
  www/src/components/marketplace/MarketplaceRepositories.tsx
  www/src/components/marketplace/MarketplaceSidebar.tsx
  www/src/components/marketplace/MarketplaceStacks.tsx
  www/src/components/marketplace/RepoCardList.tsx
  www/src/components/profile/MyProfile.tsx
  www/src/components/repos/Chart.tsx
  www/src/components/repos/Docker.tsx
  www/src/components/repos/Terraform.tsx
  www/src/components/repos/UnderTopBar.tsx
  www/src/components/repos/common/ImagePullMetrics.tsx
  www/src/components/repos/common/ImageVulnerabilities.tsx
  www/src/components/repos/common/PackageConfiguration.tsx
  www/src/components/repos/common/PackageUpdateQueue.tsx
  www/src/components/repository/Repository.tsx
  www/src/components/repository/RepositoryDeployments.tsx
  www/src/components/repository/RepositoryDescription.tsx
  www/src/components/repository/RepositoryEdit.tsx
  www/src/components/repository/RepositoryPackages.tsx
  www/src/components/repository/RepositorySideNav.tsx
  www/src/components/repository/RepositoryTests.tsx
  www/src/components/roadmap/Roadmap.tsx
  www/src/components/roadmap/RoadmapApplicationRequests.tsx
  www/src/components/roadmap/RoadmapChangelog.tsx
  www/src/components/roadmap/RoadmapFeatureRequests.tsx
  www/src/components/roadmap/RoadmapFeedback.tsx
  www/src/components/roadmap/RoadmapRoadmap.tsx
  www/src/components/roadmap/RoadmapSearchBox.tsx
  www/src/components/shell/onboarding/OnboardingTitle.tsx
  www/src/components/shell/onboarding/OnboardingWrapper.tsx
  www/src/components/stack/Stack.tsx
  www/src/components/stack/StackApps.tsx
  www/src/components/utils/layout/CardGrid.tsx
  www/src/components/utils/layout/ResponsiveLayoutContentContainer.tsx
  www/src/components/utils/layout/ResponsiveLayoutPage.tsx
  www/src/components/utils/layout/ResponsiveLayoutSidecarContainer.tsx
  www/src/components/utils/layout/ResponsiveLayoutSidenavContainer.tsx
  www/src/components/utils/layout/ResponsiveLayoutSpacer.tsx
  www/src/components/utils/layout/ScrollablePage.tsx
  www/src/components/utils/layout/SideNavOffset.tsx
Labels: enhancement, design, frontend

#881 Fix Locked Installation emails
  apps/email/lib/email/builder/locked_installation.ex
  apps/email/lib/email_web/templates/email/locked_installation.html.eex
  apps/email/lib/email_web/templates/email/locked_installation.text.eex
  apps/email/test/email/builder/locked_installation_test.exs
Labels: bug-fix

#880 fix: Nav button sizing
  www/src/components/layout/Subheader.tsx
Labels: design, bug-fix

#879 fix: Active menu item detection in Sidebar
  www/src/components/layout/Sidebar.tsx
Labels: bug-fix

#882 Bypass caching on payments methods
  apps/core/lib/core/services/payments.ex
Labels: bug-fix, backend

#883 bump vsn
  plural/helm/plural/Chart.yaml
Labels: enhancement, hotfix

#884 Allow creators to always create domain records
  apps/core/lib/core/policies/dns.ex
  apps/core/test/services/dns_test.exs
Labels: enhancement, backend

#885 Add yearly pro plan variants
  apps/core/lib/core/services/payments.ex
  apps/core/test/services/payments_test.exs
  apps/graphql/lib/graphql/resolvers/payments.ex
  apps/graphql/lib/graphql/schema/payments.ex
  apps/graphql/test/mutations/payments_mutation_test.exs
Labels: enhancement, backend
