Repository pluralsh/plural, pull requests merged in 2023-04, with the labels that each got.

#1041 Fix key backup delete
  apps/core/lib/core/clients/vault.ex
  apps/core/test/services/encryption_test.exs
Labels: bug-fix

#1045 Add release status to repo cards
  www/package.json
  www/src/components/marketplace/RepoCardList.tsx
  www/src/models/repo.ts
  www/yarn.lock
Labels: enhancement

#1046 release v0.9.55
  plural/helm/plural/Chart.yaml
Labels: release

#1047 release v0.9.56
  plural/helm/plural/Chart.yaml
Labels: release

#1044 Config upgrade
  apps/core/lib/core/schema/upgrade.ex
  apps/core/lib/core/services/upgrades.ex
  apps/core/priv/repo/migrations/20230403153851_add_upgrade_config.exs
  apps/graphql/lib/graphql/resolvers/upgrade.ex
  apps/graphql/lib/graphql/schema/upgrade.ex
  apps/graphql/test/mutations/upgrade_mutations_test.exs
  schema/schema.graphql
  www/src/generated/graphql.ts
Labels: enhancement

#1049 Downgrade cli to avoid recent push bug
  Dockerfile
Labels: bug-fix

#1048 Upgrade channel sideload
  apps/core/lib/core/schema/cluster.ex
  apps/core/lib/core/schema/version_tag.ex
  apps/core/lib/core/services/repositories.ex
  apps/core/test/services/repositories_test.exs
  apps/cron/lib/cron/prune/queues.ex
  apps/cron/test/cron/prune/queues_test.exs
  apps/graphql/lib/graphql/resolvers/repository.ex
  apps/graphql/lib/graphql/schema/repository.ex
  apps/graphql/test/queries/repository_queries_test.exs
  schema/schema.graphql
  www/src/generated/graphql.ts
Labels: enhancement

#1050 Release v0.9.57
  plural/helm/plural/Chart.yaml
Labels: enhancement, backend

#1051 Use accessible middleware to fetch upgrade repository
  apps/graphql/lib/graphql/resolvers/upgrade.ex
  apps/graphql/lib/graphql/schema/upgrade.ex
  apps/graphql/test/mutations/upgrade_mutations_test.exs
  schema/schema.graphql
  www/src/generated/graphql.ts
Labels: enhancement, backend

#1052 release v0.9.58-rc2
  plural/helm/plural/Chart.yaml
Labels: hotfix, release

#1054 Add repository contributors
  apps/core/lib/core/policies/repository.ex
  apps/core/lib/core/schema/contributor.ex
  apps/core/lib/core/schema/repository.ex
  apps/core/lib/core/schema/user.ex
  apps/core/lib/core/services/repositories.ex
  apps/core/lib/core/services/users.ex
  apps/core/priv/repo/migrations/20230407023221_add_contributors.exs
  apps/core/test/services/repositories_test.exs
  apps/core/test/support/factory.ex
  apps/graphql/lib/graphql/resolvers/repository.ex
  apps/graphql/lib/graphql/schema/repository.ex
  apps/graphql/test/mutations/repository_mutation_test.exs
  apps/graphql/test/queries/repository_queries_test.exs
Labels: enhancement, backend

#1053 Update billing cards to add cost optimization + change plan to "Custom"
  www/src/components/account/billing/BillingPricingCards.tsx
  www/src/components/account/billing/BillingPricingTable.tsx
  www/src/components/account/billing/BillingSubscriptionChip.tsx
Labels: documentation, enhancement

#1055 release v0.9.58
  plural/helm/plural/Chart.yaml
Labels: release

#1059 fix: Data syncing issue with virtualized lists
  www/src/components/account/DnsRecords.tsx
  www/src/components/account/Domains.tsx
  www/src/components/account/GroupsList.tsx
  www/src/components/account/Invites.tsx
  www/src/components/account/Roles.tsx
  www/src/components/account/ServiceAccounts.tsx
  www/src/components/account/UsersList.tsx
  www/src/components/profile/AccessTokens.tsx
  www/src/components/profile/PublicKeys.tsx
  www/src/components/repository/packages/helm/PackageUpdateQueue.tsx
  www/src/models/user.ts
Labels: bug-fix

#1058 Sideload cluster dependencies
  apps/core/lib/core/schema/cluster.ex
  apps/graphql/lib/graphql/resolvers/cluster.ex
  apps/graphql/lib/graphql/schema/cluster.ex
  apps/graphql/test/queries/cluster_queries_test.exs
  schema/schema.graphql
  www/src/generated/graphql.ts
Labels: enhancement, backend

#1060 Release v0.9.59
  plural/helm/plural/Chart.yaml
Labels: release

#1061 Implement ownership transfer
  .tool-versions
  CONTRIBUTING.md
  apps/core/lib/core/policies/chart.ex
  apps/core/lib/core/schema/chart_installation.ex
  apps/core/lib/core/schema/terraform_installation.ex
  apps/core/lib/core/services/clusters.ex
  apps/core/lib/core/services/clusters/transfer.ex
  apps/core/test/services/clusters_test.exs
  apps/core/test/support/factory.ex
  apps/graphql/lib/graphql/resolvers/cluster.ex
  apps/graphql/lib/graphql/schema/cluster.ex
  apps/graphql/test/mutations/cluster_mutations_test.exs
  schema/schema.graphql
  www/src/generated/graphql.ts
Labels: enhancement, backend

#1062 Release v0.9.60
  plural/helm/plural/Chart.yaml
Labels: release

#1063 Allow cluster dependencies to be nullable
  apps/graphql/lib/graphql/schema/cluster.ex
  schema/schema.graphql
  www/src/generated/graphql.ts
Labels: bug-fix

#1064 Deploy version v0.9.61
  plural/helm/plural/Chart.yaml
Labels: release

#1066 Fix caching bug for cluster dependencies
  apps/core/lib/core/pubsub/events.ex
  apps/core/lib/core/pubsub/protocols/cacheable.ex
  apps/core/lib/core/services/clusters.ex
  apps/core/test/pubsub/cache/clusters_test.exs
  apps/core/test/services/clusters_test.exs
Labels: enhancement, backend

#1067 release v0.9.62
  plural/helm/plural/Chart.yaml
Labels: release

#1068 Rejigger cluster constraint
  apps/core/lib/core/schema/cluster.ex
  apps/core/lib/core/services/clusters.ex
  apps/core/priv/repo/migrations/20230420210838_fix_cluster_constraints.exs
  apps/core/test/backfill/clusters_test.exs
  apps/core/test/services/upgrades_test.exs
Labels: bug-fix

#1069 Allow admins to impersonate service accounts
  apps/core/lib/core/policies/account.ex
  apps/core/lib/core/schema/cluster.ex
  apps/core/lib/core/services/clusters.ex
  apps/core/test/services/accounts_test.exs
Labels: enhancement

#1070 Release v0.9.63
  plural/helm/plural/Chart.yaml
Labels: release

#1071 feat: Show 'New cluster' option in cluster select box on Cloud Shell page and Install App dialog
  www/src/components/shell/terminal/sidebar/Sidebar.tsx
  www/src/components/utils/ClusterPicker.tsx
  www/src/components/utils/InstallAppButton.tsx
Labels: enhancement, frontend

#1073 fix: Filter non-accessible clusters in cloud shell
  www/src/components/utils/ClusterPicker.tsx
Labels: bug-fix

#1074 Release v0.9.64
  plural/helm/plural/Chart.yaml
Labels: release

#1075 fix: Add missing fields to upgrade info query
  www/src/components/overview/queries.ts
Labels: bug-fix

#1077 release v0.9.65
  plural/helm/plural/Chart.yaml
Labels: release

#1078 feat: App-specific docs
  www/package.json
  www/src/App.tsx
  www/src/components/Plural.tsx
  www/src/components/app/App.tsx
  www/src/components/app/AppSidenav.tsx
  www/src/components/app/docs/AppDocs.tsx
  www/src/components/app/docs/AppDocsContext.tsx
  www/src/components/app/docs/MarkdocContent.tsx
  www/src/components/app/queries.ts
  www/src/components/utils/layout/ScrollablePage.tsx
  www/src/markdoc/mdSchema.ts
  www/src/models/repo.ts
  www/yarn.lock
Labels: enhancement, design, frontend

#1079 Quickstack only choses primary recipes
  apps/core/lib/core/services/recipes.ex
  apps/core/test/services/recipes_test.exs
Labels: bug-fix, backend

#1080 fix: Select only primary recipes in the installer
  www/src/components/shell/terminal/sidebar/installer/Application.tsx
  www/src/models/recipe.ts
Labels: bug-fix

#1082 Auto-propagate versions on tag change
  apps/core/lib/core/pubsub/protocols/fanout.ex
  apps/core/lib/core/schema/installation.ex
  apps/core/lib/core/services/repositories.ex
  apps/core/test/pubsub/fanout/repositories_test.exs
  apps/core/test/services/repositories_test.exs
Labels: enhancement

#1083 fix: Cluster list improvements
  www/package.json
  www/src/components/overview/clusters/ClusterOwner.tsx
  www/src/components/overview/clusters/Upgrades.tsx
  www/src/components/overview/clusters/columns.tsx
  www/src/components/shell/OAuthCallback.tsx
  www/yarn.lock
Labels: bug-fix

#1084 release v0.10.0
  plural/helm/plural/Chart.yaml
Labels: release
