Repository pluralsh/plural, pull requests merged in 2023-07, with the labels that each got.

#1139 Initialize roles+groups on trial start
  apps/core/lib/core/clients/hydra.ex
  apps/core/lib/core/services/accounts.ex
  apps/core/lib/core/services/payments.ex
  apps/core/lib/core/services/versions.ex
  apps/core/test/services/payments_test.exs
  apps/core/test/support/schema_case.ex
Labels: enhancement, backend

#1140 fix: Recipe upsert doesn't trigger stack foreign key
  apps/core/lib/core/schema/recipe_section.ex
  apps/core/lib/core/services/recipes.ex
  apps/core/test/services/recipes_test.exs
Labels: bug-fix

#1142 fix(backend): recipe assoc preload
  apps/core/lib/core/services/recipes.ex
Labels: bug-fix, backend

#1143 release v0.10.19
  plural/helm/plural/Chart.yaml
Labels: release

#1145 release v0.10.20
  plural/helm/plural/Chart.yaml
Labels: release

#1146 feat(ui): add trial plan support
  www/src/components/account/Domains.tsx
  www/src/components/account/Groups.tsx
  www/src/components/account/Role.tsx
  www/src/components/account/Roles.tsx
  www/src/components/account/ServiceAccounts.tsx
  www/src/components/account/billing/BillingPricingCards.tsx
  www/src/components/account/billing/BillingStartTrialModal.tsx
  www/src/components/account/billing/BillingSubscriptionChip.tsx
  www/src/components/account/billing/BillingSubscriptionProvider.tsx
  www/src/components/account/billing/BillingTrialBanner.tsx
  www/src/components/account/billing/BillingTrialMessage.tsx
  www/src/components/account/billing/queries.ts
  www/src/components/layout/Header.tsx
  www/src/components/login/CurrentUser.tsx
  www/src/components/marketplace/MarketplaceRepositories.tsx
  www/src/contexts/SubscriptionContext.ts
  www/src/generated/graphql.ts
  www/src/graph/account.graphql
  www/src/graph/payments.graphql
  www/src/graph/users.graphql
Labels: enhancement, frontend

#1154 Utility to update account customer id manually
  apps/core/lib/core/services/accounts.ex
Labels: enhancement

#1155 Subscription upgrade cache management
  apps/core/lib/core/pubsub/events.ex
  apps/core/lib/core/pubsub/protocols/cacheable.ex
  apps/core/lib/core/services/payments.ex
  apps/core/test/pubsub/cache/accounts_test.exs
  apps/core/test/services/payments_test.exs
  apps/core/test/support/test_helpers.ex
  apps/graphql/test/mutations/payments_mutation_test.exs
Labels: enhancement

#1153 feat: Add multi-cluster management
  www/src/components/account/billing/BillingStartTrialModal.tsx
  www/src/components/account/queries.ts
  www/src/components/cluster/ClusterAdminsModal.tsx
  www/src/components/cluster/ClusterDependencyModal.tsx
  www/src/components/cluster/UpgradeNeededModal.tsx
  www/src/components/overview/CreateClusterAction.tsx
  www/src/components/overview/CreateClusterModal.tsx
  www/src/components/overview/OverviewHeader.tsx
  www/src/components/overview/clusters/ClusterHealth.tsx
  www/src/components/overview/clusters/ClusterList.tsx
  www/src/components/overview/clusters/Clusters.tsx
  www/src/components/overview/clusters/columns.tsx
  www/src/components/overview/clusters/types.ts
  www/src/components/shell/OAuthCallback.tsx
  www/src/components/shell/Shell.tsx
  www/src/components/shell/context/impersonation.tsx
  www/src/components/shell/onboarding/Onboarding.tsx
  www/src/components/shell/onboarding/checklist/Checklist.tsx
  www/src/components/shell/onboarding/context/hooks.ts
  www/src/components/shell/onboarding/context/onboarding.ts
  www/src/components/shell/onboarding/context/types.ts
  www/src/components/shell/onboarding/sections/cli/CLICompletionStep.tsx
  www/src/components/shell/onboarding/sections/cloud/ProviderSelection.tsx
  www/src/components/shell/onboarding/sections/repository/ProviderSelection.tsx
  www/src/components/shell/terminal/actionbar/ActionBar.tsx
  www/src/components/shell/terminal/actionbar/options/DeleteShellModal.tsx
  www/src/components/shell/terminal/sidebar/Sidebar.tsx
  www/src/components/shell/terminal/sidebar/installer/Installer.tsx
  www/src/components/utils/ClusterPicker.tsx
  www/src/components/utils/InstallAppButton.tsx
  www/src/contexts/ClustersContext.tsx
  www/src/models/user.ts
Labels: enhancement, frontend

#1157 Autotrial new accounts
  apps/core/lib/core/schema/platform_plan.ex
  apps/core/lib/core/services/accounts.ex
  apps/core/lib/core/services/payments.ex
  apps/core/test/services/users_test.exs
Labels: enhancement

#1159 Locked and Promotion email digesting
  apps/core/lib/core/pubsub/events.ex
  apps/core/lib/core/pubsub/protocols/fanout.ex
  apps/core/lib/core/pubsub/protocols/notifiable.ex
  apps/core/lib/core/schema/notification.ex
  apps/core/lib/core/services/clusters.ex
  apps/core/lib/core/services/clusters/transfer.ex
  apps/core/lib/core/services/rollouts.ex
  apps/core/lib/core/services/upgrades.ex
  apps/core/test/pubsub/fanout/repositories_test.exs
  apps/core/test/pubsub/notification/repository_test.exs
  apps/core/test/services/clusters_test.exs
  apps/core/test/services/rollouts_test.exs
  apps/core/test/services/upgrades_test.exs
  apps/cron/lib/cron/digest/base.ex
  apps/cron/lib/cron/digest/locked.ex
  apps/cron/lib/cron/digest/pending.ex
  apps/cron/test/cron/digest/locked_test.exs
  apps/cron/test/cron/digest/pending_test.exs
  apps/email/lib/email/builder/digest.ex
  apps/email/lib/email/helper.ex
  apps/email/lib/email_web/templates/email/locked_upgrades.html.eex
  apps/email/lib/email_web/templates/email/locked_upgrades.text.eex
  apps/email/lib/email_web/templates/email/pending_upgrades.html.eex
  apps/email/lib/email_web/templates/email/pending_upgrades.text.eex
  apps/email/lib/email_web/templates/email/repo_panel.html.eex
  apps/email/lib/email_web/templates/shared/image.html.eex
  apps/email/lib/email_web/views/email_view.ex
  config/dev.exs
  rel/config.exs
  schema/schema.graphql
  www/src/generated/graphql.ts
Labels: enhancement

#1160 Auto-read and prune notifications
  apps/core/lib/core/schema/invite.ex
  apps/core/lib/core/schema/notification.ex
  apps/core/lib/core/schema/user.ex
  apps/core/lib/core/services/accounts.ex
  apps/core/priv/repo/migrations/20230717151538_invite_admin.exs
  apps/core/test/services/accounts_test.exs
  apps/cron/lib/cron/prune/notifications.ex
  apps/cron/test/cron/prune/invites_test.exs
  apps/cron/test/cron/prune/notifications_test.exs
  apps/email/lib/email_web/templates/email/locked_upgrades.html.eex
  apps/graphql/lib/graphql/schema/account.ex
  plural/helm/plural/Chart.yaml
  plural/helm/plural/values.yaml
  schema/schema.graphql
  www/src/components/layout/Sidebar.tsx
  www/src/generated/graphql.ts
  www/src/graph/users.graphql
Labels: enhancement

#1169 Add support for querying user groups and roles
  apps/core/lib/core/policies/user.ex
  apps/core/lib/core/services/users.ex
  apps/graphql/lib/graphql/resolvers/user.ex
  apps/graphql/lib/graphql/schema/user.ex
  apps/graphql/test/queries/user_queries_test.exs
  schema/schema.graphql
  www/src/generated/graphql.ts
Labels: enhancement

#1171 Support oidc and service account bindings in invites
  .dockerignore
  apps/core/lib/core/schema/invite.ex
  apps/core/lib/core/services/accounts.ex
  apps/core/priv/repo/migrations/20230720191356_invite_oidc.exs
  apps/core/test/services/accounts_test.exs
  apps/graphql/lib/graphql/schema/account.ex
  schema/schema.graphql
  www/src/generated/graphql.ts
Labels: enhancement

#1173 Sideload invites for service accounts/oidc providers
  apps/core/lib/core/schema/oidc_provider.ex
  apps/core/lib/core/schema/user.ex
  apps/graphql/lib/graphql/resolvers/account.ex
  apps/graphql/lib/graphql/schema/repository.ex
  apps/graphql/lib/graphql/schema/user.ex
Labels: enhancement

#1176 Support group member updates in user update
  apps/core/lib/core/services/accounts.ex
  apps/core/lib/core/services/users.ex
  apps/core/test/services/users_test.exs
  apps/graphql/lib/graphql/schema/user.ex
  schema/schema.graphql
  www/src/generated/graphql.ts
Labels: enhancement

#1178 Allow group_ids for updateUser to be a full sync
  apps/core/lib/core/services/users.ex
  apps/core/test/services/users_test.exs
Labels: enhancement

#1162 feat: user management improvements
  www/src/components/Invite.tsx
  www/src/components/account/CreateGroup.tsx
  www/src/components/account/Groups.tsx
  www/src/components/account/InviteUser.tsx
  www/src/components/account/Typeaheads.tsx
  www/src/components/account/User.tsx
  www/src/components/account/Users.tsx
  www/src/components/account/UsersList.tsx
  www/src/components/account/invite/InviteUser.tsx
  www/src/components/account/invite/InviteUserButton.tsx
  www/src/components/account/invite/InviteUserModal.tsx
  www/src/components/account/invite/UserLimitModal.tsx
  www/src/components/account/invite/types.ts
  www/src/components/app/App.tsx
  www/src/components/app/AppSidenav.tsx
  www/src/components/app/oidc/OIDC.tsx
  www/src/components/cluster/Cluster.tsx
  www/src/components/cluster/ClusterAdminsModal.tsx
  www/src/components/cluster/UpgradeNeededModal.tsx
  www/src/components/users/settings/UserSettings.tsx
  www/src/components/users/settings/UserSettingsActions.tsx
  www/src/components/users/settings/UserSettingsModal.tsx
  www/src/components/users/settings/types.ts
  www/src/components/utils/List.tsx
  www/src/components/utils/combobox/GroupBindingsComboBox.tsx
  www/src/components/utils/combobox/helpers.ts
  www/src/components/utils/combobox/types.ts
  www/src/components/utils/group/CreateGroup.tsx
  www/src/components/utils/group/CreateGroupButton.tsx
  www/src/components/utils/group/CreateGroupModal.tsx
  www/src/components/utils/group/types.ts
  www/src/components/utils/user/DeleteUser.tsx
  www/src/components/utils/user/DeleteUserModal.tsx
  www/src/components/utils/user/types.ts
  www/src/contexts/AppContext.tsx
  www/src/contexts/ClustersContext.tsx
  www/src/generated/graphql.ts
  www/src/graph/account.graphql
  www/src/graph/cluster.graphql
  www/src/graph/installations.graphql
  www/src/graph/invite.graphql
  www/src/graph/oauth.graphql
  www/src/graph/repos.graphql
  www/src/graph/users.graphql
Labels: enhancement, frontend
