Repository pluralsh/plural, pull requests merged in 2023-02, with the labels that each got.

#887 feat: Update consent view
  www/src/components/oidc/OAuthConsent.tsx
Labels: enhancement, frontend

#888 Improve robustness of demo deletion
  .tool-versions
  apps/core/lib/core/services/shell/demo.ex
Labels: bug-fix, backend

#890 release 0.9.22
  plural/helm/plural/Chart.yaml
Labels: enhancement, backend, hotfix

#891 Improve robustness of demo deletion (#888)
  apps/core/lib/core/services/shell/demo.ex
Labels: bug-fix, hotfix

#893 feat: Improve loading UI
  www/public/page-load-spinner/page-load-spinner.css
  www/public/page-load-spinner/page-load-spinner.js
  www/src/App.tsx
  www/src/components/Plural.tsx
  www/src/components/login/CurrentUser.tsx
  www/src/components/utils/layout/FullScreenSpinner.tsx
  www/src/theme.ts
Labels: enhancement, frontend

#892 Fix shell img overlay
  plural/helm/plural/Chart.yaml
  plural/helm/plural/values.yaml
Labels: bug-fix, backend

#895 bump to 0.9.23
  plural/helm/plural/Chart.yaml
Labels: enhancement, backend, hotfix

#866 feat(frontend): add posthog integration and cookiebot
  www/index.html
  www/package.json
  www/src/components/Plural.tsx
  www/src/components/users/MagicLogin.tsx
  www/src/components/users/queries.ts
  www/src/helpers/localStorage.ts
  www/src/main.tsx
  www/src/utils/cookiebot.ts
  www/src/utils/posthog.ts
  www/yarn.lock
Labels: enhancement

#897 fix(frontend): fix cypress with cookiebot banner
  www/e2e/cypress/support/index.ts
Labels: bug-fix, frontend

#898 bump version
  plural/helm/plural/Chart.yaml
Labels: dependencies

#900 Deploy v0.9.25
  plural/helm/plural/Chart.yaml
Labels: bug-fix, backend, hotfix

#886 Docker scan script
  apps/api/lib/api_web/controllers/auth_controller.ex
  bin/.gitignore
  bin/list_images.py
  bin/requirements.txt
  bin/webflow_import.py
Labels: backend

#903 Persist bundles installed via shell
  apps/core/lib/core/backfill/accounts.ex
  apps/core/lib/core/services/shell.ex
  apps/core/test/backfill/accounts_test.exs
Labels: enhancement, backend

#904 Deploy command
  www/src/components/shell/terminal/Terminal.tsx
Labels: bug-fix

#902 feat: Allow user to change cookie settings
  www/package.json
  www/src/components/layout/Sidebar.tsx
  www/yarn.lock
Labels: enhancement, frontend

#901 fix: Changes are auto-saving in app.plural.sh
  www/src/components/account/CreateGroup.tsx
  www/src/components/account/EditGroup.tsx
  www/src/components/account/Group.tsx
  www/src/components/account/Groups.tsx
  www/src/components/account/GroupsList.tsx
  www/src/components/account/queries.ts
  www/src/generated/graphql.ts
  www/src/graph/groups.graphql
  www/src/hooks/useUpdateState.ts
  www/src/models/user.ts
Labels: bug-fix

#905 Release v0.9.26
  plural/helm/plural/Chart.yaml
Labels: enhancement, hotfix

#906 Add proper support for querying uninstalled repos
  apps/core/lib/core/schema/repository.ex
  apps/core/lib/core/services/shell.ex
  apps/core/lib/core/services/shell/client.ex
  apps/graphql/lib/graphql/resolvers/repository.ex
  apps/graphql/test/queries/repository_queries_test.exs
  apps/rtc/lib/rtc_web/channels/shell_channel.ex
  apps/rtc/test/rtc_web/channels/shell_channel_test.exs
Labels: enhancement, backend

#907 Bump to v0.9.27
  plural/helm/plural/Chart.yaml
Labels: enhancement, hotfix

#910 Bump release to v0.9.28
  plural/helm/plural/Chart.yaml
Labels: enhancement, hotfix

#911 fix: Redirect to marketplace after skipping onboarding
  www/src/components/shell/onboarding/sections/repository/ProviderSelection.tsx
  www/src/router/context.ts
Labels: bug-fix

#912 Issue error for non customers when listing invoices
  apps/core/lib/core/services/payments.ex
  apps/graphql/lib/graphql/schema/user.ex
  apps/graphql/test/queries/payments_queries_test.exs
Labels: enhancement, backend

#914 release version 0.9.29
  plural/helm/plural/Chart.yaml
Labels: dependencies

#913 feat: Send custom events to posthog on onboarding/installer error
  www/src/components/Plural.tsx
  www/src/components/shell/onboarding/sections/shell/CreateShell.tsx
  www/src/components/shell/terminal/installer/Application.tsx
  www/src/components/shell/terminal/installer/Installer.tsx
  www/src/utils/posthog.ts
Labels: enhancement, frontend

#908 Implement new auth landing pages
  www/package.json
  www/public/login-sidebar.jpg
  www/src/App.tsx
  www/src/components/Invite.tsx
  www/src/components/Login.tsx
  www/src/components/constants.ts
  www/src/components/oidc/OAuthConsent.tsx
  www/src/components/users/EmailConfirmation.tsx
  www/src/components/users/LabelledInput.tsx
  www/src/components/users/LoginFooter.tsx
  www/src/components/users/LoginPortal.tsx
  www/src/components/users/MagicLogin.tsx
  www/src/components/users/PasswordReset.tsx
  www/src/components/users/PasswordValidation.tsx
  www/src/components/users/RequestPasswordReset.tsx
  www/src/components/users/ResetPassword.tsx
  www/src/components/users/Signup.tsx
  www/src/components/utils/HubSpot.tsx
  www/src/components/utils/WelcomeHeader.tsx
  www/src/generated/graphql.ts
  www/src/graph/invite.graphql
  www/src/graph/users.graphql
  www/src/utils/email.test.ts
  www/src/utils/email.ts
  www/yarn.lock
Labels: enhancement, design, frontend

#915 Fix OIDC login with plural
  www/src/components/oidc/OAuthConsent.tsx
Labels: bug-fix, hotfix

#916 bump version
  plural/helm/plural/Chart.yaml
Labels: dependencies, hotfix

#917 feat: Capture more custom events
  www/src/components/oidc/OAuthConsent.tsx
  www/src/components/shell/terminal/installer/Installer.tsx
  www/src/utils/posthog.ts
Labels: enhancement, frontend

#918 Update cloud credentials info message
  www/src/components/shell/onboarding/sections/cloud/CloudStep.tsx
Labels: enhancement

#919 bump plural version
  plural/helm/plural/Chart.yaml
Labels: dependencies

#920 Bump posthog to v1.43.1
  www/package.json
  www/yarn.lock
Labels: bug-fix, frontend

#921 bump plural version
  plural/helm/plural/Chart.yaml
Labels: dependencies

#923 Start sending server-side events to posthog
  apps/core/lib/core/pubsub/consumers/posthog.ex
  apps/core/lib/core/pubsub/protocols/hoggable.ex
  apps/core/mix.exs
  apps/core/test/pubsub/posthog/repositories_test.exs
  apps/core/test/test_helper.exs
  config/config.exs
  config/prod.exs
  mix.lock
Labels: enhancement, backend

#924 Updated callout for cloud credentials and added link to quickstart docs
  www/src/components/shell/onboarding/sections/cloud/CloudStep.tsx
Labels: documentation

#856 feat: Billing
  www/package.json
  www/public/sam_profile_picture.png
  www/src/components/Plural.tsx
  www/src/components/account/AccountSidenav.tsx
  www/src/components/account/CreateGroup.tsx
  www/src/components/account/CreateRole.tsx
  www/src/components/account/CreateServiceAccount.tsx
  www/src/components/account/EditGroup.tsx
  www/src/components/account/Groups.tsx
  www/src/components/account/Roles.tsx
  www/src/components/account/ServiceAccounts.tsx
  www/src/components/account/UsersList.tsx
  www/src/components/account/billing/BillingBankCardProvider.tsx
  www/src/components/account/billing/BillingBankCards.tsx
  www/src/components/account/billing/BillingConsumptionProvider.tsx
  www/src/components/account/billing/BillingDowngradeModal.tsx
  www/src/components/account/billing/BillingError.tsx
  www/src/components/account/billing/BillingFeatureBlockBanner.tsx
  www/src/components/account/billing/BillingInvoices.tsx
  www/src/components/account/billing/BillingLayout.tsx
  www/src/components/account/billing/BillingLegacyUserBanner.tsx
  www/src/components/account/billing/BillingLegacyUserMessage.tsx
  www/src/components/account/billing/BillingLoading.tsx
  www/src/components/account/billing/BillingManagePlan.tsx
  www/src/components/account/billing/BillingMigrationModal.tsx
  www/src/components/account/billing/BillingPayments.tsx
  www/src/components/account/billing/BillingPlatformPlansProvider.tsx
  www/src/components/account/billing/BillingPreview.tsx
  www/src/components/account/billing/BillingPricingCard.tsx
  www/src/components/account/billing/BillingPricingCards.tsx
  www/src/components/account/billing/BillingPricingTable.tsx
  www/src/components/account/billing/BillingSubscriptionChip.tsx
  www/src/components/account/billing/BillingSubscriptionProvider.tsx
  www/src/components/account/billing/BillingUpgradeToProfessionalModal.tsx
  www/src/components/account/billing/queries.ts
  www/src/components/account/billing/useBankCard.tsx
  www/src/components/layout/ApplicationLayout.tsx
  www/src/components/layout/Header.tsx
  www/src/components/login/CurrentUser.tsx
  www/src/contexts/BillingBankCardContext.ts
  www/src/contexts/BillingConsumptionContext.ts
  www/src/contexts/PlatformPlansContext.ts
  www/src/contexts/SubscriptionContext.ts
  www/src/generated/graphql.ts
  www/src/hooks/usePersistedState.tsx
  www/src/models/user.ts
  www/src/utils/string.ts
  www/yarn.lock
Labels: enhancement, frontend

#926 Ensure errors propagate properly
  apps/graphql/lib/graphql/schema/base/helpers.ex
  apps/graphql/test/mutations/payments_mutation_test.exs
Labels: bug-fix, backend, hotfix

#927 Release v0.9.31
  plural/helm/plural/Chart.yaml
Labels: enhancement, backend

#928 Make cookiebot more robust
  www/src/utils/posthog.ts
Labels: bug-fix

#929 feat: Add attributes to various elements for posthog targeting
  www/src/components/layout/Header.tsx
  www/src/components/layout/Sidebar.tsx
  www/src/components/layout/Subheader.tsx
  www/src/components/shell/onboarding/OnboardingHeader.tsx
  www/src/components/shell/onboarding/sections/cloud/CloudStep.tsx
  www/src/components/shell/onboarding/sections/repository/ProviderConfiguration.tsx
  www/src/components/shell/onboarding/sections/repository/ProviderSelection.tsx
  www/src/components/shell/onboarding/sections/shell/CreateShell.tsx
  www/src/components/shell/onboarding/sections/shell/ShellStatus.tsx
  www/src/components/shell/onboarding/sections/shell/Summary.tsx
  www/src/components/shell/onboarding/sections/workspace/WorkspaceStep.tsx
  www/src/components/shell/terminal/Content.tsx
  www/src/components/shell/terminal/NextSteps.tsx
  www/src/components/shell/terminal/actionbar/ActionBar.tsx
  www/src/components/shell/terminal/actionbar/cheatsheet/CheatsheetCommand.tsx
  www/src/components/shell/terminal/actionbar/options/DeleteShellModal.tsx
  www/src/components/shell/terminal/actionbar/options/EditCloudCredentialsModal.tsx
  www/src/components/shell/terminal/actionbar/options/MoreOptions.tsx
  www/src/components/users/MagicLogin.tsx
  www/src/components/users/Signup.tsx
Labels: enhancement

#925 fix: Stack page layout
  www/src/components/stack/Stack.tsx
Labels: bug-fix, frontend

#931 Properly wait until setupShell completes
  www/src/components/shell/Shell.tsx
Labels: bug-fix, frontend

#932 chore(frontend): add missing region on GCP
  www/src/components/shell/onboarding/sections/cloud/provider/GCP.tsx
Labels: bug-fix, frontend

#933 release 0.9.33
  plural/helm/plural/Chart.yaml
Labels: enhancement, hotfix

#934 Bump version
  plural/helm/plural/Chart.yaml
Labels: dependencies, hotfix

#935 Handle incorrect signups in onCompleted
  www/src/components/users/Signup.tsx
Labels: bug-fix, frontend, hotfix

#937 release v0.9.35
  plural/helm/plural/Chart.yaml
Labels: bug-fix, hotfix

#804 chore(backend): add API documentation
  apps/graphql/lib/graphql/schema/cluster.ex
  apps/graphql/lib/graphql/schema/repository.ex
Labels: enhancement

#938 fix: Update announcement modal open logic
  www/src/components/account/billing/BillingMigrationModal.tsx
  www/src/components/account/billing/BillingSubscriptionProvider.tsx
Labels: bug-fix

#939 fix(frontend): have posthog work on login and signup page
  www/src/App.tsx
  www/src/components/users/LoginFooter.tsx
  www/src/components/utils/HubSpot.tsx
  www/src/types/window.d.ts
  www/src/utils/cookiebot.ts
  www/src/utils/posthog.ts
Labels: bug-fix

#940 Release v0.9.36
  plural/helm/plural/Chart.yaml
Labels: dependencies

#894 feat(frontend): use type safe generated me query
  .github/workflows/test.yaml
  Makefile
  apps/graphql/lib/graphql/schema/user.ex
  schema/schema.graphql
  www/codegen.yml
  www/src/components/Explore.tsx
  www/src/components/Plural.tsx
  www/src/components/account/AccountAttributes.tsx
  www/src/components/account/AccountSidenav.tsx
  www/src/components/account/Groups.tsx
  www/src/components/account/Roles.tsx
  www/src/components/account/User.tsx
  www/src/components/account/queries.ts
  www/src/components/account/utils.ts
  www/src/components/incidents/Incident.tsx
  www/src/components/incidents/IncidentStatus.tsx
  www/src/components/incidents/MessageControls.tsx
  www/src/components/incidents/MessageInput.tsx
  www/src/components/incidents/MessageReactions.tsx
  www/src/components/incidents/Severity.tsx
  www/src/components/layout/Sidebar.tsx
  www/src/components/layout/Subheader.tsx
  www/src/components/layout/WithNotifications.tsx
  www/src/components/login/CurrentUser.tsx
  www/src/components/payments/Plan.tsx
  www/src/components/profile/MyProfile.tsx
  www/src/components/profile/Profile.tsx
  www/src/components/profile/Security.tsx
  www/src/components/shell/_old/cloud/CloudSelect.tsx
  www/src/components/shell/hooks/useOnboarded.ts
  www/src/components/shell/onboarding/checklist/Checklist.tsx
  www/src/components/users/BillingDetails.tsx
  www/src/components/users/EditAccount.tsx
  www/src/components/users/EmailConfirmation.tsx
  www/src/components/users/queries.ts
  www/src/contexts/CurrentUserContext.ts
  www/src/contexts/CurrentUserContext.tsx
  www/src/generated/graphql.ts
  www/src/graph/account.graphql
  www/src/graph/users.graphql
  www/src/utils/posthog.ts
  www/src/utils/removeTypename.tsx
  www/src/utils/ts-notNil.ts
Labels: enhancement, frontend

#943 fix: Fix typo
  www/src/components/shell/onboarding/sections/repository/ProviderSelection.tsx
Labels: bug-fix

#944 fix: Update Discord link
  www/src/components/layout/Sidebar.tsx
Labels: bug-fix

#941 fix: Notifications are hiding new app nav bar
  package.json
  www/src/App.tsx
  www/src/components/layout/ApplicationLayout.tsx
  www/src/components/layout/NotificationsPanelOverlay.tsx
  www/src/components/layout/Overlay.tsx
  www/src/components/layout/Sidebar.tsx
  yarn.lock
Labels: enhancement, design

#947 Release 0.9.37
  plural/helm/plural/Chart.yaml
Labels: enhancement

#946 fix: Notifications don’t close when clicking outside panel
  www/src/components/layout/NotificationsPanelOverlay.tsx
  www/src/components/layout/Overlay.tsx
  www/src/hooks/useUnmount.tsx
Labels: bug-fix

#948 Fix typo on billing
  www/src/components/account/billing/BillingPricingCards.tsx
Labels: bug-fix

#951 Release v0.9.38
  plural/helm/plural/Chart.yaml
Labels: enhancement

#945 fix: Use new table component to display audit logs and logins
  www/package.json
  www/src/components/audits/AuditUser.tsx
  www/src/components/audits/Audits.tsx
  www/src/components/audits/LoginAudits.tsx
  www/src/components/utils/ReturnToBeginning.tsx
  www/yarn.lock
Labels: bug-fix

#952 Billing edits
  www/public/placeholder-groups.png
  www/public/placeholder-roles.png
  www/public/placeholder-service-accounts.png
  www/src/components/account/billing/BillingFeatureBlockBanner.tsx
  www/src/components/account/billing/BillingPreview.tsx
Labels: enhancement, frontend

#955 Updated pricing table and cards for terminology
  www/src/components/account/billing/BillingPricingCards.tsx
  www/src/components/account/billing/BillingPricingTable.tsx
Labels: frontend

#956 Bring-your-own-git for cloud shell
  apps/core/lib/core/schema/cloud_shell.ex
  apps/core/lib/core/services/shell.ex
  apps/core/lib/core/services/shell/client.ex
  apps/core/lib/core/services/shell/scm.ex
  apps/core/test/services/shell/client_test.exs
  apps/core/test/services/shell_test.exs
  apps/graphql/lib/graphql/schema/shell.ex
  apps/graphql/test/mutations/shell_mutations_test.exs
Labels: enhancement, backend

#959 Release v0.9.39
  plural/helm/plural/Chart.yaml
Labels: enhancement

#961 Posthog user.created event, and wipe root user id when moving accounts
  Makefile
  apps/core/lib/core/backfill/accounts.ex
  apps/core/lib/core/pubsub/protocols/hoggable.ex
  apps/core/lib/core/schema/account.ex
  apps/core/lib/core/services/accounts.ex
  apps/core/test/backfill/accounts_test.exs
  apps/core/test/pubsub/posthog/users_test.exs
  apps/core/test/services/accounts_test.exs
  schema/schema.graphql
  www/src/generated/graphql.ts
Labels: enhancement, backend

#960 Rightsize resource commitments for plural itself
  plural/helm/plural/Chart.yaml
  plural/helm/plural/values.yaml
  plural/terraform/aws/deps.yaml
  plural/terraform/aws/variables.tf
Labels: enhancement

#962 Configure worker nodes to scale to zero
  plural/terraform/aws/deps.yaml
  plural/terraform/aws/variables.tf
Labels: enhancement, backend, hotfix

#963 Autoconfigure git for demo projects
  Makefile
  apps/core/lib/core/pubsub/events.ex
  apps/core/lib/core/pubsub/protocols/hoggable.ex
  apps/core/lib/core/schema/key_backup.ex
  apps/core/lib/core/services/dns.ex
  apps/core/lib/core/services/shell.ex
  apps/core/lib/core/services/shell/demo.ex
  apps/core/lib/core/services/shell/scm.ex
  apps/core/lib/core/services/users.ex
  apps/core/priv/repo/migrations/20230223134524_remove_backup_constraint.exs
  apps/core/test/services/dns_test.exs
  apps/core/test/services/shell/demo_test.exs
  apps/core/test/services/shell_test.exs
  apps/core/test/support/schema_case.ex
  apps/graphql/lib/graphql/schema/shell.ex
  apps/graphql/lib/graphql/schema/user.ex
  apps/graphql/test/mutations/dns_mutations_test.exs
  apps/worker/test/conduit/subscribers/cluster_test.exs
  config/config.exs
  plural/helm/plural/Chart.yaml
  plural/helm/plural/templates/secret.yaml
  plural/helm/plural/values.yaml
  rel/config/config.exs
Labels: enhancement, backend

#965 Release v0.9.40
  plural/helm/plural/Chart.yaml
Labels: dependencies
