Repository pluralsh/plural, pull requests merged in 2023-08, with the labels that each got.

#1185 Add database_management feature
  apps/core/lib/core/schema/platform_plan.ex
  apps/core/lib/core/services/payments.ex
  apps/core/test/services/payments_test.exs
Labels: enhancement

#1187 Forcibly recompute usage before syncing
  apps/cron/lib/cron/task/usage.ex
Labels: bug-fix

#1189 Add named version installer
  apps/core/lib/core/schema/cluster.ex
  apps/core/lib/core/services/charts.ex
  apps/core/lib/core/services/terraform.ex
  apps/core/test/services/charts_test.exs
  apps/core/test/services/terraform_test.exs
  apps/core/test/support/factory.ex
  apps/graphql/lib/graphql/resolvers/cluster.ex
  apps/graphql/lib/graphql/resolvers/version.ex
  apps/graphql/lib/graphql/schema/version.ex
  apps/graphql/test/queries/cluster_queries_test.exs
  plural/helm/plural/Chart.yaml
  plural/helm/plural/values.yaml
  schema/schema.graphql
  www/src/components/shell/terminal/sidebar/Sidebar.tsx
  www/src/components/shell/terminal/sidebar/installer/Installer.tsx
  www/src/generated/graphql.ts
Labels: enhancement, backend

#1193 feat(backend): support oidc token exchange
  apps/api/lib/api_web/guardian_pipeline.ex
  apps/core/lib/core/application.ex
  apps/core/lib/core/policies/user.ex
  apps/core/lib/core/schema/oidc_trust_relationship.ex
  apps/core/lib/core/schema/user.ex
  apps/core/lib/core/services/users.ex
  apps/core/mix.exs
  apps/core/priv/repo/migrations/20230810182651_oidc_trust_relationships.exs
  apps/core/test/auth/jwt_test.exs
  apps/core/test/services/users_test.exs
  apps/core/test/support/factory.ex
  apps/graphql/lib/graphql/resolvers/user.ex
  apps/graphql/lib/graphql/schema/user.ex
  apps/graphql/test/mutations/user_mutation_test.exs
  apps/graphql/test/queries/user_queries_test.exs
  apps/graphql/test/test_helper.exs
  config/config.exs
  config/test.exs
  mix.lock
  schema/schema.graphql
  www/src/components/shell/terminal/sidebar/Sidebar.tsx
  www/src/generated/graphql.ts
Labels: enhancement, backend

#1197 Use id token sub to validate trust relationships
  apps/core/lib/core/services/users.ex
  apps/core/test/services/users_test.exs
  apps/graphql/test/queries/user_queries_test.exs
Labels: enhancement

#1199 Use new setup-plural in gh actions
  .github/workflows/publish.yaml
  .github/workflows/push-to-plural.yaml
Labels: enhancement

#1200 Add whitelist to set sysbox container runtime
  apps/core/lib/core/schema/account.ex
  apps/core/lib/core/services/shell/pods.ex
  apps/core/mix.exs
  apps/core/test/services/shell/pods_test.exs
  apps/cron/lib/cron/task/usage.ex
  config/config.exs
  config/test.exs
  mix.lock
  rel/config/config.exs
Labels: enhancement

#1202 Add docker jwt support
  apps/api/lib/api_web/controllers/auth_controller.ex
  apps/api/test/api_web/controllers/auth_controller_test.exs
  apps/core/lib/core/services/payments.ex
  apps/core/lib/core/services/users.ex
  apps/core/test/services/payments_test.exs
  apps/core/test/support/factory.ex
Labels: enhancement

#1205 Wire in appropriate toleration and node selectors for sysbox
  apps/core/lib/core/services/shell/pods.ex
  apps/core/test/services/shell/pods_test.exs
Labels: enhancement

#1207 Remove pushy onboarding CTAs
  apps/core/lib/core/services/repositories.ex
  apps/core/test/services/repositories_test.exs
  schema/schema.graphql
  www/src/components/layout/ApplicationLayout.tsx
  www/src/components/shell/terminal/Content.tsx
  www/src/generated/graphql.ts
Labels: enhancement

#1208 Support sysbox dind setup
  apps/core/lib/core/services/shell/pods.ex
  apps/core/test/services/shell/pods_test.exs
  apps/cron/lib/cron/task/usage.ex
  apps/cron/test/cron/task/usage_test.exs
  rel/config/plural.exs
Labels: enhancement

#1209 fix: Marketplace search field coverd by page content
  www/src/components/marketplace/MarketplaceRepositories.tsx
Labels: bug-fix, frontend

#1213 Visualize sync and locked state in cluster page
  apps/core/lib/core/schema/installation.ex
  apps/core/priv/repo/migrations/20230823162714_backfill_synced.exs
  www/src/components/cluster/ClusterApp.tsx
  www/src/components/cluster/queries.ts
Labels: enhancement

#1219 fix: Could not change automatic upgrades setting
  www/package.json
  www/src/components/app/AppSidenav.tsx
  www/src/components/app/upgrade/Upgrade.tsx
  www/src/contexts/AppContext.tsx
  www/src/generated/graphql.ts
  www/src/graph/repos.graphql
  www/yarn.lock
Labels: bug-fix, frontend

#1222 feat: Reduce load time on /marketplace
  www/src/generated/graphql.ts
  www/src/graph/installations.graphql
  www/src/graph/repos.graphql
  www/src/models/repo.ts
Labels: enhancement

#1220 Add Cluster Usage History Recording
  apps/core/lib/core/schema/cluster_usage_history.ex
  apps/core/lib/core/services/clusters.ex
  apps/core/priv/repo/migrations/20230828190601_add_cluster_usage.exs
  apps/core/test/services/clusters_test.exs
  apps/core/test/support/factory.ex
  apps/graphql/lib/graphql/resolvers/cluster.ex
  apps/graphql/lib/graphql/schema/cluster.ex
  apps/graphql/test/queries/cluster_queries_test.exs
  apps/rtc/lib/rtc_web/channels/upgrade_channel.ex
  apps/rtc/test/rtc_web/channels/upgrade_channel_test.exs
  schema/schema.graphql
  www/src/generated/graphql.ts
Labels: enhancement

#1225 Add potential fixes for email pre tags
  apps/core/lib/core/services/shell/pods.ex
  apps/core/test/services/shell/pods_test.exs
  apps/email/lib/email_web/templates/email/locked_installation.html.eex
  apps/email/lib/email_web/templates/email/locked_upgrades.html.eex
  apps/email/lib/email_web/templates/shared/pre.html.eex
  apps/email/lib/email_web/views/email_view.ex
  apps/rtc/test/rtc_web/channels/upgrade_channel_test.exs
Labels: enhancement

#1227 Use `sysbox-runc` as runtime class for sysbox shells
  apps/core/lib/core/services/shell/pods.ex
  apps/core/test/services/shell/pods_test.exs
Labels: enhancement

#1231 Filter upgrade notifications on users with active clusters
  apps/core/lib/core/schema/notification.ex
  apps/core/lib/core/services/clusters.ex
  apps/cron/lib/cron/digest/locked.ex
  apps/cron/lib/cron/digest/pending.ex
  apps/cron/test/cron/digest/locked_test.exs
  apps/cron/test/cron/digest/pending_test.exs
  apps/email/lib/email/builder/base.ex
  apps/email/lib/email/builder/locked_installation.ex
  apps/email/lib/email/builder/pending_promotion.ex
  apps/email/test/email/builder/locked_installation_test.exs
  apps/email/test/email/deliverable/versions_test.exs
Labels: enhancement

#1233 Allow independent configuration of images for sysbox shells
  apps/core/lib/core/services/shell/pods.ex
  apps/core/test/services/shell/pods_test.exs
  rel/config/plural.exs
Labels: enhancement
