Repository pluralsh/plural, pull requests merged in 2023-09, with the labels that each got.

#1235 Update plural nodes to 1.24
  plural/terraform/aws/deps.yaml
  plural/terraform/aws/variables.tf
Labels: enhancement

#1237 Make oidc provider transfer more robust
  apps/core/lib/core/services/clusters/transfer.ex
  docker-compose.yml
Labels: enhancement

#1239 Detect and defer upgrades for lock
  apps/core/lib/core/services/rollouts/rollable/versions.ex
  apps/core/test/services/rollable/versions_test.exs
Labels: bug, enhancement

#1241 Fix upgrade channel mutation
  apps/core/lib/core/services/clusters.ex
  apps/graphql/lib/graphql/resolvers/cluster.ex
  apps/graphql/lib/graphql/schema/cluster.ex
  schema/schema.graphql
  www/src/components/app/upgrade/Upgrade.tsx
  www/src/generated/graphql.ts
  www/src/models/repo.ts
  www/src/models/user.ts
Labels: bug-fix

#1236 fix: default version of azure provider
  apps/core/priv/scaffolds/terraform/providers/azure.eex
Labels: bug-fix

#1243 Add shell uniqueness detection
  apps/core/lib/core/schema/cloud_shell.ex
  apps/core/lib/core/services/shell/pods.ex
  apps/core/priv/repo/migrations/20230906192008_shell_owner.exs
  apps/rtc/lib/rtc_web/channels/shell_channel.ex
  apps/rtc/test/rtc_web/channels/shell_channel_test.exs
Labels: enhancement

#1246 Shell duplicate detection release
  apps/rtc/lib/rtc_web/channels/shell_channel.ex
  www/src/components/shell/terminal/Terminal.tsx
Labels: enhancement

#1250 chore(deps): bump cli to latest version
  Dockerfile
Labels: dependencies

#1252 fix: use the console version of the CLI
  Dockerfile
Labels: bug-fix, hotfix
