Repository pluralsh/plural, pull requests merged in 2023-05, with the labels that each got.

#1086 Make stack/category queries public
  apps/core/lib/core/policies/recipe.ex
  apps/core/lib/core/services/recipes.ex
  apps/graphql/lib/graphql/resolvers/recipe.ex
  apps/graphql/lib/graphql/schema/recipe.ex
  apps/graphql/lib/graphql/schema/repository.ex
  apps/graphql/test/queries/recipe_queries_test.exs
  apps/graphql/test/queries/repository_queries_test.exs
Labels: enhancement

#1087 Release v0.10.1
  plural/helm/plural/Chart.yaml
Labels: release

#1089 fix: update k8s tf provider in scaffolds
  apps/core/priv/scaffolds/terraform/providers/aws.eex
  apps/core/priv/scaffolds/terraform/providers/azure.eex
  apps/core/priv/scaffolds/terraform/providers/equinix.eex
  apps/core/priv/scaffolds/terraform/providers/gcp.eex
  apps/core/priv/scaffolds/terraform/providers/generic.eex
  apps/core/priv/scaffolds/terraform/providers/kind.eex
Labels: bug-fix

#1090 chore(deps): release v0.10.2
  plural/helm/plural/Chart.yaml
Labels: release

#1094 Allow jwt to be fetched when present
  apps/core/priv/scaffolds/Pluralfile.eex
  apps/graphql/lib/graphql/schema/user.ex
  www/src/components/stack/Stack.tsx
  www/src/components/stack/StackApps.tsx
Labels: enhancement

#1095 Rename warm to stable
  apps/core/lib/core/backfill/repositories.ex
  apps/core/lib/core/schema/installation.ex
  apps/core/priv/repo/seeds/013_warm_stable.exs
  apps/core/test/backfill/repositories_test.exs
Labels: enhancement, backend

#1099 Add validation for circular dependencies
  apps/core/lib/core/schema/user.ex
  apps/core/lib/core/services/clusters.ex
  apps/core/test/services/clusters_test.exs
Labels: enhancement, backend

#1098 fix: Avoid circular dependencies between clusters
  www/src/components/app/upgrade/Upgrade.tsx
  www/src/components/cluster/ClusterDependencyModal.tsx
  www/src/components/overview/clusters/ClusterList.tsx
Labels: bug-fix

#1103 Add groups to invites
  apps/core/lib/core/schema/invite.ex
  apps/core/lib/core/schema/invite_group.ex
  apps/core/lib/core/services/accounts.ex
  apps/core/priv/repo/migrations/20230516192249_add_invite_groups.exs
  apps/core/test/services/accounts_test.exs
  apps/core/test/support/test_helpers.ex
  apps/graphql/lib/graphql/schema/account.ex
  schema/schema.graphql
  www/src/generated/graphql.ts
Labels: enhancement, backend

#1097 Release v0.10.4
  plural/helm/plural/Chart.yaml
Labels: release

#1100 Delete Dependency
  apps/core/lib/core/services/clusters.ex
  apps/core/test/services/clusters_test.exs
  apps/graphql/lib/graphql/resolvers/cluster.ex
  apps/graphql/lib/graphql/schema/cluster.ex
  apps/graphql/test/mutations/cluster_mutations_test.exs
  schema/schema.graphql
  www/src/generated/graphql.ts
Labels: enhancement, backend

#1102 fix: Add domain uniqueness validation to the installer
  www/src/components/shell/terminal/sidebar/installer/ConfigurationItem.tsx
  www/src/components/shell/terminal/sidebar/installer/Installer.tsx
  www/src/components/shell/terminal/sidebar/installer/context.tsx
Labels: bug-fix

#1104 Release v0.10.5
  plural/helm/plural/Chart.yaml
Labels: enhancement, backend

#1108 Handle dangling dns records on demo project delete
  apps/core/lib/core.ex
  apps/core/lib/core/services/dns.ex
Labels: bug-fix

#1109 Release v0.10.6
  Makefile
  plural/helm/plural/Chart.yaml
Labels: enhancement

#1105 feat: Allow users to disable promotions
  www/src/components/cluster/ClusterPromoteModal.tsx
  www/src/components/overview/clusters/ClusterList.tsx
  www/src/components/overview/clusters/columns.tsx
  www/src/components/overview/clusters/types.ts
  www/src/components/overview/queries.ts
  www/src/contexts/ClustersContext.tsx
  www/yarn.lock
Labels: enhancement

#1110 feat: Hide installer steps for already installed apps
  www/src/components/shell/terminal/sidebar/Sidebar.tsx
  www/src/components/shell/terminal/sidebar/installed/Installed.tsx
  www/src/components/shell/terminal/sidebar/installer/Installer.tsx
  www/src/components/shell/terminal/sidebar/installer/helpers.tsx
Labels: enhancement, frontend
