Repository pluralsh/plural, pull requests merged in 2023-03, with the labels that each got.

#970 Fix demo repo creation
  apps/core/lib/core/services/shell.ex
  apps/core/lib/core/services/shell/scm.ex
  apps/core/test/services/shell_test.exs
Labels: bug-fix, backend

#971 Release version 0.9.41
  plural/helm/plural/Chart.yaml
Labels: enhancement, backend

#972 Use demo project id for demo repo name
  apps/core/lib/core/schema/user.ex
  apps/core/lib/core/services/shell.ex
  apps/core/test/services/shell_test.exs
Labels: bug-fix, backend

#973 release v0.9.42
  plural/helm/plural/Chart.yaml
Labels: dependencies, release

#974 Expose demoed field in the GQL User object
  apps/core/lib/core/services/shell/demo.ex
  apps/core/lib/core/services/users.ex
  apps/graphql/lib/graphql/schema/user.ex
  apps/graphql/test/queries/user_queries_test.exs
  schema/schema.graphql
  www/src/generated/graphql.ts
Labels: enhancement, backend

#975 Better service enable polling
  apps/core/lib/core/services/shell/demo.ex
  apps/core/test/services/shell/demo_test.exs
Labels: enhancement, backend

#976 release v0.9.43
  plural/helm/plural/Chart.yaml
Labels: enhancement, release

#967 Add usage recompute
  apps/core/lib/core/services/accounts.ex
  apps/core/test/services/accounts_test.exs
Labels: enhancement, backend, hotfix

#969 Implement cluster promotions
  apps/core/lib/core/policies/account.ex
  apps/core/lib/core/schema/cluster.ex
  apps/core/lib/core/schema/cluster_dependency.ex
  apps/core/lib/core/schema/deferred_update.ex
  apps/core/lib/core/schema/platform_plan.ex
  apps/core/lib/core/schema/user.ex
  apps/core/lib/core/services/clusters.ex
  apps/core/lib/core/services/dependencies.ex
  apps/core/lib/core/services/rollouts/rollable/versions.ex
  apps/core/lib/core/services/upgrades.ex
  apps/core/priv/repo/migrations/20230226032204_cluster_promotions.exs
  apps/core/test/services/clusters_test.exs
  apps/core/test/services/dependencies_test.exs
  apps/core/test/services/rollable/versions_test.exs
  apps/core/test/services/upgrades_test.exs
  apps/core/test/support/factory.ex
  apps/graphql/lib/graphql.ex
  apps/graphql/lib/graphql/resolvers/cluster.ex
  apps/graphql/lib/graphql/resolvers/dataloaders.ex
  apps/graphql/lib/graphql/schema/cluster.ex
  apps/graphql/lib/graphql/schema/upgrade.ex
  apps/graphql/test/mutations/cluster_mutations_test.exs
  apps/graphql/test/queries/cluster_queries_test.exs
  schema/schema.graphql
  www/src/generated/graphql.ts
Labels: enhancement, backend

#978 release v0.9.44
  plural/helm/plural/Chart.yaml
Labels: enhancement, backend, release

#979 Fix stale struct error when deleting deferred updates
  apps/core/lib/core/services/upgrades.ex
Labels: bug-fix, hotfix

#968 feat: Restore GCP demo and update onboarding flow
  www/package.json
  www/src/components/shell/OAuthCallback.tsx
  www/src/components/shell/Shell.tsx
  www/src/components/shell/_old/cloud/CloudBuild.tsx
  www/src/components/shell/_old/cloud/CloudCredentials.tsx
  www/src/components/shell/_old/cloud/CloudLaunch.tsx
  www/src/components/shell/_old/cloud/CloudSelect.tsx
  www/src/components/shell/_old/cloud/CloudWorkspace.tsx
  www/src/components/shell/_old/cloud/aws.tsx
  www/src/components/shell/_old/cloud/azure.tsx
  www/src/components/shell/_old/cloud/gcp.tsx
  www/src/components/shell/_old/cloud/provider.tsx
  www/src/components/shell/onboarding/Onboarding.tsx
  www/src/components/shell/onboarding/OnboardingCard.tsx
  www/src/components/shell/onboarding/OnboardingFlow.tsx
  www/src/components/shell/onboarding/OnboardingHeader.tsx
  www/src/components/shell/onboarding/OnboardingSidenav.tsx
  www/src/components/shell/onboarding/OnboardingTips.tsx
  www/src/components/shell/onboarding/assets/CalendarIcon.svg
  www/src/components/shell/onboarding/assets/GCPLogoIcon.svg
  www/src/components/shell/onboarding/assets/OnboardingTitleOnboarding.svg
  www/src/components/shell/onboarding/context/hooks.ts
  www/src/components/shell/onboarding/context/onboarding.ts
  www/src/components/shell/onboarding/context/types.ts
  www/src/components/shell/onboarding/sections/cli/CLIInstallationStep.tsx
  www/src/components/shell/onboarding/sections/cloud/CloudOption.tsx
  www/src/components/shell/onboarding/sections/cloud/CloudStep.tsx
  www/src/components/shell/onboarding/sections/cloud/ProviderSelection.tsx
  www/src/components/shell/onboarding/sections/cloud/provider/AWS.tsx
  www/src/components/shell/onboarding/sections/cloud/provider/Azure.tsx
  www/src/components/shell/onboarding/sections/cloud/provider/GCP.tsx
  www/src/components/shell/onboarding/sections/overview/OverviewStep.tsx
  www/src/components/shell/onboarding/sections/repository/ProviderConfiguration.tsx
  www/src/components/shell/onboarding/sections/repository/ProviderSelection.tsx
  www/src/components/shell/onboarding/sections/repository/RepositoryStep.tsx
  www/src/components/shell/onboarding/sections/shell/CreateShell.tsx
  www/src/components/shell/onboarding/sections/shell/CreateShellStep.tsx
  www/src/components/shell/onboarding/sections/shell/ShellStatus.tsx
  www/src/components/shell/onboarding/sections/shell/Summary.tsx
  www/src/components/shell/onboarding/sections/workspace/CreateDemo.tsx
  www/src/components/shell/onboarding/sections/workspace/DemoStatus.tsx
  www/src/components/shell/onboarding/sections/workspace/WorkspaceConfiguration.tsx
  www/src/components/shell/onboarding/sections/workspace/WorkspaceStep.tsx
  www/src/components/shell/queries.ts
  www/src/components/shell/terminal/actionbar/options/DeleteShellModal.tsx
  www/src/components/shell/terminal/actionbar/options/provider/AWS.tsx
  www/src/components/shell/terminal/actionbar/options/provider/Azure.tsx
  www/src/components/shell/terminal/installer/Installer.tsx
  www/src/generated/graphql.ts
  www/src/graph/users.graphql
  www/src/utils/object.ts
  www/src/utils/posthog.ts
  www/yarn.lock
Labels: enhancement, frontend

#966 Fix language on payment methods screen
  www/src/components/account/billing/BillingBankCards.tsx
Labels: bug-fix, frontend

#980 Release v0.9.45
  .github/workflows/pr-labels.yaml
  plural/helm/plural/Chart.yaml
Labels: backend, release

#981 Manually refetch queries after cloud shell install
  www/src/components/shell/onboarding/sections/cloud/ProviderSelection.tsx
  www/src/components/shell/terminal/installer/helpers.tsx
Labels: enhancement

#984 Make account fetch external
  apps/graphql/lib/graphql/schema/account.ex
Labels: enhancement

#985 Release v0.9.46
  plural/helm/plural/Chart.yaml
Labels: hotfix, release

#986 feat: Make platform plans fetch external
  apps/graphql/lib/graphql/schema/payments.ex
Labels: enhancement, backend

#983 Expose pinged_at field for repository installation
  apps/graphql/lib/graphql/schema/repository.ex
  schema/schema.graphql
  www/src/generated/graphql.ts
Labels: enhancement, backend

#989 Preselect app based on url query param
  www/src/components/shell/terminal/installer/Installer.tsx
  www/src/components/shell/terminal/installer/helpers.tsx
Labels: enhancement

#990 Add primary flag for recipes
  apps/core/lib/core/schema/recipe.ex
  apps/core/priv/repo/migrations/20230307173310_add_recipe_primary.exs
  apps/graphql/lib/graphql/schema/recipe.ex
  www/src/components/shell/onboarding/sections/workspace/CreateDemo.tsx
Labels: enhancement, backend, hotfix

#992 fix: Broken blog post link in BillingMigrationModal
  www/src/components/account/billing/BillingMigrationModal.tsx
Labels: bug-fix

#988 fix: Pricing style adjustments
  www/src/components/account/Groups.tsx
  www/src/components/account/Roles.tsx
  www/src/components/account/ServiceAccounts.tsx
  www/src/components/account/billing/BillingFeatureBlockBanner.tsx
  www/src/components/account/billing/BillingLayout.tsx
  www/src/components/account/billing/BillingLegacyUserBanner.tsx
Labels: design, bug-fix, frontend

#987 feat: update azure tf provider template
  apps/core/priv/scaffolds/terraform/providers/0.1.3/azure.eex
Labels: enhancement, backend

#993 Release v0.9.47
  plural/helm/plural/Chart.yaml
Labels: release

#994 Fix create default plan logic
  apps/core/lib/core/services/payments.ex
Labels: bug-fix, hotfix

#991 feat: Provide different flows for app install buttons based on user state
  www/src/components/repository/OIDCProvider.tsx
  www/src/components/repository/Repository.tsx
  www/src/components/repository/RepositoryArtifacts.tsx
  www/src/components/repository/RepositoryDeployments.tsx
  www/src/components/repository/RepositoryDescription.tsx
  www/src/components/repository/RepositoryEdit.tsx
  www/src/components/repository/RepositoryPackages.tsx
  www/src/components/repository/RepositoryPackagesDocker.tsx
  www/src/components/repository/RepositoryPackagesHelm.tsx
  www/src/components/repository/RepositoryPackagesTerraform.tsx
  www/src/components/repository/RepositorySideCar.tsx
  www/src/components/repository/RepositorySideNav.tsx
  www/src/components/repository/RepositoryTests.tsx
  www/src/components/repository/misc.tsx
  www/src/components/shell/terminal/installer/Installer.tsx
  www/src/components/stack/StackApps.tsx
  www/src/components/stack/misc.tsx
  www/src/components/stack/types.ts
  www/src/components/utils/InstallDropdownButton.tsx
  www/src/contexts/CurrentUserContext.tsx
  www/src/contexts/RepositoryContext.ts
  www/src/contexts/RepositoryContext.tsx
  www/src/generated/graphql.ts
  www/src/graph/recipes.graphql
  www/src/graph/repos.graphql
Labels: enhancement

#996 fix: Support FILE config input types
  www/src/components/shell/terminal/installer/Configuration.tsx
  www/src/components/shell/terminal/installer/ConfigurationFileInput.tsx
  www/src/components/shell/terminal/installer/ConfigurationItem.tsx
  www/src/components/shell/terminal/installer/types.ts
Labels: bug-fix

#995 Don't toggle account delinquency on downgrade
  apps/core/lib/core/services/payments.ex
Labels: enhancement, backend

#997 Release v0.9.48
  plural/helm/plural/Chart.yaml
Labels: hotfix, release

#998 feat: Available cloud providers sidecar and install commands
  www/src/components/repository/RepositorySideCar.tsx
  www/src/components/repository/misc.tsx
  www/src/components/stack/Stack.tsx
  www/src/components/stack/misc.tsx
  www/src/components/utils/InstallCommandCopyButton.tsx
  www/src/components/utils/InstallDropdownButton.tsx
  www/src/components/utils/recipeHelpers.tsx
  www/src/generated/graphql.ts
  www/src/graph/repos.graphql
Labels: enhancement, frontend

#936 Posthog id additions/fixes
  www/src/components/shell/onboarding/sections/cloud/CloudStep.tsx
  www/src/components/shell/onboarding/sections/cloud/ProviderSelection.tsx
  www/src/components/shell/terminal/actionbar/cheatsheet/CheatsheetCommand.tsx
Labels: enhancement

#999 feat: Add installed apps view to the cloud shell sidebar
  www/package.json
  www/src/components/shell/terminal/Content.tsx
  www/src/components/shell/terminal/Terminal.tsx
  www/src/components/shell/terminal/actionbar/options/MoreOptions.tsx
  www/src/components/shell/terminal/context/terminal.ts
  www/src/components/shell/terminal/queries.ts
  www/src/components/shell/terminal/sidebar/Sidebar.tsx
  www/src/components/shell/terminal/sidebar/installed/Installed.tsx
  www/src/components/shell/terminal/sidebar/installed/LaunchAppModal.tsx
  www/src/components/shell/terminal/sidebar/installed/helpers.tsx
  www/src/components/shell/terminal/sidebar/installer/Application.tsx
  www/src/components/shell/terminal/sidebar/installer/Configuration.tsx
  www/src/components/shell/terminal/sidebar/installer/ConfigurationFileInput.tsx
  www/src/components/shell/terminal/sidebar/installer/ConfigurationItem.tsx
  www/src/components/shell/terminal/sidebar/installer/Installer.tsx
  www/src/components/shell/terminal/sidebar/installer/helpers.tsx
  www/src/components/shell/terminal/sidebar/installer/queries.ts
  www/yarn.lock
Labels: enhancement, frontend

#1000 fix: Couldn’t unset a file in ConfigurationFileInput
  www/src/components/shell/onboarding/sections/cloud/provider/GCP.tsx
  www/src/components/shell/terminal/actionbar/options/provider/GCP.tsx
  www/src/components/shell/terminal/sidebar/installer/ConfigurationFileInput.tsx
  www/src/components/utils/fileInputTheme.tsx
  www/src/theme.ts
Labels: bug-fix

#1001 feat: Add legacy expiration Toast or Modal depending on expiration date
  www/src/components/Plural.tsx
  www/src/components/account/billing/BillingLegacyUserMessage.tsx
  www/src/components/login/LegacyExpiration.tsx
  www/src/helpers/localStorage.ts
Labels: enhancement, frontend

#1003 Release v0.9.49
  plural/helm/plural/Chart.yaml
Labels: release

#1005 Removed posthog feature flag for pricing
  www/src/components/account/AccountSidenav.tsx
  www/src/components/account/billing/BillingLayout.tsx
  www/src/components/account/billing/BillingSubscriptionProvider.tsx
  www/src/contexts/SubscriptionContext.ts
Labels: bug-fix, frontend

#1006 update aws node group amis
  plural/terraform/aws/deps.yaml
  plural/terraform/aws/variables.tf
Labels: dependencies

#1008 Pay outstanding invoices when changing card
  apps/core/lib/core/services/payments.ex
  apps/core/test/services/payments_test.exs
  apps/core/test/test_helper.exs
Labels: bug-fix

#1004 fix(frontend): add address element and fix add cards
  www/src/components/Plural.tsx
  www/src/components/WrapStripe.tsx
  www/src/components/account/billing/BillingBankCards.tsx
  www/src/components/account/billing/BillingError.tsx
  www/src/components/account/billing/BillingUpgradeToProfessionalModal.tsx
  www/src/components/account/billing/useBankCard.tsx
  www/src/generated/graphql.ts
  www/src/graph/payments.graphql
Labels: bug-fix, frontend

#1013 fix(backend): update schema
  schema/schema.graphql
  www/src/generated/graphql.ts
Labels: bug-fix, backend

#1011 feat: Update text in legacy expiration notices
  www/src/components/login/LegacyExpiration.tsx
Labels: enhancement, frontend

#1015 feat: User limit modal
  www/src/components/Plural.tsx
  www/src/components/account/InviteUser.tsx
  www/src/components/account/Invites.tsx
  www/src/components/account/Users.tsx
  www/src/components/account/billing/BillingPricingCards.tsx
  www/src/components/account/billing/BillingPricingTable.tsx
  www/src/generated/graphql.ts
  www/src/graph/users.graphql
Labels: enhancement, frontend

#1019 feat: Update login sidebar
  www/public/login-sidebar.jpg
  www/src/components/users/LoginPortal.tsx
Labels: design, frontend

#1020 fix: Loading improvements
  www/src/components/Plural.tsx
  www/src/components/account/CreateRole.tsx
  www/src/components/account/CreateServiceAccount.tsx
  www/src/components/account/GroupsList.tsx
  www/src/components/account/Invites.tsx
  www/src/components/account/Roles.tsx
  www/src/components/account/ServiceAccounts.tsx
  www/src/components/account/UsersList.tsx
  www/src/components/account/billing/BillingPlatformPlansProvider.tsx
  www/src/components/account/billing/BillingSubscriptionProvider.tsx
  www/src/components/account/billing/queries.ts
  www/src/components/audits/AuditDirectory.tsx
  www/src/components/audits/Audits.tsx
  www/src/components/audits/LoginAudits.tsx
  www/src/components/clusters/Clusters.tsx
  www/src/components/clusters/ClustersContent.tsx
  www/src/components/layout/Sidebar.tsx
  www/src/components/login/CurrentUser.tsx
  www/src/components/login/LegacyExpiration.tsx
  www/src/components/marketplace/MarketplaceRepositories.tsx
  www/src/components/oidc/OAuthConsent.tsx
  www/src/components/profile/AccessTokens.tsx
  www/src/components/profile/EabCredentials.tsx
  www/src/components/profile/PublicKeys.tsx
  www/src/components/publisher/Publisher.tsx
  www/src/components/repository/Repository.tsx
  www/src/components/repository/RepositoryDeployments.tsx
  www/src/components/repository/RepositoryPackagesDocker.tsx
  www/src/components/repository/RepositoryPackagesHelm.tsx
  www/src/components/repository/RepositoryPackagesTerraform.tsx
  www/src/components/repository/RepositoryTests.tsx
  www/src/components/repository/packages/Docker.tsx
  www/src/components/repository/packages/helm/PackageUpdateQueue.tsx
  www/src/components/shell/OAuthCallback.tsx
  www/src/components/shell/Shell.tsx
  www/src/components/shell/terminal/Content.tsx
  www/src/components/shell/terminal/actionbar/options/EditCloudCredentialsModal.tsx
  www/src/components/shell/terminal/sidebar/installer/Installer.tsx
  www/src/components/stack/Stack.tsx
  www/src/components/users/EmailConfirmation.tsx
  www/src/components/users/OAuthCallback.tsx
  www/src/components/users/SSOCallback.tsx
  www/src/components/utils/AlternatingBox.tsx
  www/src/components/utils/AnimatedLogo.tsx
  www/src/components/utils/Date.tsx
  www/src/components/utils/Header.tsx
  www/src/components/utils/IconOld.tsx
  www/src/components/utils/LoadingIndicator.tsx
  www/src/components/utils/NumericInput.tsx
  www/src/components/utils/colors.ts
  www/src/contexts/PlatformPlansContext.ts
  www/src/contexts/SubscriptionContext.ts
Labels: bug-fix, frontend

#1023 Release v0.9.51
  plural/helm/plural/Chart.yaml
Labels: hotfix, release

#1022 feat: Update marketplace icon
  www/package.json
  www/src/components/layout/Sidebar.tsx
  www/src/components/shell/onboarding/checklist/Checklist.tsx
  www/yarn.lock
Labels: enhancement, design

#1012 Add support for payment intents
  apps/core/lib/core/policies/payments.ex
  apps/core/lib/core/schema/platform_subscription.ex
  apps/core/lib/core/services/payments.ex
  apps/core/lib/core/stripe/handler.ex
  apps/core/priv/repo/migrations/20230316171607_add_subscription_status.exs
  apps/core/test/services/accounts_test.exs
  apps/core/test/services/payments_test.exs
  apps/core/test/stripe/handler_test.exs
  apps/core/test/support/factory.ex
  apps/core/test/test_helper.exs
  apps/graphql/lib/graphql/resolvers/payments.ex
  apps/graphql/lib/graphql/schema/account.ex
  apps/graphql/lib/graphql/schema/payments.ex
  apps/graphql/lib/graphql/schema/user.ex
  apps/graphql/test/mutations/payments_mutation_test.exs
  apps/graphql/test/queries/account_queries_test.exs
  apps/graphql/test/test_helper.exs
  schema/schema.graphql
  www/codegen.yml
  www/package.json
  www/src/components/account/billing/BillingUpgradeToProfessionalModal.tsx
  www/src/generated/graphql.ts
  www/src/graph/payments.graphql
  www/src/helpers/hostname.ts
  www/yarn.lock
Labels: enhancement, backend

#1002 added plural console repos to changelog and feature requests
  www/src/components/roadmap/RoadmapChangelog.tsx
  www/src/components/roadmap/RoadmapDataProvider.tsx
  www/src/components/roadmap/RoadmapFeatureRequests.tsx
  www/src/components/roadmap/RoadmapIssue.tsx
  www/src/components/roadmap/RoadmapRoadmap.tsx
  www/src/components/roadmap/types.ts
  www/src/components/roadmap/useRoadmapData.ts
  www/src/contexts/RoadmapContext.ts
Labels: bug-fix, frontend

#1028 fix: Retrieve plan name in Subscription query
  www/src/components/account/billing/BillingSubscriptionProvider.tsx
  www/src/generated/graphql.ts
  www/src/graph/payments.graphql
Labels: bug-fix

#1027 Add watch command to installed nubs
  apps/core/lib/core/services/shell.ex
  apps/core/lib/core/services/shell/client.ex
  apps/core/lib/core/services/shell/client/application.ex
  apps/graphql/lib/graphql/resolvers/shell.ex
  apps/graphql/lib/graphql/schema/shell.ex
  apps/graphql/test/queries/shell_queries_test.exs
  www/src/components/shell/terminal/sidebar/installed/helpers.tsx
Labels: enhancement

#1026 release v0.9.52
  plural/helm/plural/Chart.yaml
Labels: release

#1033 Demo Delete Button
  apps/core/lib/core/services/shell/demo.ex
  apps/core/test/services/shell/demo_test.exs
  apps/graphql/lib/graphql/resolvers/shell.ex
  apps/graphql/lib/graphql/schema/shell.ex
  www/src/components/shell/terminal/actionbar/ActionBar.tsx
  www/src/components/shell/terminal/actionbar/options/DeleteShellModal.tsx
  www/src/graph/users.graphql
  www/src/helpers/hostname.ts
Labels: enhancement

#1034 feat: Make legacy user callouts dismissible
  www/package.json
  www/src/components/account/billing/BillingLegacyUserBanner.tsx
  www/yarn.lock
Labels: enhancement

#1036 Release v0.9.53
  plural/helm/plural/Chart.yaml
Labels: release

#1032 feat: Payment Intents Improvements
  www/src/components/account/billing/BillingDowngradeModal.tsx
  www/src/components/account/billing/BillingInvoices.tsx
  www/src/components/account/billing/BillingPricingCards.tsx
  www/src/components/account/billing/BillingSubscriptionProvider.tsx
  www/src/components/account/billing/ConfirmPayment.tsx
  www/src/components/account/billing/PaymentForm.tsx
  www/src/components/account/billing/hooks.tsx
  www/src/components/account/billing/useRetrieveIntent.tsx
  www/src/contexts/SubscriptionContext.ts
Labels: enhancement, frontend

#1031 Surface health info in cloud shell installer
  apps/graphql/test/queries/shell_queries_test.exs
  schema/schema.graphql
  www/src/components/shell/terminal/sidebar/installed/Installed.tsx
  www/src/components/shell/terminal/sidebar/installed/helpers.tsx
  www/src/components/shell/terminal/sidebar/installer/Installer.tsx
  www/src/components/shell/terminal/sidebar/installer/queries.ts
  www/src/generated/graphql.ts
  www/src/graph/payments.graphql
Labels: enhancement

#1040 Add `hasShell` to user gql schema
  apps/core/lib/core/schema/cloud_shell.ex
  apps/graphql/lib/graphql.ex
  apps/graphql/lib/graphql/resolvers/dataloaders.ex
  apps/graphql/lib/graphql/resolvers/upgrade.ex
  apps/graphql/lib/graphql/schema/user.ex
  apps/graphql/test/queries/cluster_queries_test.exs
  schema/schema.graphql
  www/src/generated/graphql.ts
Labels: enhancement

#1039 Add repository `release_status`
  apps/core/lib/core/schema/repository.ex
  apps/core/priv/repo/migrations/20230330210655_add_release_status.exs
  apps/graphql/lib/graphql/schema/repository.ex
  schema/schema.graphql
  www/src/generated/graphql.ts
Labels: enhancement

#1042 Release v0.9.54
  plural/helm/plural/Chart.yaml
Labels: release
