Repository pluralsh/plural, pull requests merged in 2023-11, with the labels that each got.

#1270 Add service usage recording
  .tool-versions
  apps/core/lib/core/schema/cluster.ex
  apps/core/lib/core/schema/cluster_usage_history.ex
  apps/core/lib/core/schema/platform_plan.ex
  apps/core/lib/core/schema/platform_subscription.ex
  apps/core/lib/core/services/clusters.ex
  apps/core/lib/core/services/payments.ex
  apps/core/priv/repo/migrations/20231107002129_service_usage.exs
  apps/core/priv/repo/migrations/20231107013705_add_service_product.exs
  apps/core/test/services/payments_test.exs
  apps/graphql/lib/graphql/schema/cluster.ex
  apps/rtc/test/rtc_web/channels/upgrade_channel_test.exs
  schema/schema.graphql
  www/src/generated/graphql.ts
Labels: enhancement, backend

#1269 feat: add cd onboarding path
  www/src/components/shell/onboarding/Onboarding.tsx
  www/src/components/shell/onboarding/OnboardingCardButton.tsx
  www/src/components/shell/onboarding/OnboardingFlow.tsx
  www/src/components/shell/onboarding/OnboardingHeader.tsx
  www/src/components/shell/onboarding/context/hooks.ts
  www/src/components/shell/onboarding/context/onboarding.ts
  www/src/components/shell/onboarding/context/types.ts
  www/src/components/shell/onboarding/sections/cloud/CloudOption.tsx
  www/src/components/shell/onboarding/sections/cloud/ProviderSelection.tsx
  www/src/components/shell/onboarding/sections/overview/OverviewStep.tsx
  www/src/components/shell/onboarding/sections/welcome/PathOption.tsx
  www/src/components/shell/onboarding/sections/welcome/WelcomeStep.tsx
Labels: enhancement

#1273 Updated in-app pricing page for CD
  www/src/components/account/billing/BillingPricingCards.tsx
  www/src/components/account/billing/BillingPricingTable.tsx
Labels: enhancement, frontend

#1276 Update plural repo README.md
  README.md
  www/public/deployment-services.png
Labels: enhancement
