Repository pluralsh/plural, pull requests merged in 2024-06, with the labels that each got.

#1312 feat: Remove legacy image from login portal
  www/public/login-sidebar.jpg
  www/src/components/users/LoginPortal.tsx
Labels: enhancement

#1314 Allow db to be configured by url
  plural/helm/plural/values.yaml
  rel/config/config.exs
Labels: enhancement, hotfix

#1316 Fix duplicate env vars on chartmuseum
  plural/helm/plural/Chart.yaml
  plural/helm/plural/templates/_helpers.tpl
  plural/helm/plural/templates/chartmuseum.yaml
Labels: enhancement, hotfix

#1317 Fix registry shared secret
  plural/helm/plural/Chart.yaml
  plural/helm/plural/templates/registry-config.yaml
Labels: bug-fix, hotfix

#1318 Fix roles
  plural/helm/plural/Chart.yaml
  plural/helm/plural/templates/rbac.yaml
Labels: bug-fix, hotfix

#1319 rm DEPLOYED_AT in plural-www deployment
  plural/helm/plural/Chart.yaml
  plural/helm/plural/templates/deployment.yaml
Labels: bug-fix, hotfix

#1320 Need to pin the hydra migration too
  plural/helm/plural/Chart.yaml
  plural/helm/plural/templates/migration.yaml
Labels: bug-fix, hotfix
