Repository pluralsh/plural, pull requests merged in 2024-09, with the labels that each got.

#1351 cloud setup flow
  www/index.html
  www/package.json
  www/src/App.tsx
  www/src/components/Plural.tsx
  www/src/components/account/utils.ts
  www/src/components/app/App.tsx
  www/src/components/app/oidc/OIDC.tsx
  www/src/components/cluster/Cluster.tsx
  www/src/components/cluster/ClusterAdminsModal.tsx
  www/src/components/cluster/ClusterUpgrades.tsx
  www/src/components/create-cluster/ConsoleCreationStatus.tsx
  www/src/components/create-cluster/CreateCluster.tsx
  www/src/components/create-cluster/CreateClusterActions.tsx
  www/src/components/create-cluster/CreateClusterWizard.tsx
  www/src/components/create-cluster/steps/AuthenticationStep.tsx
  www/src/components/create-cluster/steps/ConfigureCloudInstanceStep.tsx
  www/src/components/create-cluster/steps/DeployLocallyStep.tsx
  www/src/components/create-cluster/steps/HostingOptionsStep.tsx
  www/src/components/create-cluster/steps/InstallCliStep.tsx
  www/src/components/layout/ApplicationLayout.tsx
  www/src/components/login/CurrentUser.tsx
  www/src/components/overview/CreateClusterAction.tsx
  www/src/components/overview/CreateClusterModal.tsx
  www/src/components/overview/Overview.tsx
  www/src/components/overview/OverviewHeader.tsx
  www/src/components/overview/apps/Apps.tsx
  www/src/components/overview/clusters/ClusterHealth.tsx
  www/src/components/overview/clusters/ClusterList.tsx
  www/src/components/overview/clusters/ClusterListEmptyState.tsx
  www/src/components/overview/clusters/Clusters.tsx
  www/src/components/overview/clusters/ClustersHelpSection.tsx
  www/src/components/overview/clusters/SelfHostedTableCols.tsx
  www/src/components/overview/clusters/UpgradeList.tsx
  www/src/components/overview/clusters/UpgradeListItem.tsx
  www/src/components/overview/clusters/Upgrades.tsx
  www/src/components/overview/clusters/columns.tsx
  www/src/components/overview/clusters/plural-cloud/CloudInstanceTableCols.tsx
  www/src/components/overview/clusters/plural-cloud/ConsoleInstanceOIDC.tsx
  www/src/components/overview/clusters/plural-cloud/DeleteInstance.tsx
  www/src/components/overview/clusters/plural-cloud/EditInstance.tsx
  www/src/components/overview/clusters/plural-cloud/PluralCloudInstances.tsx
  www/src/components/overview/clusters/self-hosted/SelfHostedClusters.tsx
  www/src/components/shell/onboarding/OnboardingCard.tsx
  www/src/components/shell/onboarding/sections/cli/CLIInstallationStep.tsx
  www/src/components/utils/Alert.tsx
  www/src/components/utils/ImpersonateServiceAccount.tsx
  www/src/components/utils/PluralErrorBoundary.tsx
  www/src/contexts/ClustersContext.tsx
  www/src/contexts/ConsoleInstancesContext.tsx
  www/src/generated/graphql.ts
  www/src/graph/cluster.graphql
  www/src/graph/pluralCloud.graphql
  www/src/graph/users.graphql
  www/yarn.lock
Labels: enhancement, frontend

#1358 Add complexity checks
  apps/api/lib/api_web/router.ex
  apps/core/lib/core/schema/user.ex
  apps/graphql/lib/graphql/schema/user.ex
  apps/graphql/test/queries/user_queries_test.exs
  config/config.exs
  mix.exs
  mix.lock
  rel/config/config.exs
  schema/schema.graphql
  www/src/components/Plural.tsx
  www/src/components/login/CurrentUser.tsx
  www/src/components/marketplace/MarketplaceRepositories.tsx
  www/src/components/shell/onboarding/sections/cloud/CloudCredentials.tsx
  www/src/generated/graphql.ts
  www/src/graph/users.graphql
Labels: enhancement, hotfix

#1360 Implement captcha on login
  apps/core/mix.exs
  apps/graphql/lib/graphql/middleware/captcha.ex
  apps/graphql/lib/graphql/schema/user.ex
  apps/graphql/test/mutations/user_mutation_test.exs
  config/config.exs
  config/test.exs
  mix.lock
  schema/schema.graphql
  www/src/generated/graphql.ts
Labels: enhancement

#1362 feat: Implement reCAPTCHA
  www/package.json
  www/src/components/users/MagicLogin.tsx
  www/src/generated/graphql.ts
  www/src/graph/users.graphql
  www/yarn.lock
Labels: enhancement

#1361 Fix sso login
  apps/core/lib/core/services/users.ex
  apps/core/test/services/users_test.exs
  apps/graphql/test/mutations/user_mutation_test.exs
Labels: enhancement

#1366 Better dns resolver retries
  .github/workflows/www.yaml
  apps/core/lib/core/retry.ex
  apps/core/lib/core/services/cloud/workflow/shared.ex
Labels: enhancement

#1368 Allow instance deletion from pending state
  apps/core/lib/core/services/cloud/workflow/shared.ex
Labels: enhancement

#1367 cloud setup flow QA
  www/package.json
  www/src/components/create-cluster/ConsoleCreationStatus.tsx
  www/src/components/create-cluster/CreateCluster.tsx
  www/src/components/create-cluster/steps/ConfigureCloudInstanceStep.tsx
  www/src/components/create-cluster/steps/HostingOptionsStep.tsx
  www/src/components/layout/Sidebar.tsx
  www/src/components/overview/OverviewHeader.tsx
  www/src/components/overview/clusters/ClusterListEmptyState.tsx
  www/src/components/overview/clusters/plural-cloud/CloudInstanceTableCols.tsx
  www/src/components/overview/clusters/plural-cloud/ConsoleInstanceOIDC.tsx
  www/src/components/overview/clusters/plural-cloud/DeleteInstance.tsx
  www/src/components/users/EmailConfirmation.tsx
  www/yarn.lock
Labels: enhancement, frontend

#1369 Support me-central-1 region for dedicated hosting
  apps/api/lib/api_web/endpoint.ex
  apps/api/mix.exs
  apps/core/lib/core/schema/console_instance.ex
  apps/core/lib/core/schema/user.ex
  apps/core/lib/core/services/cloud/workflow.ex
  apps/core/lib/core/services/cloud/workflow/shared.ex
  apps/core/lib/core/services/users.ex
  apps/graphql/lib/graphql/resolvers/cloud.ex
  apps/graphql/lib/graphql/schema/cloud.ex
  apps/graphql/lib/graphql/schema/user.ex
  apps/graphql/test/mutations/user_mutation_test.exs
  apps/graphql/test/queries/cloud_queries_test.exs
  mix.lock
  schema/schema.graphql
  www/src/generated/graphql.ts
  www/src/graph/users.graphql
Labels: enhancement
