Repository pluralsh/plural, pull requests merged in 2024-08, with the labels that each got.

#1327 Add cockroach config secret to main plural chart
  plural/helm/plural/Chart.yaml
  plural/helm/plural/templates/secrets.yaml
Labels: enhancement, hotfix

#1328 Plural Cloud CRUD
  .github/workflows/daily.yml
  .github/workflows/firebase-hosting-pull-request.yml
  .github/workflows/test.yaml
  .github/workflows/www.yaml
  .gitignore
  .tool-versions
  Dockerfile
  Makefile
  apps/core/lib/core/clients/console.ex
  apps/core/lib/core/conduit/base.ex
  apps/core/lib/core/policies/cloud.ex
  apps/core/lib/core/pubsub/events.ex
  apps/core/lib/core/pubsub/protocols/fanout.ex
  apps/core/lib/core/schema/cloud_cluster.ex
  apps/core/lib/core/schema/cockroach_cluster.ex
  apps/core/lib/core/schema/console_instance.ex
  apps/core/lib/core/services/cloud.ex
  apps/core/lib/core/services/cloud/configuration.ex
  apps/core/lib/core/services/cloud/poller.ex
  apps/core/lib/core/services/cloud/workflow.ex
  apps/core/lib/core/services/clusters.ex
  apps/core/lib/core/services/payments.ex
  apps/core/lib/core/services/shell.ex
  apps/core/mix.exs
  apps/core/priv/repo/migrations/20240806022151_add_cloud_schemas.exs
  apps/core/test/pubsub/fanout/cloud_test.exs
  apps/core/test/services/cloud/workflow_test.exs
  apps/core/test/services/cloud_test.exs
  apps/core/test/support/factory.ex
  apps/core/test/test_helper.exs
  apps/cron/lib/cron/prune/cloud.ex
  apps/cron/test/cron/prune/cloud_test.exs
  apps/email/lib/email/builder/console_reaped.ex
  apps/email/lib/email/deliverable/cloud.ex
  apps/email/lib/email_web/templates/email/console_reaped.html.eex
  apps/email/lib/email_web/templates/email/console_reaped.text.eex
  apps/email/test/email/deliverable/cloud_test.exs
  apps/graphql/lib/graphql.ex
  apps/graphql/lib/graphql/resolvers/cloud.ex
  apps/graphql/lib/graphql/schema/cloud.ex
  apps/graphql/test/mutations/cloud_mutations_test.exs
  apps/graphql/test/queries/cloud_queries_test.exs
  apps/worker/lib/worker/application.ex
  apps/worker/lib/worker/conduit/broker.ex
  apps/worker/lib/worker/conduit/subscribers/cloud.ex
  config/config.exs
  config/test.exs
  docker-compose.yml
  mix.lock
  plural/helm/plural/values.yaml
  rel/config/config.exs
  schema/schema.graphql
  www/package.json
  www/src/components/repository/packages/Docker.tsx
  www/src/components/shell/hooks/useOnboarded.ts
  www/src/generated/graphql.ts
  www/yarn.lock
Labels: enhancement

#1330 install cockroach cli in publish gh action
  .github/workflows/publish.yaml
Labels: bug-fix, hotfix

#1332 Fix worker typo
  apps/worker/lib/worker/application.ex
Labels: bug-fix, hotfix

#1334 Need to add secret read perms to plural sa
  apps/core/lib/core/clients/console.ex
  apps/core/lib/core/services/cloud/poller.ex
  plural/helm/plural/templates/rbac.yaml
Labels: bug-fix, hotfix

#1336 Need to b64 decode cockroach config secret
  Makefile
  apps/core/lib/core/clients/console.ex
  apps/core/lib/core/schema/console_instance.ex
  apps/core/lib/core/schema/postgres_cluster.ex
  apps/core/lib/core/services/cloud.ex
  apps/core/lib/core/services/cloud/configuration.ex
  apps/core/lib/core/services/cloud/poller.ex
  apps/core/lib/core/services/cloud/workflow.ex
  apps/core/priv/repo/migrations/20240810202736_rework_cockroach_clusters.exs
  apps/core/priv/repo/migrations/20240811141716_fix_db_url.exs
  apps/core/test/services/cloud/workflow_test.exs
  apps/core/test/services/cloud_test.exs
  apps/core/test/support/factory.ex
  apps/core/test/test_helper.exs
  apps/graphql/test/mutations/cloud_mutations_test.exs
  config/config.exs
  config/test.exs
  docker-compose.yml
  plural/helm/plural/Chart.yaml
  plural/helm/plural/templates/chartmuseum.yaml
  rel/config/config.exs
Labels: enhancement

#1337 remove professional plan from billing
  www/src/components/account/billing/BillingPricingCards.tsx
  www/src/components/account/billing/BillingPricingTable.tsx
  www/src/components/layout/Sidebar.tsx
Labels: enhancement, frontend

#1339 Add job to optionally create hydra db
  plural/helm/plural/Chart.yaml
  plural/helm/plural/templates/migration.yaml
Labels: enhancement

#1338 Fix cloud update synchronization
  apps/core/lib/core/clients/console.ex
  apps/core/lib/core/services/cloud/workflow.ex
  apps/graphql/lib/graphql/schema/cloud.ex
Labels: enhancement

#1340 Switch to recursive subdomains instead of hyphens
  apps/core/lib/core/clients/console.ex
  apps/core/lib/core/services/cloud.ex
  apps/core/lib/core/services/cloud/workflow.ex
Labels: enhancement

#1343 Better cloud subdomaining
  .github/workflows/publish.yaml
  apps/core/lib/core/clients/console.ex
  apps/core/lib/core/services/cloud.ex
  apps/core/priv/repo/seeds/00_bootstrap.exs
  apps/core/priv/repo/seeds/012_enterprise_plan.exs
  config/config.exs
  plural/helm/plural/Chart.yaml
  plural/helm/plural/templates/_helpers.tpl
  plural/helm/plural/templates/deployment.yaml
  plural/helm/plural/templates/migration.yaml
  plural/helm/plural/values.yaml
  plural/manifests/context.yaml
  rel/config/config.exs
Labels: bug-fix, hotfix

#1344 Fix chart templating
  plural/helm/plural/Chart.yaml
  plural/helm/plural/templates/deployment.yaml
Labels: bug-fix, hotfix

#1345 Fix release process
  .github/workflows/publish.yaml
  plural/manifests/context.yaml
Labels: bug-fix, hotfix

#1346 Fix migration name generation
  plural/helm/plural/Chart.yaml
  plural/helm/plural/templates/_helpers.tpl
Labels: bug-fix, hotfix

#1347 Ignore migration jobs
  plural/helm/plural/Chart.yaml
  plural/helm/plural/templates/migration.yaml
Labels: bug-fix, hotfix

#1348 stabilize secret key base
  plural/helm/plural/Chart.yaml
  plural/helm/plural/templates/secrets.yaml
Labels: bug-fix, hotfix

#1350 Add legacy boolean to clusters
  apps/core/lib/core/schema/cluster.ex
  apps/core/lib/core/schema/upgrade_queue.ex
  apps/core/lib/core/services/clusters.ex
  apps/core/priv/repo/migrations/20240827164453_add_legacy_flag_clusters.exs
  apps/core/test/services/clusters_test.exs
  apps/graphql/lib/graphql/schema/cluster.ex
  apps/graphql/lib/graphql/schema/upgrade.ex
  schema/schema.graphql
  www/src/generated/graphql.ts
Labels: enhancement

#1353 Only allow oauth login against current login method
  apps/core/lib/core/schema/account.ex
  apps/core/lib/core/schema/validations.ex
  apps/core/lib/core/services/cloud.ex
  apps/core/lib/core/services/users.ex
  apps/core/test/services/accounts_test.exs
  apps/core/test/services/cloud_test.exs
  apps/core/test/services/users_test.exs
Labels: enhancement

#1354 Console sideload url format
  apps/graphql/lib/graphql/resolvers/cloud.ex
  apps/graphql/mix.exs
  apps/graphql/test/queries/cloud_queries_test.exs
  mix.lock
  schema/schema.graphql
Labels: enhancement

#1356 Fix cloud instance validations
  .github/PULL_REQUEST_TEMPLATE.md
  apps/core/lib/core/schema/console_instance.ex
  apps/core/lib/core/services/cloud.ex
Labels: enhancement

#1357 Query DNS before finalizing cloud instances
  apps/core/lib/core/schema/console_instance.ex
  apps/core/lib/core/services/cloud/workflow.ex
Labels: enhancement
