Repository pluralsh/plural, pull requests merged in 2024-05, with the labels that each got.

#1304 fixed sidebar button links
  www/src/components/layout/Sidebar.tsx
Labels: bug-fix, frontend

#1306 deprecate cloud shell in onboarding
  www/src/components/shell/onboarding/Onboarding.tsx
  www/src/components/shell/onboarding/OnboardingFlow.tsx
  www/src/components/shell/onboarding/context/hooks.ts
  www/src/components/shell/onboarding/sections/cloud/CloudStep.tsx
Labels: enhancement, frontend

#1309 Disable docker image scans
  config/prod.exs
Labels: enhancement, hotfix
