Repository pluralsh/plural, pull requests merged in 2024-10, with the labels that each got.

#1371 add support for dedicated cloud instances
  www/src/components/create-cluster/CreateCluster.tsx
  www/src/components/create-cluster/CreateClusterActions.tsx
  www/src/components/create-cluster/CreateClusterWizard.tsx
  www/src/components/create-cluster/steps/ChooseCloudStep.tsx
  www/src/components/create-cluster/steps/ChooseHostingOptionStep.tsx
  www/src/components/create-cluster/steps/ConfigureCloudInstanceStep.tsx
  www/src/components/create-cluster/steps/InstallCliStep.tsx
  www/src/components/overview/clusters/plural-cloud/CloudInstanceTableCols.tsx
  www/src/components/overview/clusters/plural-cloud/ConsoleInstanceOIDC.tsx
  www/src/components/shell/onboarding/OnboardingCardButton.tsx
  www/src/components/shell/onboarding/sections/cloud/CloudOption.tsx
  www/src/generated/graphql.ts
  www/src/graph/pluralCloud.graphql
Labels: enhancement, frontend

#1372 Implement user-bound oidc providers
  apps/core/lib/core/policies/oauth.ex
  apps/core/lib/core/schema/oidc_provider.ex
  apps/core/lib/core/services/base.ex
  apps/core/lib/core/services/oauth.ex
  apps/core/lib/core/services/repositories.ex
  apps/core/priv/repo/migrations/20241005171529_add_owner_id_oidc_provider.exs
  apps/core/test/services/oauth_test.exs
  apps/graphql/lib/graphql/resolvers/oauth.ex
  apps/graphql/lib/graphql/resolvers/repository.ex
  apps/graphql/lib/graphql/schema/oauth.ex
  apps/graphql/lib/graphql/schema/repository.ex
  apps/graphql/test/mutations/repository_mutation_test.exs
  apps/graphql/test/queries/oauth_queries_test.exs
  config/config.exs
  schema/schema.graphql
  www/src/generated/graphql.ts
Labels: enhancement

#1373 fix broken tables on account tab
  www/src/components/account/GroupsList.tsx
  www/src/components/utils/List.tsx
Labels: bug-fix

#1374 update DS
  www/package.json
  www/src/_deprecated/components/incidents/Severity.tsx
  www/src/components/account/Account.tsx
  www/src/components/account/AccountSidenav.tsx
  www/src/components/account/billing/BillingPricingTable.tsx
  www/src/components/account/invite/InviteUser.tsx
  www/src/components/account/invite/InviteUserModal.tsx
  www/src/components/audits/AuditDirectory.tsx
  www/src/components/cluster/ClusterAdminsModal.tsx
  www/src/components/create-cluster/CreateCluster.tsx
  www/src/components/layout/Sidebar.tsx
  www/src/components/marketplace/MarketplaceRepositories.tsx
  www/src/components/profile/ListItem.tsx
  www/src/components/repository/Repository.tsx
  www/src/components/repository/RepositoryEdit.tsx
  www/src/components/shell/onboarding/sections/cloud/CloudStep.tsx
  www/src/components/shell/onboarding/sections/cloud/ProviderSelection.tsx
  www/src/components/users/settings/UserSettingsModal.tsx
  www/src/components/utils/Link.tsx
  www/src/components/utils/List.tsx
  www/src/components/utils/group/CreateGroup.tsx
  www/vitest.config.ts
  www/yarn.lock
Labels: enhancement, frontend

#1375 fix: Ensure OIDC provider UI can handle OIDC providers w/o installations
  www/package.json
  www/src/components/account/Roles.tsx
  www/src/components/account/User.tsx
  www/src/components/account/billing/queries.ts
  www/src/components/account/queries.ts
  www/src/components/app/oidc/OIDC.tsx
  www/src/components/app/queries.ts
  www/src/components/audits/queries.ts
  www/src/components/layout/Sidebar.tsx
  www/src/components/layout/WithNotifications.tsx
  www/src/components/layout/queries.ts
  www/src/components/marketplace/MarketplaceStacks.tsx
  www/src/components/marketplace/queries.ts
  www/src/components/oidc/OAuthConsent.tsx
  www/src/components/oidc/queries.ts
  www/src/components/overview/clusters/SelfHostedTableCols.tsx
  www/src/components/profile/MyProfile.tsx
  www/src/components/publisher/queries.ts
  www/src/components/repository/RepositorySideNav.tsx
  www/src/components/repository/packages/Chart.tsx
  www/src/components/repository/packages/Docker.tsx
  www/src/components/repository/packages/Terraform.tsx
  www/src/components/roadmap/Roadmap.tsx
  www/src/components/shell/queries.ts
  www/src/components/stack/Stack.tsx
  www/src/components/stack/misc.tsx
  www/src/components/stack/queries.ts
  www/src/components/stack/types.ts
  www/src/components/users/queries.ts
  www/src/components/utils/tableFetchHelpers.tsx
  www/src/components/utils/useFetchPaginatedData.tsx
  www/src/generated/graphql.ts
  www/src/graph/notifications.graphql
  www/src/graph/oauth.graphql
  www/src/graph/recipes.graphql
  www/src/models/incidents.ts
  www/src/models/repo.ts
  www/src/utils/graphql.ts
  www/yarn.lock
Labels: bug-fix

#1376 add tooltips to cloud instance oidc and manager edit buttons
  www/package.json
  www/src/App.tsx
  www/src/components/overview/clusters/plural-cloud/CloudInstanceTableCols.tsx
  www/src/components/overview/clusters/plural-cloud/ConsoleInstanceOIDC.tsx
  www/src/utils/shouldForwardProp.ts
  www/yarn.lock
Labels: enhancement, frontend

#1378 Improve hydra error messages
  apps/core/lib/core/clients/hydra.ex
  apps/core/test/services/cloud/workflow_test.exs
  apps/core/test/test_helper.exs
Labels: enhancement

#1379 update ds and fix console errors
  www/package.json
  www/src/App.tsx
  www/src/components/marketplace/RepoCardList.tsx
  www/src/components/utils/layout/ResponsiveLayoutContentContainer.tsx
  www/yarn.lock
Labels: enhancement, frontend

#1380 fix crashes from grommet layer
  www/src/components/app/AppMetadataPanel.tsx
  www/src/components/cluster/ClusterMetadataPanel.tsx
  www/src/components/shell/terminal/actionbar/cheatsheet/Cheatsheet.tsx
  www/src/components/users/EmailConfirmation.tsx
  www/src/components/utils/InfoPanel.tsx
Labels: bug-fix, frontend

#1381 add new pricing page
  www/src/components/account/billing/BillingManagePlan.tsx
  www/src/components/account/billing/BillingPricingCard.tsx
  www/src/components/account/billing/BillingPricingCards.tsx
  www/src/components/account/billing/BillingPricingTable.tsx
  www/src/components/account/billing/BillingStartTrialModal.tsx
  www/src/components/account/billing/PaymentForm.tsx
  www/src/components/layout/Sidebar.tsx
Labels: enhancement, frontend

#1382 feat: Plural OIDC clients
  www/package.json
  www/src/components/app/oidc/OIDC.tsx
  www/src/components/cluster/Cluster.tsx
  www/src/components/cluster/ClusterApps.tsx
  www/src/components/overview/clusters/plural-cloud/CloudInstanceTableCols.tsx
  www/src/components/overview/clusters/plural-cloud/ConsoleInstanceOIDC.tsx
  www/src/components/overview/clusters/plural-cloud/DeletePluralOIDCClient.tsx
  www/src/components/overview/clusters/plural-cloud/EditPluralOIDCClient.tsx
  www/src/components/overview/clusters/plural-cloud/EditPluralOIDCClients.tsx
  www/src/generated/graphql.ts
  www/src/graph/oauth.graphql
  www/yarn.lock
Labels: enhancement

#1383 enhancement: OIDC styling improvements
  www/src/components/overview/clusters/plural-cloud/EditPluralOIDCClient.tsx
  www/src/components/overview/clusters/plural-cloud/EditPluralOIDCClients.tsx
Labels: enhancement

#1384 README update
  README.md
Labels: documentation, enhancement, hotfix

#1385 Add anchors to name regex
  apps/core/lib/core/schema/console_instance.ex
  apps/core/test/services/cloud_test.exs
Labels: bug-fix, hotfix
