Repository pluralsh/plural, pull requests merged in 2025-08, with the labels that each got.

#1451 Add delete_namespace sync config to cloud shared service setups
  apps/core/lib/core/services/cloud/workflow/shared.ex
Labels: enhancement

#1454 fix: Invite view fixes
  www/src/components/Invite.tsx
  www/src/generated/graphql.ts
  www/src/graph/invite.graphql
Labels: bug-fix

#1455 Fix dedicated stack provisioning
  apps/core/lib/core/services/cloud/configuration.ex
  apps/core/test/services/cloud/workflow_test.exs
Labels: enhancement, backend

#1456 add restart to create cluster wizard
  www/src/components/create-cluster/CreateCluster.tsx
  www/src/components/create-cluster/CreateClusterActions.tsx
  www/src/components/overview/clusters/plural-cloud/DeleteInstance.tsx
Labels: enhancement, frontend
