Repository pluralsh/plural, pull requests merged in 2025-09, with the labels that each got.

#1459 sanitize console urls
  www/src/components/create-cluster/steps/AuthenticationStep.tsx
  www/src/components/overview/clusters/SelfHostedTableCols.tsx
  www/src/components/overview/clusters/all/AllClustersTableCols.tsx
  www/src/components/overview/clusters/plural-cloud/CloudInstanceTableCols.tsx
Labels: bug-fix, frontend

#1460 Add domain mapping feature with email validation
  apps/core/lib/core.ex
  apps/core/lib/core/schema/domain_mapping.ex
  apps/core/lib/core/schema/user.ex
  apps/core/lib/core/services/accounts.ex
  apps/core/lib/core/services/users.ex
  apps/core/priv/generic_emails.txt
  apps/core/test/services/accounts_test.exs
  apps/core/test/services/users_test.exs
  apps/core/test/support/schema_case.ex
  apps/graphql/lib/graphql/schema/account.ex
  docker-compose.yml
  schema/schema.graphql
  www/package.json
  www/src/App.tsx
  www/src/components/account/AccountAttributes.tsx
  www/src/components/create-cluster/CreateClusterActions.tsx
  www/src/components/create-cluster/CreateClusterWizard.tsx
  www/src/components/create-cluster/steps/AuthenticationStep.tsx
  www/src/components/create-cluster/steps/DeployLocallyStep.tsx
  www/src/components/login/CurrentUser.tsx
  www/src/components/overview/clusters/Clusters.tsx
  www/src/components/users/EmailConfirmation.tsx
  www/src/components/users/LoginPortal.tsx
  www/src/components/users/MagicLogin.tsx
  www/src/components/users/OAuthCallback.tsx
  www/src/components/users/SSOCallback.tsx
  www/src/components/users/queries.ts
  www/src/components/users/types.ts
  www/src/components/users/utils.ts
  www/src/generated/graphql.ts
  www/src/graph/account.graphql
  www/src/graph/users.graphql
  www/src/helpers/client.ts
  www/src/helpers/growthbook.ts
  www/yarn.lock
Labels: enhancement

#1461 Add delete_user tool
  apps/core/lib/core/mcp/server.ex
  apps/core/lib/core/mcp/tools/delete_user.ex
Labels: enhancement

#1462 Fix delete_user tool def
  apps/core/lib/core/mcp/tools/delete_user.ex
Labels: bug-fix, hotfix
