Repository pluralsh/plural, pull requests merged in 2025-06, with the labels that each got.

#1425 fix console url
  www/src/components/overview/clusters/plural-cloud/CloudInstanceTableCols.tsx
Labels: bug-fix, frontend

#1427 temporarily disable pro plan
  www/src/components/account/billing/BillingManagePlan.tsx
  www/src/components/account/billing/BillingPricingCards.tsx
Labels: enhancement, frontend

#1429 Exclusively set customer and customer_email
  apps/core/lib/core/services/payments.ex
Labels: bug-fix

#1430 replace old upgrade method with stripe checkout
  apps/core/lib/core/services/payments.ex
  www/src/components/account/billing/BillingBankCards.tsx
  www/src/components/account/billing/BillingLegacyUserBanner.tsx
  www/src/components/account/billing/BillingLegacyUserMessage.tsx
  www/src/components/account/billing/BillingManagePlan.tsx
  www/src/components/account/billing/BillingMigrationModal.tsx
  www/src/components/account/billing/BillingPricingCards.tsx
  www/src/components/account/billing/BillingPricingTable.tsx
  www/src/components/account/billing/BillingTrialBanner.tsx
  www/src/components/account/billing/BillingTrialMessage.tsx
  www/src/components/account/billing/BillingUpgradeToProfessionalModal.tsx
  www/src/components/account/billing/ConfirmPayment.tsx
  www/src/components/account/billing/PaymentForm.tsx
  www/src/components/account/billing/hooks.tsx
  www/src/components/create-cluster/steps/ChooseCloudStep.tsx
  www/src/components/create-cluster/steps/ChooseHostingOptionStep.tsx
  www/src/components/create-cluster/steps/ConfigureCloudInstanceStep.tsx
  www/src/generated/graphql.ts
  www/src/graph/payments.graphql
Labels: enhancement, frontend

#1431 remove stripe feature flag
  apps/worker/lib/worker/conduit/subscribers/cloud.ex
  www/src/components/account/billing/BillingManagePlan.tsx
Labels: bug-fix, frontend

#1432 Add explicit db creds to cloud services/stacks
  apps/core/lib/core/conduit/base.ex
  apps/core/lib/core/mcp/tools/modify_pro_plan.ex
  apps/core/lib/core/schema/platform_plan.ex
  apps/core/lib/core/services/cloud/configuration.ex
  apps/core/lib/core/services/payments.ex
  apps/core/priv/repo/migrations/20250611031008_add_ingest_meter.exs
  apps/rtc/lib/rtc_web/channels/upgrade_channel.ex
  apps/worker/lib/worker/conduit/broker.ex
  apps/worker/lib/worker/conduit/subscribers/billing.ex
Labels: enhancement

#1435 Add postgres cluster config
  apps/core/lib/core/services/cloud/configuration.ex
Labels: bug-fix, hotfix
