Repository pluralsh/plural, pull requests merged in 2025-03, with the labels that each got.

#1404 add TTL to create cluster flow cached state
  www/src/components/account/billing/BillingPricingCards.tsx
  www/src/components/create-cluster/CreateCluster.tsx
  www/src/components/create-cluster/steps/ChooseCloudStep.tsx
  www/src/components/create-cluster/steps/ChooseHostingOptionStep.tsx
  www/src/components/overview/clusters/ClustersHelpSection.tsx
  www/src/hooks/usePersistedState.tsx
Labels: bug-fix, frontend

#1405 enhancement: Add confirmation dialog for cloud cluster creation and fix access tokens header
  www/src/components/create-cluster/steps/ConfigureCloudInstanceStep.tsx
  www/src/components/profile/AccessTokens.tsx
Labels: enhancement

#1406 fix: Docs links
  www/src/components/cluster/ClusterMetadataPanel.tsx
  www/src/components/cluster/ClusterSidecar.tsx
  www/src/components/marketplace/MarketplaceRepositories.tsx
  www/src/components/profile/KeyBackups.tsx
  www/src/components/shell/onboarding/OnboardingTips.tsx
  www/src/components/shell/onboarding/checklist/Checklist.tsx
  www/src/components/shell/terminal/Content.tsx
  www/src/components/shell/terminal/actionbar/options/DeleteShellModal.tsx
Labels: bug-fix

#1407 More robust enterprise plan setup
  apps/core/lib/core/services/payments.ex
  apps/core/test/services/payments_test.exs
Labels: enhancement
