Repository pluralsh/plural, pull requests merged in 2025-05, with the labels that each got.

#1414 Adds the ability to add users to the oidc provider of a console insta…
  apps/core/lib/core/mcp/server.ex
  apps/core/lib/core/mcp/tools/add_oidc_binding.ex
  apps/core/lib/core/services/cloud.ex
  apps/core/test/services/cloud_test.exs
Labels: enhancement

#1415 Preserve redirect urls while modifying cloud console oidc bindings
  apps/core/lib/core/services/cloud.ex
Labels: bug-fix

#1416 Add network and oidc schemas to cloud console instances
  apps/core/lib/core/mcp/tools/cloud_reap.ex
  apps/core/lib/core/schema/console_instance.ex
  apps/core/lib/core/services/cloud/configuration.ex
  apps/core/priv/repo/migrations/20250507155235_add_cloud_network_policy.exs
  apps/graphql/lib/graphql/schema/cloud.ex
  schema/schema.graphql
  www/src/generated/graphql.ts
Labels: enhancement

#1417 Automatically add github app pem to Plural cloud consoles
  apps/core/lib/core/schema/console_instance.ex
  apps/core/lib/core/services/cloud.ex
  apps/core/lib/core/services/cloud/configuration.ex
  rel/config/plural.exs
Labels: enhancement

#1418 fix: better handle impersonation errors and hide edit oidc client when user has no permissions
  www/src/components/overview/clusters/plural-cloud/CloudInstanceTableCols.tsx
  www/src/hooks/useImpersonatedServiceAccount.tsx
Labels: bug-fix

#1419 Fix gap in service account access policy management
  apps/core/lib/core/services/accounts.ex
  apps/core/test/services/accounts_test.exs
Labels: bug-fix

#1421 add external OIDC and network policy to plural cloud instances
  www/package.json
  www/src/components/Plural.tsx
  www/src/components/account/MoreMenu.tsx
  www/src/components/account/Typeaheads.tsx
  www/src/components/app/AppSidecar.tsx
  www/src/components/overview/clusters/ClusterList.tsx
  www/src/components/overview/clusters/Clusters.tsx
  www/src/components/overview/clusters/plural-cloud/CloudInstanceTableCols.tsx
  www/src/components/overview/clusters/plural-cloud/ConsoleInstanceOIDC.tsx
  www/src/components/overview/clusters/plural-cloud/EditPluralOIDCClient.tsx
  www/src/components/overview/clusters/plural-cloud/EditPluralOIDCClients.tsx
  www/src/components/overview/clusters/plural-cloud/PluralCloudInstances.tsx
  www/src/components/overview/clusters/plural-cloud/details/PluralCloudInstanceClusterPermissions.tsx
  www/src/components/overview/clusters/plural-cloud/details/PluralCloudInstanceDetails.tsx
  www/src/components/overview/clusters/plural-cloud/details/PluralCloudInstanceDropdown.tsx
  www/src/components/overview/clusters/plural-cloud/details/PluralCloudInstanceMoreMenu.tsx
  www/src/components/overview/clusters/plural-cloud/details/login-settings/ExternalOidc.tsx
  www/src/components/overview/clusters/plural-cloud/details/login-settings/PluralCloudInstanceLoginSettings.tsx
  www/src/components/overview/clusters/plural-cloud/details/login-settings/PluralOidc.tsx
  www/src/components/overview/clusters/plural-cloud/details/network-policy/NetworkPolicyForm.tsx
  www/src/components/overview/clusters/plural-cloud/details/network-policy/PluralCloudInstanceNetworkPolicy.tsx
  www/src/components/overview/clusters/self-hosted/SelfHostedClusters.tsx
  www/src/components/utils/EditableDiv.tsx
  www/src/components/utils/ImpersonateServiceAccount.tsx
  www/src/components/utils/InputRevealer.tsx
  www/src/components/utils/Typography.tsx
  www/src/components/utils/applyNodeToRefs.ts
  www/src/contexts/ConsoleInstancesContext.tsx
  www/src/generated/graphql.ts
  www/src/graph/oauth.graphql
  www/src/graph/pluralCloud.graphql
  www/src/graph/users.graphql
  www/src/hooks/useImpersonatedServiceAccount.tsx
  www/src/hooks/useUpdateState.ts
  www/src/utils/graphql.ts
  www/src/utils/isNonNullable.ts
  www/yarn.lock
Labels: enhancement, frontend

#1420 Add support for es passwords in cloud console instances
  apps/core/lib/core/schema/console_instance.ex
  apps/core/lib/core/services/cloud.ex
  apps/core/lib/core/services/cloud/configuration.ex
  apps/core/priv/repo/migrations/20250520191648_add_es_password_field.exs
  apps/core/test/services/cloud_test.exs
Labels: enhancement
