Repository pluralsh/plural, pull requests merged in 2025-07, with the labels that each got.

#1437 cloud create menu updates
  www/src/components/create-cluster/CreateCluster.tsx
  www/src/components/create-cluster/steps/ConfigureCloudInstanceStep.tsx
Labels: enhancement, frontend

#1440 Ensure console repository is created on plural instances
  apps/core/lib/core/services/cloud.ex
  apps/core/priv/repo/seeds/016_add_console_repo.exs
  apps/core/test/services/cloud_test.exs
  config/config.exs
  rel/config/config.exs
Labels: enhancement

#1442 Fix frontend domain inference
  .github/workflows/test.yaml
  apps/core/lib/core/services/cloud.ex
  apps/graphql/lib/graphql/resolvers/cloud.ex
  apps/graphql/lib/graphql/schema/cloud.ex
  plural/helm/plural/Chart.yaml
  plural/helm/plural/values.yaml
  rel/config/cron.exs
  schema/schema.graphql
  www/src/generated/graphql.ts
Labels: enhancement

#1444 Fix env var for cron pods
  rel/config/cron.exs
Labels: bug-fix, hotfix

#1447 record bytes ingested in cluster usage history tables
  apps/core/lib/core/schema/cluster_usage_history.ex
  apps/core/lib/core/services/cloud/configuration.ex
  apps/core/priv/repo/migrations/20250723224040_add_byte_ingest_history.exs
  apps/graphql/lib/graphql/schema/cluster.ex
  apps/rtc/lib/rtc_web/channels/upgrade_channel.ex
  schema/schema.graphql
  www/src/generated/graphql.ts
Labels: enhancement

#1448 Add cluster ping api
  apps/core/lib/core/services/clusters.ex
  apps/graphql/lib/graphql/resolvers/cluster.ex
  apps/graphql/lib/graphql/schema/cluster.ex
  apps/graphql/test/mutations/cluster_mutations_test.exs
  schema/schema.graphql
  www/src/components/overview/clusters/ClusterHealth.tsx
  www/src/generated/graphql.ts
Labels: enhancement
